"use client";

import { FormEvent, useEffect, useState } from "react";
import { useRouter } from "next/navigation";
import { createClient } from "@/lib/supabase/client";
import { useTheme } from "@/context/ThemeContext";

const DEFAULT_COLOR = "#64748b";

export default function SettingsForm() {
  const router = useRouter();
  const supabase = createClient();
  const { primaryColor, setPrimaryColor, refreshTheme } = useTheme();

  const [color, setColor] = useState(primaryColor || DEFAULT_COLOR);
  const [saving, setSaving] = useState(false);
  const [message, setMessage] = useState("");
  const [error, setError] = useState("");

  useEffect(() => {
    setColor(primaryColor || DEFAULT_COLOR);
  }, [primaryColor]);

  async function handleSubmit(event: FormEvent<HTMLFormElement>) {
    event.preventDefault();
    setSaving(true);
    setMessage("");
    setError("");

    const normalized = color.trim().startsWith("#") ? color.trim() : `#${color.trim()}`;

    if (!/^#[0-9a-fA-F]{6}$/.test(normalized)) {
      setError("Please enter a valid 6-digit HEX color.");
      setSaving(false);
      return;
    }

    const { error: updateError } = await supabase
      .from("school_settings")
      .update({ theme_color: normalized })
      .eq("id", 1);

    if (updateError) {
      setError(updateError.message);
      setSaving(false);
      return;
    }

    setPrimaryColor(normalized);
    await refreshTheme();
    setColor(normalized);
    setMessage("School theme updated successfully.");
    setSaving(false);
    router.refresh();
  }

  return (
    <div className="mx-auto max-w-5xl">
      <header className="rounded-3xl border border-[var(--school-border)] bg-[var(--school-surface)] p-6 shadow-sm md:p-8">
        <p className="text-xs font-bold uppercase tracking-[0.16em] theme-primary">Administration</p>
        <div className="mt-2 flex flex-col gap-3 md:flex-row md:items-end md:justify-between">
          <div>
            <h1 className="text-3xl font-bold text-[var(--school-text)]">Admin Settings</h1>
            <p className="mt-2 text-sm text-[var(--school-muted)]">Manage central school settings used across the application.</p>
          </div>
          <button
            type="button"
            onClick={() => router.push("/admin")}
            className="w-fit rounded-xl border border-[var(--school-primary-border)] px-4 py-2 text-sm font-semibold theme-primary"
          >
            Back to Dashboard
          </button>
        </div>
      </header>

      <section className="mt-6 grid gap-6 lg:grid-cols-[1.1fr_.9fr]">
        <form onSubmit={handleSubmit} className="rounded-3xl border border-[var(--school-border)] bg-[var(--school-surface)] p-6 shadow-sm md:p-8">
          <p className="text-xs font-bold uppercase tracking-[0.14em] theme-primary">Appearance</p>
          <h2 className="mt-2 text-xl font-bold text-[var(--school-text)]">School primary color</h2>
          <p className="mt-2 text-sm leading-6 text-[var(--school-muted)]">
            This central color controls the primary visual identity. Derived hover, soft and border variants are generated by the theme system.
          </p>

          <div className="mt-7 flex flex-col gap-4 sm:flex-row sm:items-end">
            <label className="flex-1">
              <span className="mb-2 block text-sm font-semibold text-[var(--school-text)]">HEX color</span>
              <input
                value={color}
                onChange={(event) => setColor(event.target.value)}
                placeholder={DEFAULT_COLOR}
                maxLength={7}
                className="h-12 w-full rounded-xl border border-[var(--school-border)] bg-[var(--school-surface)] px-4 text-sm text-[var(--school-text)] outline-none focus:border-[var(--school-primary)]"
              />
            </label>
            <label className="w-full sm:w-28">
              <span className="mb-2 block text-sm font-semibold text-[var(--school-text)]">Preview</span>
              <input
                type="color"
                value={/^#[0-9a-fA-F]{6}$/.test(color) ? color : DEFAULT_COLOR}
                onChange={(event) => setColor(event.target.value)}
                className="h-12 w-full cursor-pointer rounded-xl border border-[var(--school-border)] bg-[var(--school-surface)] p-1"
                aria-label="Choose school primary color"
              />
            </label>
          </div>

          {error ? <p className="mt-4 rounded-xl border border-red-200 bg-red-50 px-4 py-3 text-sm text-red-700">{error}</p> : null}
          {message ? <p className="mt-4 rounded-xl border border-[var(--school-primary-border)] bg-[var(--school-primary-soft)] px-4 py-3 text-sm theme-primary">{message}</p> : null}

          <button type="submit" disabled={saving} className="mt-6 rounded-xl px-5 py-3 text-sm font-bold theme-primary-bg disabled:cursor-not-allowed disabled:opacity-60">
            {saving ? "Saving..." : "Save Theme Settings"}
          </button>
        </form>

        <aside className="rounded-3xl border border-[var(--school-border)] bg-[var(--school-surface)] p-6 shadow-sm md:p-8">
          <p className="text-xs font-bold uppercase tracking-[0.14em] theme-primary">Live preview</p>
          <div className="mt-5 rounded-2xl border border-[var(--school-primary-border)] bg-[var(--school-primary-soft)] p-5">
            <div className="flex items-center justify-between gap-4">
              <div>
                <p className="text-sm font-bold text-[var(--school-text)]">C.T. Model School</p>
                <p className="mt-1 text-xs text-[var(--school-muted)]">Theme preview</p>
              </div>
              <span className="rounded-full px-3 py-1.5 text-xs font-bold theme-primary-bg">Primary</span>
            </div>
            <button type="button" className="mt-6 w-full rounded-xl px-4 py-3 text-sm font-bold theme-primary-bg">Sample Action</button>
          </div>
          <p className="mt-5 text-xs leading-5 text-[var(--school-muted)]">Theme changes are stored in the central school settings record and loaded by the application theme provider.</p>
        </aside>
      </section>
    </div>
  );
}
