"use client";

type Fee={id:string;fee_type:string;amount:number;entry_date:string;due_date:string|null;reference_no:string|null;paid_amount:number;balance:number;last_payment_date:string|null;status:string};
type Child={id:string;student_id:string|null;student_name:string;class:string;section:string|null;student?:{fee?:{academic_year?:string|null;total_charged?:number;total_paid?:number;total_discount?:number;balance_due?:number};fees?:Fee[]}|null};
const money=(n:number)=>`৳ ${Number(n||0).toLocaleString("en-BD",{minimumFractionDigits:2,maximumFractionDigits:2})}`;
const label=(x:string)=>x.split("_").map(w=>w[0]?.toUpperCase()+w.slice(1)).join(" ");
const badge=(s:string)=>s==="PAID"?"bg-emerald-100 text-emerald-700":s==="PARTIALLY PAID"?"bg-orange-100 text-orange-700":s==="OVERDUE"?"bg-red-100 text-red-700":"bg-red-100 text-red-700";
const date=(v:string|null)=>v?new Date(`${v}T00:00:00`).toLocaleDateString("en-GB"):"Not set";

export default function PortalFees({children}:{children:Child[]}){
 return <div className="space-y-6">
  {children.map(child=>{const summary=child.student?.fee||{};const fees=child.student?.fees||[];return <section key={child.id} className="rounded-3xl border border-[var(--school-border)] bg-[var(--school-surface)] shadow-sm">
   <header className="border-b border-[var(--school-border)] bg-[var(--school-primary-soft)] p-5 sm:p-6"><p className="text-[10px] font-black uppercase tracking-[.16em] theme-primary">{child.student_id||"Temporary Student"}</p><h3 className="mt-1 text-xl font-black">{child.student_name}</h3><p className="mt-1 text-xs text-[var(--school-muted)]">Class {child.class||"-"}{child.section?` • Section ${child.section}`:""} • Academic Year {summary.academic_year||"-"}</p></header>
   <div className="p-5 sm:p-6"><div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-4"><div className="rounded-2xl border border-[var(--school-border)] p-4"><p className="text-[10px] text-[var(--school-muted)]">TOTAL CHARGED</p><p className="mt-1 text-lg font-black">{money(summary.total_charged||0)}</p></div><div className="rounded-2xl border border-[var(--school-border)] p-4"><p className="text-[10px] text-[var(--school-muted)]">TOTAL PAID</p><p className="mt-1 text-lg font-black text-emerald-700">{money(summary.total_paid||0)}</p></div><div className="rounded-2xl border border-[var(--school-border)] p-4"><p className="text-[10px] text-[var(--school-muted)]">DISCOUNT</p><p className="mt-1 text-lg font-black">{money(summary.total_discount||0)}</p></div><div className="rounded-2xl border border-[var(--school-border)] p-4"><p className="text-[10px] text-[var(--school-muted)]">BALANCE DUE</p><p className="mt-1 text-lg font-black text-red-700">{money(summary.balance_due||0)}</p></div></div>
   <div className="mt-5 space-y-3">{fees.length?fees.map(f=><article key={f.id} className="rounded-2xl border border-[var(--school-border)] p-4"><div className="flex flex-col gap-3 lg:flex-row lg:items-center lg:justify-between"><div><p className="font-black">{label(f.fee_type)}</p><p className="mt-1 text-xs text-[var(--school-muted)]">Charge Date: {date(f.entry_date)} • Last Payment: {date(f.last_payment_date)} • Due Date: {date(f.due_date)}</p>{f.reference_no&&<p className="mt-1 text-[11px] text-[var(--school-muted)]">Reference: {f.reference_no}</p>}</div><span className={`w-fit rounded-full px-3 py-1.5 text-[10px] font-black ${badge(f.status)}`}>{f.status}</span></div><div className="mt-4 grid grid-cols-3 gap-2"><div><p className="text-[9px] text-[var(--school-muted)]">CHARGE</p><p className="font-black">{money(f.amount)}</p></div><div><p className="text-[9px] text-[var(--school-muted)]">PAID</p><p className="font-black">{money(f.paid_amount)}</p></div><div><p className="text-[9px] text-[var(--school-muted)]">DUE</p><p className="font-black">{money(f.balance)}</p></div></div></article>):<div className="rounded-2xl border border-dashed border-[var(--school-border)] p-8 text-center text-sm text-[var(--school-muted)]">No fee has been assigned yet.</div>}</div>
  </div></section>})}
  {!children.length&&<div className="rounded-2xl border border-dashed border-[var(--school-border)] p-8 text-center text-sm text-[var(--school-muted)]">No approved student is linked to this account yet.</div>}
 </div>;
}
