"use client";

// Vercel build trigger: keep the normalized People profile edit state on main.

import { ChangeEvent, FormEvent, useEffect, useMemo, useState } from "react";
import { createClient } from "@/lib/supabase/client";
import { AdminPageShell } from "@/components/admin/AdminPageShell";
import { PeopleMasterData } from "./master-data";

type Category = "teacher" | "committee" | "staff" | "gpa5" | "scholarship" | "achievement";
type Profile = { id:string; category:Category; full_name:string; photo_url:string|null; designation:string|null; department:string|null; subject:string|null; committee_position:string|null; class_name:string|null; section:string|null; academic_year:string|null; exam_name:string|null; result_value:string|null; achievement_type:string|null; scholarship_type:string|null; short_description:string|null; email:string|null; phone:string|null; whatsapp:string|null; is_active:boolean; display_order:number };
const categories:{value:Category;label:string}[]=[{value:"teacher",label:"Our Teacher"},{value:"committee",label:"Management Committee"},{value:"staff",label:"Staff / Employee"},{value:"gpa5",label:"GPA-5 Achiever"},{value:"scholarship",label:"Scholarship Achiever"},{value:"achievement",label:"Other Achievement"}];
const emptyForm={category:"teacher" as Category,full_name:"",photo_url:"",designation:"",department:"",subject:"",committee_position:"",class_name:"",section:"",academic_year:"",exam_name:"",result_value:"",achievement_type:"",scholarship_type:"",short_description:"",email:"",phone:"",whatsapp:"",display_order:"0"};
const BUCKET="school_people";
function storagePathFromPublicUrl(url:string){const marker=`/storage/v1/object/public/${BUCKET}/`;const index=url.indexOf(marker);return index>=0?decodeURIComponent(url.slice(index+marker.length)):"";}
export default function PeopleAdminPage(){
 const supabase=useMemo(()=>createClient(),[]); const [form,setForm]=useState(emptyForm); const [profiles,setProfiles]=useState<Profile[]>([]); const [editingId,setEditingId]=useState<string|null>(null); const [photo,setPhoto]=useState<File|null>(null); const [loading,setLoading]=useState(true); const [saving,setSaving]=useState(false); const [message,setMessage]=useState(""); const [filter,setFilter]=useState<Category|"all">("all");
 async function loadProfiles(){setLoading(true);const {data,error}=await supabase.from("people_profiles").select("id,category,full_name,photo_url,designation,department,subject,committee_position,class_name,section,academic_year,exam_name,result_value,achievement_type,scholarship_type,short_description,email,phone,whatsapp,is_active,display_order").order("display_order").order("full_name");if(error)setMessage(error.message);else setProfiles((data??[]) as Profile[]);setLoading(false);}
 useEffect(()=>{void loadProfiles();},[]);
 const visibleProfiles=filter==="all"?profiles:profiles.filter(x=>x.category===filter); const student=form.category==="gpa5"||form.category==="scholarship";
 const update=(k:keyof typeof emptyForm,v:string)=>setForm(x=>({...x,[k]:v})); const reset=()=>{setForm(emptyForm);setEditingId(null);setPhoto(null);};
 async function upload(file:File){const ext=file.name.split(".").pop()?.toLowerCase()||"jpg";const path=`${form.category}/${crypto.randomUUID()}.${ext}`;const {error}=await supabase.storage.from(BUCKET).upload(path,file,{upsert:false});if(error)throw error;return {path,url:supabase.storage.from(BUCKET).getPublicUrl(path).data.publicUrl};}
 async function save(e:FormEvent){e.preventDefault();if(!form.full_name.trim())return setMessage("Name is required.");setSaving(true);setMessage("");try{let photoUrl=form.photo_url||null;let newPhotoPath="";if(photo){const uploaded=await upload(photo);photoUrl=uploaded.url;newPhotoPath=uploaded.path;}const payload={...form,full_name:form.full_name.trim(),photo_url:photoUrl,display_order:Number(form.display_order)||0,is_active:true};delete (payload as Record<string,unknown>).photo_url;const rpcPayload={...payload,photo_url:photoUrl};const {error}=await supabase.rpc("people_admin_save_profile",{p_payload:rpcPayload,p_id:editingId});if(error){if(newPhotoPath)await supabase.storage.from(BUCKET).remove([newPhotoPath]);throw error;}if(editingId&&form.photo_url&&newPhotoPath){const oldPath=storagePathFromPublicUrl(form.photo_url);if(oldPath&&oldPath!==newPhotoPath)await supabase.storage.from(BUCKET).remove([oldPath]);}setMessage(editingId?"Profile updated and previous photo deleted.":"Profile added successfully.");reset();await loadProfiles();}catch(err){setMessage(err instanceof Error?err.message:"Unable to save profile.");}finally{setSaving(false);}}
 function edit(x:Profile){setEditingId(x.id);setForm({...emptyForm,category:x.category,full_name:x.full_name,photo_url:x.photo_url||"",designation:x.designation||"",department:x.department||"",subject:x.subject||"",committee_position:x.committee_position||"",class_name:x.class_name||"",section:x.section||"",academic_year:x.academic_year||"",exam_name:x.exam_name||"",result_value:x.result_value||"",achievement_type:x.achievement_type||"",scholarship_type:x.scholarship_type||"",short_description:x.short_description||"",email:x.email||"",phone:x.phone||"",whatsapp:x.whatsapp||"",display_order:String(x.display_order)});setPhoto(null);window.scrollTo({top:0,behavior:"smooth"});}
 async function toggle(x:Profile){const {error}=await supabase.rpc("people_admin_set_active",{p_id:x.id,p_active:!x.is_active});if(error)setMessage(error.message);else await loadProfiles();}
 async function remove(x:Profile){if(!window.confirm(`Delete ${x.full_name}?`))return;const {error}=await supabase.rpc("people_admin_delete",{p_id:x.id});if(error){setMessage(error.message);return;}const path=x.photo_url?storagePathFromPublicUrl(x.photo_url):"";if(path)await supabase.storage.from(BUCKET).remove([path]);setMessage("Profile deleted and its storage photo was deleted.");await loadProfiles();}
 return <AdminPageShell eyebrow="People & Achievements" title="Quick Add Profiles" description="Manage teachers, committee members, staff and student achievements from one reusable profile system.">
  <div className="grid gap-6 xl:grid-cols-[minmax(0,1.05fr)_minmax(420px,.95fr)]">
   <form onSubmit={save} className="rounded-3xl border border-[var(--school-border)] bg-[var(--school-surface)] p-5 shadow-sm md:p-7"><div className="flex items-center justify-between"><div><h2 className="text-xl font-bold">{editingId?"Edit Profile":"Quick Add"}</h2><p className="mt-1 text-sm text-[var(--school-muted)]">Category controls the fields shown below.</p></div>{editingId?<button type="button" onClick={reset} className="rounded-xl border border-[var(--school-border)] px-3 py-2 text-xs font-bold">Cancel</button>:null}</div>
    <div className="mt-6 grid gap-4 md:grid-cols-2"><label className="md:col-span-2"><span className="label">Profile Type</span><select className="field" value={form.category} onChange={e=>update("category",e.target.value)}>{categories.map(x=><option key={x.value} value={x.value}>{x.label}</option>)}</select></label><label><span className="label">Full Name *</span><input className="field" value={form.full_name} onChange={e=>update("full_name",e.target.value)} required/></label><label><span className="label">Photo</span><input className="field" type="file" accept="image/*" onChange={(e:ChangeEvent<HTMLInputElement>)=>setPhoto(e.target.files?.[0]||null)}/></label>
    {(form.category==="teacher"||form.category==="staff")&&<><label><span className="label">{form.category==="staff"?"Job Title":"Designation"}</span><input className="field" value={form.designation} onChange={e=>update("designation",e.target.value)}/></label><label><span className="label">Department</span><input className="field" value={form.department} onChange={e=>update("department",e.target.value)}/></label></>}{form.category==="teacher"&&<label><span className="label">Subject</span><input className="field" value={form.subject} onChange={e=>update("subject",e.target.value)}/></label>}
    {form.category==="committee"&&<><label><span className="label">Committee</span><input className="field" value={form.department} onChange={e=>update("department",e.target.value)}/></label><label><span className="label">Position</span><input className="field" value={form.committee_position} onChange={e=>update("committee_position",e.target.value)}/></label></>}
    {student&&<><label><span className="label">Class</span><input className="field" value={form.class_name} onChange={e=>update("class_name",e.target.value)}/></label><label><span className="label">Section</span><input className="field" value={form.section} onChange={e=>update("section",e.target.value)}/></label><label><span className="label">Academic Year</span><input className="field" value={form.academic_year} onChange={e=>update("academic_year",e.target.value)}/></label><label><span className="label">Exam</span><input className="field" value={form.exam_name} onChange={e=>update("exam_name",e.target.value)}/></label><label><span className="label">Result / GPA</span><input className="field" value={form.result_value} onChange={e=>update("result_value",e.target.value)}/></label>{form.category==="scholarship"&&<label><span className="label">Scholarship Type</span><input className="field" value={form.scholarship_type} onChange={e=>update("scholarship_type",e.target.value)}/></label>}</>}
    {form.category==="achievement"&&<label><span className="label">Achievement Type</span><input className="field" value={form.achievement_type} onChange={e=>update("achievement_type",e.target.value)}/></label>}
    <label className="md:col-span-2"><span className="label">Short Description</span><textarea className="field min-h-24 py-3" value={form.short_description} onChange={e=>update("short_description",e.target.value)}/></label><div className="md:col-span-2"><p className="mb-3 text-xs font-bold uppercase tracking-[0.14em] theme-primary">Contact Information</p><div className="grid gap-4 md:grid-cols-3"><label><span className="label">Email</span><input className="field" type="email" value={form.email} onChange={e=>update("email",e.target.value)}/></label><label><span className="label">Phone</span><input className="field" value={form.phone} onChange={e=>update("phone",e.target.value)}/></label><label><span className="label">WhatsApp</span><input className="field" value={form.whatsapp} onChange={e=>update("whatsapp",e.target.value)}/></label></div></div><label><span className="label">Display Order</span><input className="field" type="number" min="0" value={form.display_order} onChange={e=>update("display_order",e.target.value)}/></label></div>
    {message?<p className="mt-4 rounded-xl bg-[var(--school-primary-soft)] px-4 py-3 text-sm font-semibold theme-primary">{message}</p>:null}<button disabled={saving} className="mt-5 w-full rounded-xl px-5 py-3 text-sm font-bold theme-primary-bg">{saving?"Saving...":editingId?"Update Profile":"Add Profile"}</button>
   </form>
   <section className="rounded-3xl border border-[var(--school-border)] bg-[var(--school-surface)] p-5 shadow-sm md:p-7"><div className="flex flex-col gap-3 sm:flex-row sm:items-center sm:justify-between"><div><h2 className="text-xl font-bold">Profiles</h2><p className="mt-1 text-sm text-[var(--school-muted)]">{profiles.length} total</p></div><select className="field sm:max-w-48" value={filter} onChange={e=>setFilter(e.target.value as Category|"all")}><option value="all">All Categories</option>{categories.map(x=><option key={x.value} value={x.value}>{x.label}</option>)}</select></div><div className="mt-5 space-y-3">{loading?<p>Loading...</p>:visibleProfiles.map(x=><article key={x.id} className="flex gap-3 rounded-2xl border border-[var(--school-border)] p-3"><div className="h-16 w-16 shrink-0 overflow-hidden rounded-xl bg-[var(--school-primary-soft)]">{x.photo_url?<img src={x.photo_url} alt={x.full_name} className="h-full w-full object-cover"/>:<div className="flex h-full items-center justify-center text-xs font-bold theme-primary">PHOTO</div>}</div><div className="min-w-0 flex-1"><p className="truncate font-bold">{x.full_name}</p><p className="text-xs text-[var(--school-muted)]">{x.category}</p></div><div className="flex gap-1"><button onClick={()=>edit(x)} className="rounded-lg border px-2 py-1 text-[11px] font-bold">Edit</button><button onClick={()=>void toggle(x)} className="rounded-lg border px-2 py-1 text-[11px] font-bold">{x.is_active?"Hide":"Show"}</button><button onClick={()=>void remove(x)} className="rounded-lg border px-2 py-1 text-[11px] font-bold text-red-700">Delete</button></div></article>)}</div></section>
  </div><PeopleMasterData/><style jsx>{`.label{display:block;margin-bottom:7px;font-size:12px;font-weight:700;color:var(--school-muted)}.field{width:100%;min-height:44px;border:1px solid var(--school-border);border-radius:12px;background:var(--school-surface);padding:0 12px;color:var(--school-text);outline:none}.field:focus{border-color:var(--school-primary);box-shadow:0 0 0 3px var(--school-primary-soft)}`}</style>
 </AdminPageShell>;
}
