"use client";

import { useCallback, useEffect, useMemo, useState } from "react";
import { createClient } from "@/lib/supabase/client";

type Overview = {
  generated_at: string;
  students: { total: number; by_class: { class: string; total: number }[]; by_class_section: { class: string; section: string; total: number }[] };
  people: { teachers: number; staff: number; other_members: number; parents: number; teacher_by_role: { role: string; total: number }[]; staff_by_department: { department: string; total: number }[] };
  academic: { classes: number; sections: number; pending_admissions: number; pending_existing_registrations: number; pending_parent_child_registrations: number; published_notices: number };
  inventory: { active_items: number; low_stock_items: number; total_units: number };
  financial: { period_start: string; income: { student_collection: number; other_income: number; total: number }; expense: { salary: number; bill_payment: number; other_expense: number; total: number }; bills: { total_payable: number; paid: number; due: number; count: number; pending_approval: number }; collection: { student_due: number; student_collected: number; other_collected: number; total_collected: number }; cash_bank: { cash: number; bank: number } };
};
const money = (n: number) => `৳ ${new Intl.NumberFormat("en-BD", { minimumFractionDigits: 2, maximumFractionDigits: 2 }).format(Number(n) || 0)}`;
const monthLabel = (v: string) => new Date(`${v}-01T00:00:00`).toLocaleDateString("en-US", { month: "long", year: "numeric" });
const Card = ({ label, value, note, cls = "" }: { label: string; value: string | number; note?: string; cls?: string }) => <div className="rounded-2xl border border-[var(--school-border)] bg-[var(--school-surface)] p-4"><p className="text-[9px] font-black uppercase tracking-wider text-[var(--school-muted)]">{label}</p><p className={`mt-1 text-xl font-black ${cls}`}>{value}</p>{note && <p className="mt-1 text-[10px] text-[var(--school-muted)]">{note}</p>}</div>;
const Section = ({ title, children }: { title: string; children: React.ReactNode }) => <div className="rounded-3xl border border-[var(--school-border)] bg-[var(--school-surface)] p-5 sm:p-6"><h2 className="text-lg font-black">{title}</h2>{children}</div>;

export default function PublicOverview() {
  const db = useMemo(() => createClient(), []);
  const [data, setData] = useState<Overview | null>(null);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState("");
  const load = useCallback(async () => {
    const { data: next, error: e } = await db.rpc("public_school_overview");
    if (e) { setError(e.message); return; }
    setError(""); setData(next as Overview); setLoading(false);
  }, [db]);
  useEffect(() => { let active = true; const refresh = async () => { if (!active || document.hidden) return; await load(); }; void refresh(); const interval = window.setInterval(() => void refresh(), 5000); const focus = () => void refresh(); const visible = () => void refresh(); window.addEventListener("focus", focus); document.addEventListener("visibilitychange", visible); return () => { active = false; window.clearInterval(interval); window.removeEventListener("focus", focus); document.removeEventListener("visibilitychange", visible); }; }, [load]);
  useEffect(() => { const channel = db.channel("public-school-overview-live").on("postgres_changes", { event: "*", schema: "public", table: "students" }, () => void load()).on("postgres_changes", { event: "*", schema: "public", table: "teacher_members" }, () => void load()).on("postgres_changes", { event: "*", schema: "public", table: "staff_members" }, () => void load()).on("postgres_changes", { event: "*", schema: "public", table: "parents" }, () => void load()).on("postgres_changes", { event: "*", schema: "public", table: "notices" }, () => void load()).on("postgres_changes", { event: "*", schema: "public", table: "inventory_items" }, () => void load()).on("postgres_changes", { event: "*", schema: "public", table: "accounts_entries" }, () => void load()).on("postgres_changes", { event: "*", schema: "public", table: "accounts_bills" }, () => void load()).on("postgres_changes", { event: "*", schema: "public", table: "accounts_bill_payments" }, () => void load()).on("postgres_changes", { event: "*", schema: "public", table: "hr_salary_payment_history" }, () => void load()).on("postgres_changes", { event: "*", schema: "public", table: "student_fee_accounts" }, () => void load()).subscribe(); return () => { void db.removeChannel(channel); }; }, [db, load]);
  const month = data?.financial.period_start?.slice(0, 7) || "";
  const net = Number(data?.financial.income.total || 0) - Number(data?.financial.expense.total || 0);
  return <main className="min-h-screen bg-[var(--school-background)] px-3 py-6 sm:px-6 lg:px-10"><div className="mx-auto max-w-7xl">
    <header className="rounded-3xl border border-[var(--school-border)] bg-[var(--school-surface)] p-6 shadow-sm sm:p-8"><p className="text-[10px] font-black uppercase tracking-[.18em] theme-primary">C.T. Model School</p><h1 className="mt-2 text-2xl font-black sm:text-3xl">School Overview</h1><p className="mt-2 max-w-3xl text-sm leading-6 text-[var(--school-muted)]">Complete read-only school snapshot: students, classes, people, academic activity, inventory and live financial position.</p><p className="mt-3 text-[10px] font-bold uppercase tracking-wider text-[var(--school-muted)]">Live view • automatically refreshed</p></header>
    {error && <div className="mt-5 rounded-xl border border-red-200 bg-red-50 p-4 text-sm font-semibold text-red-700">Unable to load the school overview. Retrying automatically...</div>}
    {loading ? <div className="mt-5 rounded-3xl border border-[var(--school-border)] bg-[var(--school-surface)] p-12 text-center text-sm text-[var(--school-muted)]">Loading live school overview...</div> : data && <section className="mt-5 space-y-5">
      <div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-4"><Card label="Total Students" value={data.students.total} note={`${data.academic.classes} class(es) • ${data.academic.sections} section(s)`} cls="theme-primary"/><Card label="Teachers" value={data.people.teachers} note="Active teaching members" cls="theme-primary"/><Card label="Staff" value={data.people.staff} note="Active non-teaching staff" cls="theme-primary"/><Card label="Parents / Guardians" value={data.people.parents} note="Active parent accounts" cls="theme-primary"/></div>
      <Section title="Students by Class"><div className="mt-4 grid gap-3 sm:grid-cols-2 lg:grid-cols-4">{data.students.by_class.map((item) => <div key={item.class} className="rounded-2xl border border-[var(--school-border)] p-4"><p className="text-xs font-black uppercase tracking-wider text-[var(--school-muted)]">Class {item.class}</p><p className="mt-1 text-2xl font-black theme-primary">{item.total}</p><p className="text-xs text-[var(--school-muted)]">student(s)</p></div>)}</div><div className="mt-4 grid gap-2 sm:grid-cols-2 lg:grid-cols-4">{data.students.by_class_section.map((item) => <div key={`${item.class}-${item.section}`} className="flex items-center justify-between rounded-xl bg-[var(--school-background)] px-4 py-3 text-sm"><span>Class {item.class} • Section {item.section}</span><b>{item.total}</b></div>)}</div></Section>
      <div className="grid gap-5 lg:grid-cols-2"><Section title="People"><div className="mt-4 grid grid-cols-2 gap-3"><Card label="Teachers" value={data.people.teachers}/><Card label="Staff" value={data.people.staff}/><Card label="Other Members" value={data.people.other_members}/><Card label="Parents" value={data.people.parents}/></div>{data.people.staff_by_department.length > 0 && <div className="mt-4 space-y-2">{data.people.staff_by_department.map((x) => <div key={x.department} className="flex justify-between border-b border-[var(--school-border)] py-2 text-sm"><span>{x.department}</span><b>{x.total}</b></div>)}</div>}</Section><Section title="Academic & Website Activity"><div className="mt-4 grid grid-cols-2 gap-3"><Card label="Classes" value={data.academic.classes}/><Card label="Sections" value={data.academic.sections}/><Card label="Published Notices" value={data.academic.published_notices}/><Card label="Pending Admissions" value={data.academic.pending_admissions} cls="text-orange-700"/><Card label="Existing Student Requests" value={data.academic.pending_existing_registrations} cls="text-orange-700"/><Card label="Parent Child Requests" value={data.academic.pending_parent_child_registrations} cls="text-orange-700"/></div></Section></div>
      <Section title="Inventory Overview"><div className="mt-4 grid gap-3 sm:grid-cols-3"><Card label="Active Items" value={data.inventory.active_items}/><Card label="Total Units" value={data.inventory.total_units}/><Card label="Low Stock" value={data.inventory.low_stock_items} cls={data.inventory.low_stock_items > 0 ? "text-red-700" : "theme-primary"}/></div></Section>
      <Section title={`Financial Overview • ${monthLabel(month)}`}><div className="mt-4 grid gap-3 sm:grid-cols-2 lg:grid-cols-4"><Card label="Total Income" value={money(data.financial.income.total)} cls="theme-primary"/><Card label="Total Expense" value={money(data.financial.expense.total)} cls="text-red-700"/><Card label="Net Movement" value={money(net)} cls={net >= 0 ? "theme-primary" : "text-red-700"}/><Card label="Student Collection" value={money(data.financial.collection.student_collected)} cls="theme-primary"/></div><div className="mt-4 grid gap-4 lg:grid-cols-2"><div className="rounded-2xl bg-[var(--school-background)] p-4 space-y-3 text-sm"><div className="flex justify-between"><span>Salary</span><b>{money(data.financial.expense.salary)}</b></div><div className="flex justify-between"><span>Bill Payments</span><b>{money(data.financial.expense.bill_payment)}</b></div><div className="flex justify-between"><span>Other Expense</span><b>{money(data.financial.expense.other_expense)}</b></div></div><div className="rounded-2xl bg-[var(--school-background)] p-4 space-y-3 text-sm"><div className="flex justify-between"><span>Bills Payable</span><b>{money(data.financial.bills.total_payable)}</b></div><div className="flex justify-between"><span>Bills Paid</span><b>{money(data.financial.bills.paid)}</b></div><div className="flex justify-between"><span>Bills Due</span><b className="text-red-700">{money(data.financial.bills.due)}</b></div><div className="flex justify-between"><span>Cash / Bank</span><b>{money(Number(data.financial.cash_bank.cash) + Number(data.financial.cash_bank.bank))}</b></div></div></div></Section>
      <div className="rounded-2xl border border-dashed border-[var(--school-border)] bg-[var(--school-surface)] p-5 text-center"><p className="text-sm font-black">View Only</p><p className="mt-1 text-xs leading-5 text-[var(--school-muted)]">Monitoring only. No create, edit, approve, delete, payment or transaction action is available on /overview.</p></div>
    </section>}
  </div></main>;
}
