import Link from "next/link";
import { redirect } from "next/navigation";
import { getCurrentAdminPermissions } from "@/lib/adminPermissions";
import { AdminPageShell } from "@/components/admin/AdminPageShell";

const isSuperAdmin=(name:string)=>["admin","administrator","super_admin","super admin"].includes(name.toLowerCase().replace(/_/g," "));
type Portal={key:string;title:string;description:string;sections:{label:string;href:string;description:string}[]};
const portals:Portal[]=[
 {key:"admin",title:"Admin Portal",description:"Core administration, access control and system settings.",sections:[{label:"Dashboard",href:"/admin",description:"Central administration overview"},{label:"Role Management",href:"/admin/roles",description:"Existing role and permission builder"},{label:"PR & PO Permissions",href:"/admin/roles/procurement",description:"Separate procurement permissions"},{label:"Settings",href:"/admin/settings",description:"System configuration"}]},
 {key:"accounts",title:"Accounts Portal",description:"Financial operations and account-related workflows.",sections:[{label:"Accounts",href:"/admin/accounts",description:"Open the existing Accounts workspace"},{label:"Ledger",href:"/admin/accounts?tab=ledger",description:"Future general ledger workspace"},{label:"Income",href:"/admin/accounts?tab=income",description:"Student income and collection workflow"},{label:"Expense & Bills",href:"/admin/accounts?tab=expenses",description:"Bills, expenses and payment workflow"}]},
 {key:"store",title:"Store Portal",description:"Inventory, stock and store operations.",sections:[{label:"Inventory",href:"/admin/inventory",description:"Items, stock and inventory operations"},{label:"Item SR",href:"/admin/item-sr",description:"Service Request workflow"},{label:"PR & PO",href:"/admin/inventory/procurement",description:"Procurement workflow"}]},
 {key:"members",title:"Members Portal",description:"People, member records and related administration.",sections:[{label:"Members",href:"/admin/members",description:"Member administration"},{label:"People & Achievements",href:"/admin/people",description:"People profiles and achievements"},{label:"Parents & Guardians",href:"/admin/parents",description:"Parent and guardian administration"}]},
 {key:"hr",title:"HR Portal",description:"Human resources and staff administration.",sections:[{label:"Human Resources",href:"/admin/hr",description:"Existing HR workspace"},{label:"Teachers & Staff",href:"/admin/people",description:"Staff and teacher records"}]},
 {key:"academic",title:"Academic Portal",description:"Academic records, results and school information.",sections:[{label:"Results & Reports",href:"/admin/results",description:"Results and academic reporting"},{label:"Notices",href:"/admin/notices",description:"School notices and communication"}]},
];
export default async function AdminPortalsPage(){const access=await getCurrentAdminPermissions();if(!access||!isSuperAdmin(access.profile.role.name))redirect("/admin");return <AdminPageShell eyebrow="Super Admin • Full Control" title="Portal Control Center" description="One clean control surface for all related management portals. Existing individual pages remain unchanged. Future related sections can be grouped into the appropriate portal without changing their underlying workflow."><div className="mb-5 rounded-2xl border border-[var(--school-primary-border)] bg-[var(--school-primary-soft)] p-4"><p className="text-sm font-black theme-primary">Full Control Portal System</p><p className="mt-1 text-xs leading-5 text-[var(--school-muted)]">Open a portal to see only the sections related to that area. This is a navigation layer only. Existing permissions, routes, business logic and individual pages continue to work as before.</p></div><div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-3">{portals.map(portal=><section key={portal.key} className="group rounded-3xl border border-[var(--school-border)] bg-[var(--school-surface)] p-5 shadow-sm transition hover:-translate-y-0.5 hover:shadow-md"><div className="flex items-start justify-between gap-3"><div><span className="inline-flex rounded-full border border-[var(--school-border)] px-2.5 py-1 text-[9px] font-black uppercase tracking-[.14em] theme-primary">Portal</span><h2 className="mt-3 text-lg font-black">{portal.title}</h2><p className="mt-1 text-xs leading-5 text-[var(--school-muted)]">{portal.description}</p></div><span className="flex h-10 w-10 shrink-0 items-center justify-center rounded-2xl bg-[var(--school-primary-soft)] text-lg font-black theme-primary">{portal.sections.length}</span></div><div className="mt-4 space-y-2">{portal.sections.map(section=><Link key={section.label+section.href} href={section.href} className="block rounded-2xl border border-[var(--school-border)] bg-[var(--school-background)] p-3 transition hover:border-[var(--school-primary-border)] hover:bg-[var(--school-primary-soft)]"><div className="flex items-center justify-between gap-3"><span className="text-sm font-black">{section.label}</span><span className="theme-primary">→</span></div><p className="mt-1 text-[10px] leading-4 text-[var(--school-muted)]">{section.description}</p></Link>)}</div></section>)}</div><div className="mt-5 rounded-3xl border border-dashed border-[var(--school-border)] bg-[var(--school-surface)] p-5"><p className="text-[10px] font-black uppercase tracking-[.16em] theme-primary">Future Ready</p><h3 className="mt-1 text-base font-black">Add new related sections inside a portal</h3><p className="mt-1 text-xs leading-5 text-[var(--school-muted)]">When a new related module is added later, place its navigation entry inside the matching portal instead of making the Super Admin sidebar longer.</p></div></AdminPageShell>}
