"use client";
import { FormEvent, useEffect, useMemo, useState } from "react";
import { createClient } from "@/lib/supabase/client";
import { AdminPageShell } from "@/components/admin/AdminPageShell";

type MemberType="staff"|"teacher"|"accounts"|"other";
type Member={member_type:MemberType;id:string;member_id:string;full_name:string;password_text:string;role:string;subject?:string|null;designation:string|null;department:string|null;email:string|null;phone:string|null;is_active:boolean};
type FormState={id:string|null;type:MemberType;full_name:string;password:string;role:string;designation:string;department:string;subject:string;email:string;phone:string;whatsapp:string;nid:string;address:string;joining_date:string;photo_url:string;details:string};
const blank:FormState={id:null,type:"staff",full_name:"",password:"",role:"Staff",designation:"",department:"",subject:"",email:"",phone:"",whatsapp:"",nid:"",address:"",joining_date:"",photo_url:"",details:""};
const defaults=(t:MemberType)=>t==="teacher"?{role:"Teacher",designation:"Teacher",department:"Academic"}:t==="accounts"?{role:"Accounts",designation:"Accounts",department:"Accounts"}:t==="other"?{role:"Other",designation:"",department:""}:{role:"Staff",designation:"",department:""};
const idPrefix=(t:MemberType)=>t==="staff"?"STID00001":t==="teacher"?"TCID00001":t==="accounts"?"ACID00001":"OTID00001";

export default function MembersPage(){
 const supabase=useMemo(()=>createClient(),[]);const[type,setType]=useState<MemberType>("staff");const[members,setMembers]=useState<Member[]>([]);const[form,setForm]=useState<FormState>({...blank});const[search,setSearch]=useState("");const[loading,setLoading]=useState(false);const[saving,setSaving]=useState(false);const[message,setMessage]=useState("");
 async function load(){setLoading(true);const{data,error}=await supabase.rpc("store_admin_list_members",{p_member_type:type,p_search:search||null});if(error)setMessage(error.message);else setMembers((data??[])as Member[]);setLoading(false);}
 useEffect(()=>{void load();},[type]);
 function changeType(t:MemberType){setType(t);setForm({...blank,type:t,...defaults(t)});setMessage("");}
 function edit(m:Member){setForm({...blank,type:m.member_type,id:m.id,full_name:m.full_name,password:m.password_text,role:m.role,designation:m.designation||"",department:m.department||"",subject:m.subject||"",email:m.email||"",phone:m.phone||"",whatsapp:"",nid:"",address:"",joining_date:"",photo_url:"",details:""});window.scrollTo({top:0,behavior:"smooth"});}
 async function save(e:FormEvent){e.preventDefault();setSaving(true);setMessage("");let details:Record<string,unknown>={};if(form.details.trim()){try{details=JSON.parse(form.details);}catch{setMessage("Other Details must be valid JSON or empty.");setSaving(false);return;}}
  const{data,error}=await supabase.rpc("store_admin_save_member",{p_member_type:form.type,p_id:form.id,p_full_name:form.full_name,p_password:form.password,p_role:form.role,p_designation:form.designation,p_department:form.department,p_subject:form.subject,p_email:form.email,p_phone:form.phone,p_whatsapp:form.whatsapp,p_nid:form.nid,p_address:form.address,p_joining_date:form.joining_date||null,p_photo_url:form.photo_url,p_details:details});
  if(error)setMessage(error.message);else{setMessage(form.id?"Member updated successfully.":`Member created: ${(data as{member_id:string}).member_id}`);setForm({...blank,type:form.type,...defaults(form.type)});await load();}setSaving(false);
 }
 async function remove(m:Member){if(!window.confirm(`Remove ${m.full_name} (${m.member_id})?`))return;const{error}=await supabase.rpc("store_admin_remove_member",{p_member_type:m.member_type,p_id:m.id});if(error)setMessage(error.message);else{setMessage(`${m.member_id} removed.`);await load();}}
 const visible=members.filter(m=>{const q=search.trim().toLowerCase();return!q||[m.member_id,m.full_name,m.role,m.designation,m.department,m.email,m.phone].some(v=>v?.toLowerCase().includes(q));});
 return <AdminPageShell eyebrow="Community Access" title="Staff, Teachers, Accounts & Others" description="Admin-created internal members only. Parents, Students and Management Committee are excluded because they use their own registration/profile flows.">
  <div className="mb-6 flex flex-wrap gap-2">{(["staff","teacher","accounts","other"]as MemberType[]).map(t=><button key={t} onClick={()=>changeType(t)} className={`rounded-xl px-4 py-2 text-sm font-bold capitalize ${type===t?"theme-primary-bg":"border border-[var(--school-border)] bg-[var(--school-surface)]"}`}>{t}</button>)}</div>
  {message?<p className="mb-5 rounded-xl bg-[var(--school-primary-soft)] px-4 py-3 text-sm font-semibold theme-primary">{message}</p>:null}
  <div className="grid gap-6 xl:grid-cols-[minmax(360px,.8fr)_minmax(0,1.2fr)]">
   <form onSubmit={save} className="rounded-3xl border border-[var(--school-border)] bg-[var(--school-surface)] p-5 shadow-sm md:p-7"><h2 className="text-xl font-black">{form.id?"Edit":"Add"} {type}</h2><p className="mt-1 text-sm text-[var(--school-muted)]">ID is generated automatically: {idPrefix(type)} and increases for every new member.</p>
    <div className="mt-6 grid gap-4 sm:grid-cols-2"><label className="sm:col-span-2"><span className="label">Full Name *</span><input className="field" value={form.full_name} onChange={e=>setForm({...form,full_name:e.target.value})} required/></label><label><span className="label">Password *</span><input className="field" value={form.password} onChange={e=>setForm({...form,password:e.target.value})} required/></label><label><span className="label">Role *</span><input className="field" value={form.role} onChange={e=>setForm({...form,role:e.target.value})} required/></label>
     {type==="teacher"?<label className="sm:col-span-2"><span className="label">Subject</span><input className="field" value={form.subject} onChange={e=>setForm({...form,subject:e.target.value})}/></label>:null}{type==="accounts"?<label className="sm:col-span-2"><span className="label">Accounts Role</span><select className="field" value={form.role} onChange={e=>setForm({...form,role:e.target.value})}>{["Accounts Manager","Accounts Officer","Accountant","Cashier","Billing Officer","Finance Officer","Other Accounts"].map(x=><option key={x}>{x}</option>)}</select></label>:null}{type==="other"?<label className="sm:col-span-2"><span className="label">Role / Position</span><input className="field" value={form.role} onChange={e=>setForm({...form,role:e.target.value})} placeholder="ICT / Maintenance / Librarian"/></label>:null}
     <label><span className="label">Designation</span><input className="field" value={form.designation} onChange={e=>setForm({...form,designation:e.target.value})}/></label><label><span className="label">Department</span><select className="field" value={form.department} onChange={e=>setForm({...form,department:e.target.value})}><option value="">Select</option>{["Administration","Academic","Accounts","Examination","Library","ICT","Maintenance","Store","Other"].map(x=><option key={x}>{x}</option>)}</select></label><label><span className="label">Email</span><input className="field" type="email" value={form.email} onChange={e=>setForm({...form,email:e.target.value})}/></label><label><span className="label">Phone</span><input className="field" value={form.phone} onChange={e=>setForm({...form,phone:e.target.value})}/></label><label><span className="label">WhatsApp</span><input className="field" value={form.whatsapp} onChange={e=>setForm({...form,whatsapp:e.target.value})}/></label><label><span className="label">NID</span><input className="field" value={form.nid} onChange={e=>setForm({...form,nid:e.target.value})}/></label><label><span className="label">Joining Date</span><input className="field" type="date" value={form.joining_date} onChange={e=>setForm({...form,joining_date:e.target.value})}/></label><label><span className="label">Photo URL</span><input className="field" value={form.photo_url} onChange={e=>setForm({...form,photo_url:e.target.value})}/></label><label className="sm:col-span-2"><span className="label">Address</span><textarea className="field min-h-20 py-3" value={form.address} onChange={e=>setForm({...form,address:e.target.value})}/></label><label className="sm:col-span-2"><span className="label">Other Details (optional JSON)</span><textarea className="field min-h-24 py-3 font-mono text-xs" value={form.details} onChange={e=>setForm({...form,details:e.target.value})} placeholder='{"education":"B.Sc","experience":"5 years"}'/></label></div>
    <button disabled={saving} className="mt-5 w-full rounded-xl px-5 py-3 text-sm font-bold theme-primary-bg disabled:opacity-60">{saving?"Saving...":form.id?"Update Member":"Create Member & Generate ID"}</button>
   </form>
   <section className="rounded-3xl border border-[var(--school-border)] bg-[var(--school-surface)] p-5 shadow-sm md:p-7"><div className="flex flex-col gap-3 sm:flex-row sm:items-end sm:justify-between"><div><h2 className="text-xl font-black capitalize">{type} Members</h2><p className="mt-1 text-sm text-[var(--school-muted)]">Admin-only. Password remains hidden from public users.</p></div><div className="flex gap-2"><input className="field min-w-0 sm:w-64" value={search} onChange={e=>setSearch(e.target.value)} placeholder="Search ID / name"/><button onClick={()=>void load()} className="rounded-xl px-4 py-2 text-sm font-bold theme-primary-bg">Search</button></div></div><div className="mt-5 space-y-3">{loading?<p className="p-6 text-center text-sm text-[var(--school-muted)]">Loading...</p>:visible.map(m=><article key={m.id} className="rounded-2xl border border-[var(--school-border)] p-4"><div className="flex flex-col gap-3 lg:flex-row lg:items-center lg:justify-between"><div><p className="text-xs font-black theme-primary">{m.member_id}</p><h3 className="mt-1 font-black">{m.full_name}</h3><p className="text-xs text-[var(--school-muted)]">{m.role}{m.designation?` • ${m.designation}`:""}{m.department?` • ${m.department}`:""}{m.subject?` • ${m.subject}`:""}</p><p className="mt-2 text-xs">Password: <b>{m.password_text}</b></p></div><div className="flex gap-2"><button onClick={()=>edit(m)} className="rounded-xl border border-[var(--school-border)] px-3 py-2 text-xs font-bold">Edit</button><button onClick={()=>void remove(m)} className="rounded-xl border border-red-200 px-3 py-2 text-xs font-bold text-red-600">Remove</button></div></div></article>)}{!loading&&!visible.length?<p className="rounded-2xl border border-dashed border-[var(--school-border)] p-8 text-center text-sm text-[var(--school-muted)]">No members found.</p>:null}</div></section>
  </div>
 </AdminPageShell>;
}
