"use client";
import { FormEvent, useEffect, useMemo, useState } from "react";
import { createClient } from "@/lib/supabase/client";
import { AdminPageShell } from "@/components/admin/AdminPageShell";
type MemberType="teacher"|"staff"|"accounts"|"other";
type Member={id:string;member_id:string;member_type:MemberType;full_name:string;password:string;designation?:string|null;department?:string|null;subject?:string|null;qualification?:string|null;role_name?:string|null;role_title?:string|null;phone?:string|null;email?:string|null;address?:string|null;short_bio?:string|null;details?:string|null;is_active:boolean};
type FormState={id:string|null;member_type:MemberType;full_name:string;password:string;designation:string;department:string;subject:string;qualification:string;role_name:string;role_title:string;phone:string;email:string;address:string;short_bio:string;details:string};
const emptyForm:FormState={id:null,member_type:"staff",full_name:"",password:"",designation:"",department:"",subject:"",qualification:"",role_name:"",role_title:"",phone:"",email:"",address:"",short_bio:"",details:""};
const labels={teacher:"Teacher",staff:"Staff",accounts:"Accounts",other:"Other"};
function generatePassword(){const chars="ABCDEFGHJKLMNPQRSTUVWXYZabcdefghijkmnopqrstuvwxyz23456789@#";return Array.from({length:10},()=>chars[Math.floor(Math.random()*chars.length)]).join("");}
export default function MembersPage(){
 const supabase=useMemo(()=>createClient(),[]);const[type,setType]=useState<MemberType>("staff");const[members,setMembers]=useState<Member[]>([]);const[form,setForm]=useState<FormState>(emptyForm);const[search,setSearch]=useState("");const[loading,setLoading]=useState(true);const[saving,setSaving]=useState(false);const[message,setMessage]=useState("");
 async function loadMembers(){setLoading(true);const{data,error}=type==="other"?await supabase.rpc("school_admin_list_other_members"):await supabase.rpc("school_admin_list_members",{p_member_type:type});if(error)setMessage(error.message);else setMembers((data??[])as Member[]);setLoading(false);}
 useEffect(()=>{void loadMembers();},[type]);
 function update(name:keyof FormState,value:string){setForm(x=>({...x,[name]:value}));}function reset(){setForm({...emptyForm,member_type:type});}
 async function save(e:FormEvent){e.preventDefault();setSaving(true);setMessage("");let result;
  if(type==="other"){result=form.id?await supabase.rpc("school_admin_update_other_member",{p_id:form.id,p_full_name:form.full_name,p_password:form.password||null,p_role_title:form.role_title,p_department:form.department,p_phone:form.phone,p_email:form.email,p_details:form.details}):await supabase.rpc("school_admin_add_other_member",{p_full_name:form.full_name,p_password:form.password,p_role_title:form.role_title,p_department:form.department,p_phone:form.phone,p_email:form.email,p_details:form.details});}
  else{const args={p_member_type:type,p_full_name:form.full_name,p_password:form.password,p_designation:form.designation||null,p_department:form.department||null,p_subject:form.subject||null,p_role_name:form.role_name||null,p_qualification:form.qualification||null,p_joining_date:null,p_email:form.email||null,p_phone:form.phone||null,p_whatsapp:form.phone||null,p_address:form.address||null,p_short_bio:form.short_bio||null,p_photo_url:null};result=form.id?await supabase.rpc("school_admin_update_member",{...args,p_id:form.id}):await supabase.rpc("school_admin_add_member_v2",args);}
  if(result.error)setMessage(result.error.message);else{setMessage(form.id?"Member updated successfully.":`Member created: ${(result.data as{login_id?:string})?.login_id||"success"}`);reset();await loadMembers();}setSaving(false);
 }
 function edit(m:Member){setForm({id:m.id,member_type:type,full_name:m.full_name,password:"",designation:m.designation||"",department:m.department||"",subject:m.subject||"",qualification:m.qualification||"",role_name:m.role_name||"",role_title:m.role_title||"",phone:m.phone||"",email:m.email||"",address:m.address||"",short_bio:m.short_bio||"",details:m.details||""});window.scrollTo({top:0,behavior:"smooth"});}
 async function remove(m:Member){if(!window.confirm(`Remove ${m.full_name} (${m.member_id})?`))return;const{error}=m.member_type==="other"?await supabase.rpc("school_admin_deactivate_other_member",{p_id:m.id}):await supabase.rpc("school_admin_deactivate_member",{p_member_type:m.member_type,p_id:m.id});if(error)setMessage(error.message);else{setMessage(`${m.member_id} removed.`);await loadMembers();}}
 const visible=members.filter(m=>{const q=search.trim().toLowerCase();return!q||[m.member_id,m.full_name,m.designation,m.department,m.role_name,m.role_title,m.email,m.phone].some(v=>v?.toLowerCase().includes(q));});
 return <AdminPageShell eyebrow="School Members" title="Teachers, Staff, Accounts & Others" description="Admin-created members only. Parents, Students and Management Committee are intentionally excluded because they use their own registration/profile flow.">
  <div className="mb-6 flex flex-wrap gap-2">{(Object.keys(labels)as MemberType[]).map(k=><button key={k} onClick={()=>{setType(k);setForm({...emptyForm,member_type:k});}} className={`rounded-xl px-4 py-2 text-sm font-bold ${type===k?"theme-primary-bg":"border border-[var(--school-border)] bg-[var(--school-surface)]"}`}>{labels[k]}</button>)}</div>
  <div className="grid gap-6 xl:grid-cols-[minmax(360px,.8fr)_minmax(0,1.2fr)]">
   <form onSubmit={save} className="rounded-3xl border border-[var(--school-border)] bg-[var(--school-surface)] p-5 shadow-sm md:p-7">
    <div className="flex items-start justify-between"><div><p className="text-xs font-bold uppercase tracking-[0.16em] theme-primary">Admin Add / Edit</p><h2 className="mt-1 text-xl font-black">{form.id?`Edit ${labels[type]}`:`Add ${labels[type]}`}</h2><p className="mt-1 text-sm text-[var(--school-muted)]">One profile = one database row. ID is generated automatically.</p></div>{form.id?<button type="button" onClick={reset} className="rounded-xl border border-[var(--school-border)] px-3 py-2 text-xs font-bold">Cancel</button>:null}</div>
    <div className="mt-6 grid gap-4 sm:grid-cols-2">
     <label className="sm:col-span-2"><span className="label">Full Name *</span><input className="field" value={form.full_name} onChange={e=>update("full_name",e.target.value)} required /></label>
     {type==="teacher"&&<><label><span className="label">Designation</span><select className="field" value={form.designation} onChange={e=>update("designation",e.target.value)}><option value="">Select designation</option>{["Head Teacher","Assistant Head Teacher","Senior Teacher","Assistant Teacher","Subject Teacher","Lecturer","Other"].map(x=><option key={x}>{x}</option>)}</select></label><label><span className="label">Subject</span><input className="field" value={form.subject} onChange={e=>update("subject",e.target.value)}/></label><label><span className="label">Department</span><select className="field" value={form.department} onChange={e=>update("department",e.target.value)}><option value="">Select department</option>{["Academic","Examination","ICT","Library","Administration","Other"].map(x=><option key={x}>{x}</option>)}</select></label><label><span className="label">Qualification</span><input className="field" value={form.qualification} onChange={e=>update("qualification",e.target.value)}/></label></>}
     {type==="staff"&&<><label><span className="label">Designation *</span><select className="field" value={form.designation} onChange={e=>update("designation",e.target.value)} required><option value="">Select designation</option>{["Office Assistant","Peon","Guard","Librarian","Lab Assistant","Computer Operator","Cleaner","Maintenance","Other"].map(x=><option key={x}>{x}</option>)}</select></label><label><span className="label">Department</span><select className="field" value={form.department} onChange={e=>update("department",e.target.value)}><option value="">Select department</option>{["Administration","Academic","Library","ICT","Maintenance","Store","Other"].map(x=><option key={x}>{x}</option>)}</select></label></>}
     {type==="accounts"&&<><label><span className="label">Accounts Role *</span><select className="field" value={form.role_name} onChange={e=>update("role_name",e.target.value)} required><option value="">Select role</option>{["Accounts Manager","Accounts Officer","Accountant","Cashier","Billing Officer","Finance Officer","Other Accounts"].map(x=><option key={x}>{x}</option>)}</select></label><label><span className="label">Department</span><input className="field bg-[var(--school-background)]" value="Accounts" readOnly/></label><label><span className="label">Qualification</span><input className="field" value={form.qualification} onChange={e=>update("qualification",e.target.value)}/></label></>}
     {type==="other"&&<><label><span className="label">Role / Position *</span><input className="field" value={form.role_title} onChange={e=>update("role_title",e.target.value)} required placeholder="ICT / Maintenance / Librarian"/></label><label><span className="label">Department</span><input className="field" value={form.department} onChange={e=>update("department",e.target.value)}/></label><label className="sm:col-span-2"><span className="label">Details</span><textarea className="field min-h-24 py-3" value={form.details} onChange={e=>update("details",e.target.value)}/></label></>}
     <div className="sm:col-span-2 grid gap-4 sm:grid-cols-[1fr_auto] sm:items-end"><label><span className="label">Password {form.id?"(leave blank to keep current)":"*"}</span><input className="field" value={form.password} onChange={e=>update("password",e.target.value)} required={!form.id}/></label><button type="button" onClick={()=>update("password",generatePassword())} className="rounded-xl border border-[var(--school-border)] px-4 py-3 text-sm font-bold">Generate</button></div>
     <label><span className="label">Phone</span><input className="field" value={form.phone} onChange={e=>update("phone",e.target.value)}/></label><label><span className="label">Email</span><input className="field" type="email" value={form.email} onChange={e=>update("email",e.target.value)}/></label>
     {type!=="other"&&<label className="sm:col-span-2"><span className="label">Address</span><input className="field" value={form.address} onChange={e=>update("address",e.target.value)}/></label>}
    </div>
    {message?<p className="mt-4 rounded-xl bg-[var(--school-primary-soft)] px-4 py-3 text-sm font-semibold theme-primary">{message}</p>:null}<button disabled={saving} className="mt-5 w-full rounded-xl px-5 py-3 text-sm font-bold theme-primary-bg disabled:opacity-60">{saving?"Saving...":form.id?"Update Member":`Create ${labels[type]} ID`}</button>
   </form>
   <section className="rounded-3xl border border-[var(--school-border)] bg-[var(--school-surface)] p-5 shadow-sm md:p-7">
    <div className="flex flex-col gap-3 sm:flex-row sm:items-end sm:justify-between"><div><p className="text-xs font-bold uppercase tracking-[0.16em] theme-primary">{labels[type]} Table</p><h2 className="mt-1 text-xl font-black">All {labels[type]} Profiles</h2><p className="mt-1 text-sm text-[var(--school-muted)]">Each member is stored as one complete profile row.</p></div><input className="field sm:max-w-xs" value={search} onChange={e=>setSearch(e.target.value)} placeholder="Search ID / name..."/></div>
    <div className="mt-5 space-y-3">{loading?<p className="p-6 text-center text-sm text-[var(--school-muted)]">Loading...</p>:null}{visible.map(m=><article key={m.id} className="rounded-2xl border border-[var(--school-border)] p-4"><div className="flex flex-col gap-3 lg:flex-row lg:items-center lg:justify-between"><div><p className="text-xs font-black theme-primary">{m.member_id}</p><h3 className="mt-1 font-black">{m.full_name}</h3><p className="text-xs text-[var(--school-muted)]">{m.designation||m.role_name||m.role_title||""}{m.department?` • ${m.department}`:""}{m.subject?` • ${m.subject}`:""}</p></div><div className="flex flex-wrap items-center gap-2"><span className="rounded-xl border border-[var(--school-border)] bg-[var(--school-background)] px-3 py-2 font-mono text-xs">Pass: {m.password}</span><button onClick={()=>edit(m)} className="rounded-xl border border-[var(--school-border)] px-3 py-2 text-xs font-bold">Edit</button><button onClick={()=>void remove(m)} className="rounded-xl border border-red-200 px-3 py-2 text-xs font-bold text-red-600">Remove</button></div></div></article>)}{!loading&&!visible.length?<p className="rounded-2xl border border-dashed border-[var(--school-border)] p-8 text-center text-sm text-[var(--school-muted)]">No members found.</p>:null}</div>
   </section>
  </div>
 </AdminPageShell>;
}
