"use client";

import { useState } from "react";
import { createClient } from "@/lib/supabase/client";

type Item={id:string;item_code:string;item_name:string;item_type:string|null;specification:string|null;model:string|null;unit:string;current_stock:number;stock_status:string};
type Selected=Item&{quantity:number;note:string};
const status=(v:string)=>v.toLowerCase().includes("out")?"text-red-700 bg-red-50 border-red-100":v.toLowerCase().includes("low")?"text-amber-700 bg-amber-50 border-amber-100":"theme-primary bg-[var(--school-primary-soft)] border-[var(--school-primary-border)]";

export default function AdminItemSrForm(){
 const db=createClient();
 const [q,setQ]=useState(""); const [items,setItems]=useState<Item[]>([]); const [selected,setSelected]=useState<Selected[]>([]);
 const [open,setOpen]=useState(false); const [className,setClassName]=useState(""); const [department,setDepartment]=useState(""); const [details,setDetails]=useState("");
 const [busy,setBusy]=useState(false); const [error,setError]=useState(""); const [success,setSuccess]=useState("");
 const totalQty=selected.reduce((s,x)=>s+Number(x.quantity),0);
 async function search(){setError("");setSuccess("");const raw=q.trim();if(!raw){setError("Enter item code or item name.");return;}const {data,error:e}=await db.rpc("admin_list_sr_items",{p_search:raw});if(e){setError(e.message);return;}setItems((data??[]) as Item[]);if(!(data??[]).length)setError(`No active item found for “${raw}”.`);}
 function add(item:Item){if(Number(item.current_stock)<=0){setError(`${item.item_code} is out of stock.`);return;}if(selected.some(x=>x.id===item.id))return;setSelected(v=>[...v,{...item,quantity:1,note:""}]);setItems(v=>v.filter(x=>x.id!==item.id));setError("");}
 function update(id:string,field:"quantity"|"note",value:string){setSelected(v=>v.map(x=>x.id===id?{...x,[field]:field==="quantity"?Math.max(1,Math.min(Number(x.current_stock),Number(value)||1)):value}:x));}
 async function submit(){setError("");setSuccess("");if(!selected.length){setError("Select at least one item.");return;}if(!className.trim()){setError("Class / Section is required.");return;}if(!details.trim()){setError("Request Details is required.");return;}setBusy(true);const snapshot=[...selected];const {data,error:e}=await db.rpc("admin_submit_sr",{p_class_name:className.trim(),p_department:department.trim(),p_request_details:details.trim(),p_items:snapshot.map(x=>({item_id:x.id,quantity:x.quantity,note:x.note.trim()}))});setBusy(false);if(e){setError(e.message);return;}setSuccess(`SR ${data?.sr_number??""} submitted successfully. Status: Pending Approval.`);setSelected([]);setItems([]);setQ("");setClassName("");setDepartment("");setDetails("");setOpen(false);}
 return <div className="space-y-4">
  <section className="rounded-2xl border border-[var(--school-border)] bg-[var(--school-primary-soft)] p-4">
   <div className="flex flex-col gap-2 sm:flex-row"><div className="flex min-w-0 flex-1 overflow-hidden rounded-xl border border-[var(--school-border)] bg-[var(--school-surface)]"><span className="flex items-center border-r border-[var(--school-border)] px-3 text-[10px] font-black theme-primary">ITM-</span><input value={q} onChange={e=>setQ(e.target.value)} onKeyDown={e=>{if(e.key==='Enter')void search()}} placeholder="Search by item code or name..." className="h-10 min-w-0 flex-1 bg-transparent px-3 text-xs outline-none"/><button type="button" onClick={()=>void search()} disabled={busy} className="px-4 text-[10px] font-black theme-primary-bg disabled:opacity-60">Search</button></div><button type="button" onClick={()=>setOpen(true)} className="rounded-xl border border-[var(--school-primary-border)] bg-[var(--school-surface)] px-5 py-2.5 text-[10px] font-black theme-primary">Open SR Form</button></div>
   <p className="mt-2 text-[10px] text-[var(--school-muted)]">Search supports ITM-code, numeric code, item name, type and specification.</p>
   {items.length>0&&<div className="mt-3 max-h-64 space-y-1.5 overflow-y-auto">{items.map(item=><button key={item.id} type="button" onClick={()=>add(item)} className="w-full rounded-xl border border-[var(--school-border)] bg-[var(--school-surface)] p-3 text-left hover:border-[var(--school-primary-border)]"><div className="flex flex-wrap items-center gap-2"><b className="text-[10px] theme-primary">{item.item_code}</b><span className="min-w-0 flex-1 truncate text-xs font-semibold">{item.item_name}</span><span className="text-[10px] text-[var(--school-muted)]">{item.specification||item.item_type||"Item"}</span><span className={`rounded-full border px-2 py-0.5 text-[9px] font-bold ${status(item.stock_status)}`}>{item.stock_status} · {item.current_stock} {item.unit}</span></div></button>)}</div>}
  </section>
  {error&&<div className="rounded-xl border border-red-200 bg-red-50 px-4 py-3 text-xs font-semibold text-red-700">{error}</div>}
  {success&&<div className="rounded-xl border border-[var(--school-primary-border)] bg-[var(--school-primary-soft)] px-4 py-3 text-xs font-bold theme-primary">{success}</div>}
  {selected.length>0&&<section className="rounded-2xl border border-[var(--school-border)] bg-[var(--school-surface)] p-4"><div className="flex items-center justify-between"><div><h3 className="text-sm font-black">Selected Items</h3><p className="text-[10px] text-[var(--school-muted)]">{selected.length} item(s) · Total Qty {totalQty}</p></div><button type="button" onClick={()=>setOpen(true)} className="rounded-lg px-3 py-2 text-[10px] font-black theme-primary-bg">Open Full SR Form →</button></div></section>}
  {open&&<div className="fixed inset-0 z-[100] flex items-center justify-center bg-black/45 p-3 sm:p-5" role="dialog" aria-modal="true"><div className="flex max-h-[92vh] w-full max-w-4xl flex-col overflow-hidden rounded-3xl border border-[var(--school-border)] bg-[var(--school-surface)] shadow-2xl"><header className="flex items-center justify-between border-b border-[var(--school-border)] px-5 py-4 sm:px-6"><div><p className="text-[10px] font-black uppercase tracking-[.16em] theme-primary">Item Service Request</p><h2 className="mt-1 text-xl font-black">Full SR Form</h2><p className="mt-1 text-[10px] text-[var(--school-muted)]">Select items, set quantity, enter request information and submit for approval.</p></div><button type="button" onClick={()=>setOpen(false)} className="rounded-xl border border-[var(--school-border)] px-3 py-2 text-sm font-bold">×</button></header>
   <div className="overflow-y-auto p-5 sm:p-6"><div className="grid gap-3 sm:grid-cols-2"><label><span className="mb-1 block text-[10px] font-bold">Class / Section *</span><input value={className} onChange={e=>setClassName(e.target.value)} placeholder="Class 6-A" className="field h-10 w-full text-xs"/></label><label><span className="mb-1 block text-[10px] font-bold">Department</span><input value={department} onChange={e=>setDepartment(e.target.value)} placeholder="Department" className="field h-10 w-full text-xs"/></label></div><label className="mt-3 block"><span className="mb-1 block text-[10px] font-bold">Request Details *</span><textarea value={details} onChange={e=>setDetails(e.target.value)} rows={4} placeholder="What is the item needed for?" className="field w-full resize-none text-xs"/></label>
    <div className="mt-5 rounded-2xl border border-[var(--school-border)]"><div className="flex items-center justify-between border-b border-[var(--school-border)] bg-[var(--school-primary-soft)] px-4 py-3"><div><h3 className="text-sm font-black">Requested Items</h3><p className="text-[10px] text-[var(--school-muted)]">Item code, quantity and optional note</p></div><span className="rounded-full bg-[var(--school-surface)] px-3 py-1 text-[9px] font-black theme-primary">{selected.length} · Qty {totalQty}</span></div>{selected.length===0?<div className="p-8 text-center text-xs text-[var(--school-muted)]">No items selected. Close this form and select items from the search results.</div>:<div className="divide-y divide-[var(--school-border)]">{selected.map(item=><div key={item.id} className="grid gap-3 p-4 sm:grid-cols-[minmax(0,1.5fr)_100px_minmax(150px,1fr)_auto] sm:items-center"><div className="min-w-0"><b className="text-[10px] theme-primary">{item.item_code}</b><p className="truncate text-xs font-semibold">{item.item_name}</p><p className="text-[9px] text-[var(--school-muted)]">Stock {item.current_stock} {item.unit}</p></div><input type="number" min="1" max={Number(item.current_stock)} value={item.quantity} onChange={e=>update(item.id,"quantity",e.target.value)} className="field h-9 w-full text-xs"/><input value={item.note} onChange={e=>update(item.id,"note",e.target.value)} placeholder="Optional note" className="field h-9 w-full text-xs"/><button type="button" onClick={()=>setSelected(v=>v.filter(x=>x.id!==item.id))} className="rounded-lg border border-red-200 px-3 py-2 text-[10px] font-bold text-red-700">Remove</button></div>)}</div>}</div>
   </div><footer className="flex flex-col-reverse gap-2 border-t border-[var(--school-border)] bg-[var(--school-primary-soft)] px-5 py-4 sm:flex-row sm:items-center sm:justify-between sm:px-6"><span className="text-xs font-bold theme-primary">{selected.length} item(s) · Total Qty {totalQty}</span><div className="flex gap-2"><button type="button" onClick={()=>setOpen(false)} className="rounded-xl border border-[var(--school-border)] px-4 py-2.5 text-xs font-bold">Cancel</button><button type="button" onClick={()=>void submit()} disabled={busy||!selected.length} className="rounded-xl px-5 py-2.5 text-xs font-black theme-primary-bg disabled:opacity-50">{busy?"Submitting...":"Submit for Approval →"}</button></div></footer>
  </div></div>}
 </div>;
}
