"use client";

import { useCallback, useEffect, useMemo, useState } from "react";
import { createClient } from "@/lib/supabase/client";
import AccountsEntryForm from "./accounts-entry-form";

type Entry={id:string;voucher_no:string;entry_date:string;entry_type:string;category:string|null;party_type:string|null;party_id:string|null;party_name:string|null;amount:number;total_amount:number;paid_amount:number;due_amount:number;due_date:string|null;payment_status:string;payment_method:string;account_name:string|null;reference_no:string|null;description:string|null;status:string;created_at:string};
type Summary={income:number;expense:number;net:number;cash:number;bank:number;receivable:number;payable:number;transactions:number};
const money=(n:number)=>`৳ ${new Intl.NumberFormat("en-BD",{minimumFractionDigits:2,maximumFractionDigits:2}).format(Number(n)||0)}`;
const typeNames:Record<string,string>={student_fee:"Student Fee",salary:"Salary",other_payment:"Other Member Payment",income:"Income",expense:"Expense",vendor_payment:"Vendor Payment",school_bill:"School Bill",cash_in:"Cash In",cash_out:"Cash Out",bank_in:"Bank Deposit",bank_out:"Bank Withdrawal",bank_transfer:"Bank Transfer",journal:"Journal"};
const sections=[
 ["dashboard","Dashboard","Overview, balances and alerts"],["transactions","Transactions","All posted financial entries"],["receivable","Receivable / Payable","Student dues, salary and vendor balances"],["cashbook","Cashbook","Cash in, cash out and running history"],["bankbook","Bankbook","Bank deposits, withdrawals and transfers"],["reports","Reports","Collection, expense and financial reports"],["audit","Audit / History","Voucher history and reversals"],["heads","Account Heads","Chart of accounts and categories"]
] as const;

export default function AccountsWorkspaceV2(){
 const supabase=useMemo(()=>createClient(),[]);const token=typeof window!=="undefined"?localStorage.getItem("ctms_store_token"):null;const [active,setActive]=useState("dashboard");const [summary,setSummary]=useState<Summary|null>(null);const [entries,setEntries]=useState<Entry[]>([]);const [loading,setLoading]=useState(true);const [error,setError]=useState("");const [query,setQuery]=useState("");const [type,setType]=useState("all");const [status,setStatus]=useState("all");const [heads,setHeads]=useState<any[]>([]);
 const load=useCallback(async()=>{if(!token)return;setLoading(true);setError("");const [s,e,h]=await Promise.all([supabase.rpc("store_accounts_summary",{p_token:token}),supabase.rpc("store_accounts_list_entries",{p_token:token,p_type:type==="all"?"":type,p_search:query}),supabase.from("accounts_account_heads").select("id,head_type,head_name,is_active,display_order").eq("is_active",true).order("display_order").order("head_name")]);if(s.error||e.error){setError(s.error?.message||e.error?.message||"Unable to load Accounts data")}else{setSummary((s.data||null) as Summary);setEntries((e.data||[]) as Entry[])}if(!h.error)setHeads(h.data||[]);setLoading(false)},[supabase,token,type,query]);
 useEffect(()=>{load()},[load]);
 const filtered=useMemo(()=>entries.filter(e=>status==="all"||e.payment_status===status||e.status===status),[entries,status]);
 const receivable=useMemo(()=>filtered.filter(e=>e.due_amount>0&&["student_fee","income"].includes(e.entry_type)),[filtered]);
 const payable=useMemo(()=>filtered.filter(e=>e.due_amount>0&&["salary","vendor_payment","school_bill","other_payment"].includes(e.entry_type)),[filtered]);
 const cash=useMemo(()=>filtered.filter(e=>["cash_in","cash_out"].includes(e.entry_type)||e.payment_method==="cash"),[filtered]);
 const bank=useMemo(()=>filtered.filter(e=>["bank_in","bank_out","bank_transfer"].includes(e.entry_type)||e.payment_method==="bank"),[filtered]);
 const byCategory=useMemo(()=>{const m=new Map<string,number>();for(const e of filtered){const k=e.category||typeNames[e.entry_type]||e.entry_type;m.set(k,(m.get(k)||0)+Number(e.amount||0))}return [...m.entries()].sort((a,b)=>b[1]-a[1]).slice(0,12)},[filtered]);
 const card=(label:string,value:string,sub?:string)=><div className="rounded-2xl border border-[var(--school-border)] bg-[var(--school-surface)] p-4"><p className="text-[10px] font-bold uppercase tracking-wider text-[var(--school-muted)]">{label}</p><p className="mt-1 text-xl font-black">{value}</p>{sub&&<p className="mt-1 text-[10px] text-[var(--school-muted)]">{sub}</p>}</div>;
 const table=(rows:Entry[])=>rows.length===0?<div className="rounded-2xl border border-dashed border-[var(--school-border)] p-8 text-center text-xs text-[var(--school-muted)]">No transaction found.</div>:<div className="overflow-x-auto rounded-2xl border border-[var(--school-border)]"><table className="w-full min-w-[1050px] text-left text-xs"><thead className="bg-[var(--school-primary-soft)]"><tr>{["Date","Voucher","Type","Party","Category","Total","Paid","Due","Method","Status"].map(x=><th key={x} className="p-3 text-[10px] font-black uppercase tracking-wider text-[var(--school-muted)]">{x}</th>)}</tr></thead><tbody>{rows.map(e=><tr key={e.id} className="border-t border-[var(--school-border)]"><td className="p-3">{e.entry_date}</td><td className="p-3 font-black">{e.voucher_no}</td><td className="p-3">{typeNames[e.entry_type]||e.entry_type}</td><td className="p-3">{e.party_id||e.party_name||"-"}</td><td className="p-3">{e.category||"-"}</td><td className="p-3">{money(e.total_amount)}</td><td className="p-3 theme-primary">{money(e.paid_amount)}</td><td className="p-3 font-bold text-amber-700">{money(e.due_amount)}</td><td className="p-3">{e.payment_method}</td><td className="p-3 font-black uppercase">{e.payment_status||e.status}</td></tr>)}</tbody></table></div>;
 if(!token)return <div className="rounded-2xl border border-amber-200 bg-amber-50 p-5 text-sm text-amber-800">Accounts session not found. Please sign in again.</div>;
 return <div className="mt-5 overflow-hidden rounded-3xl border border-[var(--school-border)] bg-[var(--school-surface)] shadow-sm"><div className="grid lg:grid-cols-[255px_minmax(0,1fr)]"><aside className="border-b border-[var(--school-border)] bg-[var(--school-primary-soft)] lg:border-b-0 lg:border-r"><div className="p-4"><p className="text-[10px] font-black uppercase tracking-[.16em] theme-primary">Owner Accounts</p><h3 className="mt-1 text-base font-black">Finance Control Center</h3><div className="mt-3"><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search voucher, party, category..." className="w-full rounded-xl border border-[var(--school-border)] bg-[var(--school-surface)] px-3 py-2.5 text-xs outline-none"/></div></div><nav className="max-h-[calc(100vh-245px)] overflow-y-auto px-2 pb-3">{sections.map(([k,t,d])=><button key={k} type="button" onClick={()=>setActive(k)} className={`mb-1 w-full rounded-xl px-3 py-3 text-left ${active===k?"theme-primary-bg":"hover:bg-[var(--school-surface)]"}`}><div className="text-xs font-black">{t}</div><div className="mt-0.5 text-[9px] opacity-70">{d}</div></button>)}</nav></aside><main className="min-w-0 p-4 sm:p-6"><div className="flex flex-col gap-3 border-b border-[var(--school-border)] pb-5 sm:flex-row sm:items-start sm:justify-between"><div><p className="text-[10px] font-black uppercase tracking-[.16em] theme-primary">Accounts</p><h2 className="mt-1 text-xl font-black">{sections.find(s=>s[0]===active)?.[1]}</h2><p className="mt-1 text-xs text-[var(--school-muted)]">{sections.find(s=>s[0]===active)?.[2]}</p></div><AccountsEntryForm onSaved={load}/></div>{error&&<div className="mt-4 rounded-xl border border-red-200 bg-red-50 p-3 text-xs font-semibold text-red-700">{error}</div>}{loading?<div className="py-12 text-center text-xs text-[var(--school-muted)]">Loading Accounts...</div>:<>
 {active==="dashboard"&&<div className="mt-5 space-y-5"><div className="grid gap-3 sm:grid-cols-2 xl:grid-cols-4">{card("Total Income",money(summary?.income||0),"Posted school income and collections")}{card("Total Expense",money(summary?.expense||0),"Posted operational and payable payments")}{card("Net Position",money(summary?.net||0),"Income minus expense")}{card("Transactions",String(summary?.transactions||0),"Posted financial entries")}</div><div className="grid gap-3 sm:grid-cols-2 xl:grid-cols-4">{card("Cash Balance",money(summary?.cash||0))}{card("Bank Balance",money(summary?.bank||0))}{card("Receivable",money(summary?.receivable||0),"Student / income dues")}{card("Payable",money(summary?.payable||0),"Salary / vendor / bill dues")}</div><div className="grid gap-5 lg:grid-cols-[1.3fr_.7fr]"><div className="rounded-2xl border border-[var(--school-border)] p-4"><div className="flex items-center justify-between"><h3 className="text-sm font-black">Recent Transactions</h3><button onClick={()=>setActive("transactions")} className="text-[10px] font-black theme-primary">View all</button></div><div className="mt-3">{table(filtered.slice(0,8))}</div></div><div className="rounded-2xl border border-[var(--school-border)] p-4"><h3 className="text-sm font-black">Top Categories</h3><div className="mt-3 space-y-2">{byCategory.length?byCategory.map(([k,v])=><div key={k} className="flex items-center justify-between rounded-xl bg-[var(--school-primary-soft)] px-3 py-2 text-xs"><span>{k}</span><b>{money(v)}</b></div>):<p className="text-xs text-[var(--school-muted)]">No posted categories yet.</p>}</div></div></div></div>}
 {active==="transactions"&&<div className="mt-5"><div className="mb-4 flex flex-wrap gap-2"><select value={type} onChange={e=>setType(e.target.value)} className="rounded-xl border border-[var(--school-border)] px-3 py-2 text-xs"><option value="all">All Types</option>{Object.entries(typeNames).map(([k,v])=><option key={k} value={k}>{v}</option>)}</select><select value={status} onChange={e=>setStatus(e.target.value)} className="rounded-xl border border-[var(--school-border)] px-3 py-2 text-xs"><option value="all">All Status</option><option value="paid">Paid</option><option value="partial">Partial</option><option value="due">Due</option><option value="posted">Posted</option></select><button onClick={load} className="rounded-xl border border-[var(--school-border)] px-3 py-2 text-xs font-bold">Refresh</button></div>{table(filtered)}</div>}
 {active==="receivable"&&<div className="mt-5 space-y-5"><div className="grid gap-3 sm:grid-cols-2">{card("Receivable",money(summary?.receivable||0),"Student and income dues")}{card("Payable",money(summary?.payable||0),"Salary, vendor and school bills")}</div><div><h3 className="mb-2 text-sm font-black">Receivable</h3>{table(receivable)}</div><div><h3 className="mb-2 text-sm font-black">Payable</h3>{table(payable)}</div></div>}
 {active==="cashbook"&&<div className="mt-5 space-y-4"><div className="grid gap-3 sm:grid-cols-3">{card("Cash Balance",money(summary?.cash||0))}{card("Cash In",money(cash.filter(e=>e.entry_type==="cash_in"||["income","student_fee"].includes(e.entry_type)).reduce((a,e)=>a+Number(e.amount||0),0)))}{card("Cash Out",money(cash.filter(e=>e.entry_type==="cash_out"||["expense","salary","vendor_payment","school_bill","other_payment"].includes(e.entry_type)).reduce((a,e)=>a+Number(e.amount||0),0)))}</div>{table(cash)}</div>}
 {active==="bankbook"&&<div className="mt-5 space-y-4"><div className="grid gap-3 sm:grid-cols-3">{card("Bank Balance",money(summary?.bank||0))}{card("Bank In",money(bank.filter(e=>["bank_in","income","student_fee"].includes(e.entry_type)).reduce((a,e)=>a+Number(e.amount||0),0)))}{card("Bank Out",money(bank.filter(e=>["bank_out","expense","salary","vendor_payment","school_bill","other_payment"].includes(e.entry_type)).reduce((a,e)=>a+Number(e.amount||0),0)))}</div>{table(bank)}</div>}
 {active==="reports"&&<div className="mt-5 space-y-5"><div className="grid gap-3 sm:grid-cols-2 xl:grid-cols-4">{card("Collection",money(filtered.filter(e=>e.entry_type==="student_fee").reduce((a,e)=>a+Number(e.paid_amount||0),0)))}{card("Salary Paid",money(filtered.filter(e=>e.entry_type==="salary").reduce((a,e)=>a+Number(e.paid_amount||0),0)))}{card("Vendor Paid",money(filtered.filter(e=>e.entry_type==="vendor_payment").reduce((a,e)=>a+Number(e.paid_amount||0),0)))}{card("School Bills Paid",money(filtered.filter(e=>e.entry_type==="school_bill").reduce((a,e)=>a+Number(e.paid_amount||0),0)))}</div><div className="rounded-2xl border border-[var(--school-border)] p-4"><h3 className="text-sm font-black">Category Summary</h3><div className="mt-3 grid gap-2 sm:grid-cols-2">{byCategory.map(([k,v])=><div key={k} className="flex justify-between rounded-xl bg-[var(--school-primary-soft)] px-3 py-2 text-xs"><span>{k}</span><b>{money(v)}</b></div>)}</div></div>{table(filtered)}</div>}
 {active==="audit"&&<div className="mt-5 space-y-4"><div className="rounded-2xl border border-[var(--school-border)] bg-[var(--school-primary-soft)] p-4 text-xs leading-5"><b>Audit rule:</b> vouchers remain in history. Void/reversal must be treated as a controlled action, never by deleting the original transaction.</div>{table(filtered)}</div>}
 {active==="heads"&&<div className="mt-5"><div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-3">{heads.map(h=><div key={h.id} className="rounded-2xl border border-[var(--school-border)] p-4"><p className="text-[9px] font-black uppercase tracking-wider text-[var(--school-muted)]">{h.head_type}</p><p className="mt-1 text-sm font-black">{h.head_name}</p></div>)}</div>{heads.length===0&&<div className="rounded-2xl border border-dashed border-[var(--school-border)] p-8 text-center text-xs text-[var(--school-muted)]">No account heads configured yet.</div>}</div>}
 </>}</main></div></div>;
}
