"use client";

import { useCallback, useEffect, useMemo, useState } from "react";
import { createClient } from "@/lib/supabase/client";

type Overview={period_start:string;period_end:string;income:{student_collection:number;other_income:number;total:number};expense:{salary:number;bill_payment:number;other_expense:number;total:number};bills:{total_payable:number;paid:number;due:number;count:number;pending_approval:number};collection:{student_due:number;student_collected:number;other_collected:number;total_collected:number};cash_bank:{cash:number;bank:number}};
const money=(n:number)=>`৳ ${new Intl.NumberFormat("en-BD",{minimumFractionDigits:2,maximumFractionDigits:2}).format(Number(n)||0)}`;
const monthLabel=(v:string)=>new Date(`${v}-01T00:00:00`).toLocaleDateString("en-US",{month:"long",year:"numeric"});
const Card=({label,value,note,cls=""}:{label:string;value:string|number;note?:string;cls?:string})=><div className="rounded-2xl border border-[var(--school-border)] bg-[var(--school-surface)] p-4"><p className="text-[9px] font-black uppercase tracking-wider text-[var(--school-muted)]">{label}</p><p className={`mt-1 text-xl font-black ${cls}`}>{value}</p>{note&&<p className="mt-1 text-[10px] text-[var(--school-muted)]">{note}</p>}</div>;

export default function FinancialOverview(){
 const db=useMemo(()=>createClient(),[]);const [month,setMonth]=useState(new Date().toISOString().slice(0,7));const [data,setData]=useState<Overview|null>(null);const [loading,setLoading]=useState(true);const [error,setError]=useState("");
 const load=useCallback(async()=>{const token=typeof window!=="undefined"?localStorage.getItem("ctms_store_token"):null;if(!token){setError("Session not found. Please sign in again.");setLoading(false);return;}setLoading(true);setError("");const r=await db.rpc("store_accounts_financial_overview",{p_token:token,p_month:`${month}-01`});if(r.error)setError(r.error.message);else setData(r.data as Overview);setLoading(false)},[db,month]);
 useEffect(()=>{void load()},[load]);
 const balance=Number(data?.income.total||0)-Number(data?.expense.total||0);
 return <section className="rounded-3xl border border-[var(--school-border)] bg-[var(--school-surface)] shadow-sm">
  <header className="border-b border-[var(--school-border)] bg-[var(--school-primary-soft)] p-5 sm:p-6"><div className="flex flex-col gap-4 lg:flex-row lg:items-end lg:justify-between"><div><p className="text-[10px] font-black uppercase tracking-[.16em] theme-primary">Accounts • Committee & Admin View</p><h2 className="mt-1 text-xl font-black">Financial Overview</h2><p className="mt-1 max-w-3xl text-xs text-[var(--school-muted)]">One school-wide view of income, expenses, bills, collection and cash/bank movement. Existing Salary, Student Fees and Bill workflows remain separate and are only summarized here.</p></div><label className="text-[10px] font-bold text-[var(--school-muted)]">Period<input type="month" value={month} onChange={e=>setMonth(e.target.value)} className="mt-1 block rounded-xl border border-[var(--school-border)] bg-[var(--school-surface)] px-3 py-2.5 text-xs"/></label></div></header>
  {error&&<div className="mx-5 mt-5 rounded-xl border border-red-200 bg-red-50 p-3 text-xs font-semibold text-red-700 sm:mx-6">{error}</div>}
  {loading?<div className="p-10 text-center text-xs text-[var(--school-muted)]">Loading school financial overview...</div>:data&&<div className="p-5 sm:p-6">
   <div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-4"><Card label="Total Income" value={money(data.income.total)} note="Student collection + other income" cls="theme-primary"/><Card label="Total Expense" value={money(data.expense.total)} note="Salary + bills + other expense" cls="text-red-700"/><Card label="Net Movement" value={money(balance)} note="Income minus paid expense" cls={balance>=0?"theme-primary":"text-red-700"}/><Card label="Total Collection" value={money(data.collection.total_collected)} note="Collected during selected month" cls="theme-primary"/></div>
   <div className="mt-5 grid gap-4 lg:grid-cols-2"><div className="rounded-2xl border border-[var(--school-border)] p-4"><div className="flex items-center justify-between"><div><p className="text-[10px] font-black uppercase tracking-wider theme-primary">Income</p><h3 className="mt-1 text-base font-black">{monthLabel(month)}</h3></div><p className="text-lg font-black theme-primary">{money(data.income.total)}</p></div><div className="mt-4 space-y-3"><div className="flex justify-between text-xs"><span>Student Fees Collection</span><b>{money(data.income.student_collection)}</b></div><div className="flex justify-between text-xs"><span>Other Income</span><b>{money(data.income.other_income)}</b></div></div></div><div className="rounded-2xl border border-[var(--school-border)] p-4"><div className="flex items-center justify-between"><div><p className="text-[10px] font-black uppercase tracking-wider text-red-700">Expense</p><h3 className="mt-1 text-base font-black">{monthLabel(month)}</h3></div><p className="text-lg font-black text-red-700">{money(data.expense.total)}</p></div><div className="mt-4 space-y-3"><div className="flex justify-between text-xs"><span>Salary</span><b>{money(data.expense.salary)}</b></div><div className="flex justify-between text-xs"><span>Bill Payments</span><b>{money(data.expense.bill_payment)}</b></div><div className="flex justify-between text-xs"><span>Other Expense</span><b>{money(data.expense.other_expense)}</b></div></div></div></div>
   <div className="mt-5 grid gap-3 sm:grid-cols-2 lg:grid-cols-4"><Card label="Bills Payable" value={money(data.bills.total_payable)} note={`${data.bills.count} bill(s) this month`}/><Card label="Bills Paid" value={money(data.bills.paid)} note="Paid against school bills" cls="theme-primary"/><Card label="Bills Due" value={money(data.bills.due)} note="Current outstanding bills" cls="text-red-700"/><Card label="Pending Approval" value={data.bills.pending_approval} note="Bills waiting for approval" cls="text-orange-700"/></div>
   <div className="mt-5 grid gap-3 sm:grid-cols-2 lg:grid-cols-4"><Card label="Student Collection" value={money(data.collection.student_collected)} note="Selected month" cls="theme-primary"/><Card label="Student Outstanding" value={money(data.collection.student_due)} note="All current student balances" cls="text-red-700"/><Card label="Other Collection" value={money(data.collection.other_collected)} note="Non-student income" cls="theme-primary"/><Card label="Cash / Bank Movement" value={money(Number(data.cash_bank.cash)+Number(data.cash_bank.bank))} note={`Cash ${money(data.cash_bank.cash)} • Bank ${money(data.cash_bank.bank)}`}/></div>
   <div className="mt-5 rounded-2xl border border-dashed border-[var(--school-border)] bg-[var(--school-primary-soft)] p-4"><p className="text-[10px] font-black uppercase tracking-wider theme-primary">Single-page control view</p><p className="mt-1 text-xs leading-5 text-[var(--school-muted)]">This overview does not replace the existing Salary Sheet, Student Fees or Bill Payments modules. It reads their existing transactions and presents the school-wide financial picture here, so Admin and authorized Committee users can review the position without opening each workflow separately.</p></div>
  </div>}
 </section>;
}
