"use client";

import { FormEvent, useCallback, useEffect, useMemo, useState } from "react";
import { createClient } from "@/lib/supabase/client";

type Permissions = Record<string, boolean>;
type Student = { id:string; student_id:string; full_name:string; admission_class:string|null; section:string|null; academic_year:string|null; balance_due:number };
type Entry = { id:string; entry_date:string; academic_year:string; fee_type:string; entry_type:string; reference_no:string|null; amount:number; due_date:string|null; payment_method:string|null; notes:string|null; student_id:string; full_name:string; admission_class:string|null; section:string|null; current_balance:number };
type Summary = { total_charged:number; total_collected:number; total_discount:number; total_due:number; month_collected:number; today_collected:number; students_with_fees:number };

const feeTypes = [
  ["admission_fee","Admission Fee"],["tuition_fee","Tuition / Monthly Fee"],["session_fee","Session / Annual Fee"],["exam_fee","Examination Fee"],
  ["registration_fee","Registration Fee"],["re_admission_fee","Re-admission Fee"],["transport_fee","Transport Fee"],["library_fee","Library Fee"],
  ["lab_fee","Laboratory / Computer Fee"],["sports_fee","Sports Fee"],["id_card_fee","ID Card Fee"],["certificate_fee","Certificate / Document Fee"],
  ["uniform_fee","Uniform Fee"],["fine","Fine / Penalty"],["event_fee","Event / Activity Fee"],["other","Other Student Income"],
] as const;
const money=(n:number)=>`৳ ${new Intl.NumberFormat("en-BD",{minimumFractionDigits:2,maximumFractionDigits:2}).format(Number(n)||0)}`;
const today=()=>new Date().toISOString().slice(0,10);
const label=(key:string)=>feeTypes.find(x=>x[0]===key)?.[1]||key.replace(/_/g," ");

export default function StudentIncomeWorkspace({permissions={},adminMode=false}:{permissions?:Permissions;adminMode?:boolean}){
  const supabase=useMemo(()=>createClient(),[]);
  const token=typeof window!=="undefined"?window.localStorage.getItem("ctms_store_token"):null;
  const can=(key:string)=>adminMode||Boolean(permissions[key]);
  const canView=can("student_income_view"); const canCharge=can("student_income_charge"); const canCollect=can("student_income_collect"); const canEdit=can("student_income_edit"); const canReports=can("student_income_reports");
  const [month,setMonth]=useState(new Date().toISOString().slice(0,7)); const [feeType,setFeeType]=useState(""); const [entryType,setEntryType]=useState(""); const [search,setSearch]=useState("");
  const [entries,setEntries]=useState<Entry[]>([]); const [students,setStudents]=useState<Student[]>([]); const [summary,setSummary]=useState<Summary>({total_charged:0,total_collected:0,total_discount:0,total_due:0,month_collected:0,today_collected:0,students_with_fees:0});
  const [showCharge,setShowCharge]=useState(false); const [showCollect,setShowCollect]=useState(false); const [selected,setSelected]=useState<Student|null>(null); const [studentSearch,setStudentSearch]=useState("");
  const [message,setMessage]=useState(""); const [error,setError]=useState(""); const [loading,setLoading]=useState(false); const [saving,setSaving]=useState(false);
  const args=(extra:Record<string,unknown>={})=>({p_token:token||null,...extra});
  const load=useCallback(async()=>{if(!canView)return;setLoading(true);setError("");const [l,s]=await Promise.all([
    supabase.rpc("store_accounts_student_income_list",args({p_month:`${month}-01`,p_fee_type:feeType||null,p_status:entryType||null,p_search:search||null})),
    supabase.rpc("store_accounts_student_income_summary",args({p_month:`${month}-01"})),
  ]);if(l.error)setError(l.error.message);else setEntries((l.data||[]) as Entry[]);if(!s.error&&s.data)setSummary(s.data as Summary);else if(s.error)setError(s.error.message);setLoading(false)},[canView,month,feeType,entryType,search,supabase,token]);
  useEffect(()=>{void load()},[load]);
  const loadStudents=useCallback(async()=>{const r=await supabase.rpc("store_accounts_student_income_students",args({p_search:studentSearch||null}));if(r.error)setError(r.error.message);else setStudents((r.data||[]) as Student[])},[studentSearch,supabase,token]);
  useEffect(()=>{if(showCharge||showCollect)void loadStudents()},[showCharge,showCollect,loadStudents]);
  function openCharge(){setSelected(null);setShowCharge(true);setShowCollect(false);setMessage("");setError("")}; function openCollect(){setSelected(null);setShowCollect(true);setShowCharge(false);setMessage("");setError("")};
  async function submitCharge(e:FormEvent<HTMLFormElement>){e.preventDefault();if(!selected)return;setSaving(true);setError("");const f=new FormData(e.currentTarget);const r=await supabase.rpc("store_accounts_student_income_save_charge",args({p_student_id:selected.id,p_academic_year:String(f.get("academic_year")),p_fee_type:String(f.get("fee_type")),p_amount:Number(f.get("amount")),p_entry_date:String(f.get("entry_date")),p_due_date:String(f.get("due_date")||"")||null,p_reference_no:String(f.get("reference_no")||"")||null,p_notes:String(f.get("notes")||"")||null}));if(r.error)setError(r.error.message);else{setShowCharge(false);setMessage(`Student fee charge created. Reference: ${r.data?.reference_no||"-"}`);await load()}setSaving(false)}
  async function submitCollect(e:FormEvent<HTMLFormElement>){e.preventDefault();if(!selected)return;setSaving(true);setError("");const f=new FormData(e.currentTarget);const r=await supabase.rpc("store_accounts_student_income_collect",args({p_student_id:selected.id,p_academic_year:String(f.get("academic_year")),p_fee_type:String(f.get("fee_type")),p_amount:Number(f.get("amount")),p_payment_method:String(f.get("payment_method")),p_account_name:String(f.get("account_name")||"")||null,p_reference_no:String(f.get("reference_no")||"")||null,p_paid_at:String(f.get("paid_at")),p_notes:String(f.get("notes")||"")||null}));if(r.error)setError(r.error.message);else{setShowCollect(false);setMessage(`Payment collected successfully. Receipt: ${r.data?.receipt_no||"-"}`);await load()}setSaving(false)}
  if(!adminMode&&!canView&&!canCharge&&!canCollect&&!canEdit&&!canReports)return null;
  return <section className="mt-5 rounded-3xl border border-[var(--school-border)] bg-[var(--school-surface)] shadow-sm">
    <div className="border-b border-[var(--school-border)] bg-[var(--school-primary-soft)] p-5 sm:p-6"><div className="flex flex-col gap-4 lg:flex-row lg:items-end lg:justify-between"><div><p className="text-[10px] font-black uppercase tracking-[.16em] theme-primary">Accounts • Student Income</p><h2 className="mt-1 text-xl font-black">Student Fees & Collections</h2><p className="mt-1 text-xs text-[var(--school-muted)]">Admission, tuition, exam, transport, library, lab, certificate, fine and other student-related income. Charges and payments remain individual ledger entries.</p></div><div className="flex flex-wrap gap-2">{canCharge&&<button type="button" onClick={openCharge} className="rounded-xl px-4 py-2.5 text-xs font-black theme-primary-bg">+ Add Fee Charge</button>}{canCollect&&<button type="button" onClick={openCollect} className="rounded-xl border border-[var(--school-border)] px-4 py-2.5 text-xs font-black">Collect Payment</button>}</div></div></div>
    {message&&<div className="mx-5 mt-5 rounded-xl border border-[var(--school-primary-border)] bg-[var(--school-primary-soft)] p-3 text-xs font-semibold theme-primary sm:mx-6">{message}</div>}{error&&<div className="mx-5 mt-5 rounded-xl border border-red-200 bg-red-50 p-3 text-xs font-semibold text-red-700 sm:mx-6">{error}</div>}
    {canView&&<div className="p-5 sm:p-6"><div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-3 xl:grid-cols-6">{[["Total Charged",money(summary.total_charged),""],["Total Collected",money(summary.total_collected),"text-emerald-700"],["Total Discount",money(summary.total_discount),""],["Total Due",money(summary.total_due),"text-red-700"],["This Month",money(summary.month_collected),""],["Today",money(summary.today_collected),"text-emerald-700"]].map(([a,b,c])=><div key={String(a)} className="rounded-2xl border border-[var(--school-border)] p-4"><p className="text-[9px] font-black uppercase tracking-wider text-[var(--school-muted)]">{a}</p><p className={`mt-1 text-lg font-black ${c}`}>{b}</p></div>)}</div>
      <div className="mt-5 grid gap-2 sm:grid-cols-2 lg:grid-cols-4"><label className="text-[10px] font-bold text-[var(--school-muted)]">Month<input type="month" value={month} onChange={e=>setMonth(e.target.value)} className="mt-1 w-full rounded-xl border border-[var(--school-border)] bg-[var(--school-surface)] px-3 py-2.5 text-xs"/></label><label className="text-[10px] font-bold text-[var(--school-muted)]">Fee Type<select value={feeType} onChange={e=>setFeeType(e.target.value)} className="mt-1 w-full rounded-xl border border-[var(--school-border)] bg-[var(--school-surface)] px-3 py-2.5 text-xs"><option value="">All</option>{feeTypes.map(([v,l])=><option key={v} value={v}>{l}</option>)}</select></label><label className="text-[10px] font-bold text-[var(--school-muted)]">Entry Type<select value={entryType} onChange={e=>setEntryType(e.target.value)} className="mt-1 w-full rounded-xl border border-[var(--school-border)] bg-[var(--school-surface)] px-3 py-2.5 text-xs"><option value="">All</option><option value="charge">Charges</option><option value="payment">Payments</option><option value="discount">Discounts</option></select></label><label className="text-[10px] font-bold text-[var(--school-muted)]">Search<input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Student ID / name / receipt" className="mt-1 w-full rounded-xl border border-[var(--school-border)] bg-[var(--school-surface)] px-3 py-2.5 text-xs"/></label></div>
      {loading?<div className="py-10 text-center text-xs text-[var(--school-muted)]">Loading student income...</div>:entries.length===0?<div className="mt-5 rounded-2xl border border-dashed border-[var(--school-border)] p-10 text-center"><p className="text-sm font-black">No student income entries found</p><p className="mt-1 text-xs text-[var(--school-muted)]">Add a fee charge first, then collect payments against the student's outstanding balance.</p></div>:<div className="mt-5 overflow-x-auto rounded-2xl border border-[var(--school-border)]"><table className="w-full min-w-[1050px] text-left text-xs"><thead className="bg-[var(--school-primary-soft)]"><tr>{["Date","Student","Class","Fee Type","Entry","Reference","Amount","Method","Current Due"].map(h=><th key={h} className="p-3 text-[9px] font-black uppercase tracking-wider text-[var(--school-muted)]">{h}</th>)}</tr></thead><tbody>{entries.map(e=><tr key={e.id} className="border-t border-[var(--school-border)]"><td className="p-3">{e.entry_date}</td><td className="p-3"><p className="font-black">{e.full_name}</p><p className="text-[10px] text-[var(--school-muted)]">{e.student_id}</p></td><td className="p-3">{e.admission_class||"-"}{e.section?` • ${e.section}`:""}</td><td className="p-3">{label(e.fee_type)}</td><td className="p-3 font-black capitalize">{e.entry_type}</td><td className="p-3 font-bold">{e.reference_no||"-"}</td><td className="p-3 font-black">{money(e.amount)}</td><td className="p-3 capitalize">{e.payment_method||"-"}</td><td className="p-3 font-black text-red-700">{money(e.current_balance)}</td></tr>)}</tbody></table></div>}</div>}

    {(showCharge||showCollect)&&<div className="fixed inset-0 z-50 flex items-end justify-center bg-black/30 p-0 sm:items-center sm:p-5"><div className="max-h-[92vh] w-full max-w-2xl overflow-y-auto rounded-t-3xl bg-[var(--school-surface)] p-5 shadow-2xl sm:rounded-3xl sm:p-6"><div className="flex items-start justify-between gap-3"><div><p className="text-[10px] font-black uppercase tracking-[.16em] theme-primary">{showCharge?"Add Fee Charge":"Collect Student Payment"}</p><h3 className="mt-1 text-xl font-black">{showCharge?"Create Student Fee Charge":"Record Fee Collection"}</h3></div><button type="button" onClick={()=>{setShowCharge(false);setShowCollect(false)}} className="rounded-xl border border-[var(--school-border)] px-3 py-2 text-xs font-bold">Close</button></div>
      {!selected?<><input value={studentSearch} onChange={e=>setStudentSearch(e.target.value)} placeholder="Search Student ID or name" className="mt-5 w-full rounded-xl border border-[var(--school-border)] px-3 py-3 text-sm"/><div className="mt-3 space-y-2">{students.slice(0,20).map(s=><button type="button" key={s.id} onClick={()=>setSelected(s)} className="w-full rounded-2xl border border-[var(--school-border)] p-4 text-left hover:bg-[var(--school-primary-soft)]"><p className="font-black">{s.full_name}</p><p className="mt-1 text-xs text-[var(--school-muted)]">{s.student_id} • Class {s.admission_class||"-"}{s.section?` • ${s.section}`:""} • Due {money(s.balance_due)}</p></button>)}</div></>:<>{<div className="mt-5 rounded-2xl bg-[var(--school-primary-soft)] p-4"><p className="text-xs font-black">{selected.full_name}</p><p className="mt-1 text-[10px] text-[var(--school-muted)]">{selected.student_id} • Class {selected.admission_class||"-"}{selected.section?` • ${selected.section}`:""} • Current Due {money(selected.balance_due)}</p></div>}
      <form onSubmit={showCharge?submitCharge:submitCollect} className="mt-5 grid gap-4 sm:grid-cols-2"><label><span className="text-xs font-bold">Academic Year *</span><input name="academic_year" required defaultValue={selected.academic_year||String(new Date().getFullYear())} className="mt-1 w-full rounded-xl border border-[var(--school-border)] px-3 py-3 text-sm"/></label><label><span className="text-xs font-bold">Fee Type *</span><select name="fee_type" required defaultValue="tuition_fee" className="mt-1 w-full rounded-xl border border-[var(--school-border)] px-3 py-3 text-sm">{feeTypes.map(([v,l])=><option key={v} value={v}>{l}</option>)}</select></label><label><span className="text-xs font-bold">Amount *</span><input name="amount" required type="number" min="0.01" step="0.01" className="mt-1 w-full rounded-xl border border-[var(--school-border)] px-3 py-3 text-sm"/></label>{showCharge?<><label><span className="text-xs font-bold">Entry Date *</span><input name="entry_date" required type="date" defaultValue={today()} className="mt-1 w-full rounded-xl border border-[var(--school-border)] px-3 py-3 text-sm"/></label><label><span className="text-xs font-bold">Due Date</span><input name="due_date" type="date" className="mt-1 w-full rounded-xl border border-[var(--school-border)] px-3 py-3 text-sm"/></label></>:<><label><span className="text-xs font-bold">Payment Date *</span><input name="paid_at" required type="date" defaultValue={today()} className="mt-1 w-full rounded-xl border border-[var(--school-border)] px-3 py-3 text-sm"/></label><label><span className="text-xs font-bold">Payment Method *</span><select name="payment_method" defaultValue="cash" className="mt-1 w-full rounded-xl border border-[var(--school-border)] px-3 py-3 text-sm"><option value="cash">Cash</option><option value="bank">Bank</option><option value="cheque">Cheque</option><option value="mobile_banking">Mobile Banking</option><option value="other">Other</option></select></label><label><span className="text-xs font-bold">Account / Bank</span><input name="account_name" className="mt-1 w-full rounded-xl border border-[var(--school-border)] px-3 py-3 text-sm"/></label></>}<label className="sm:col-span-2"><span className="text-xs font-bold">{showCharge?"Reference No":"Receipt / Reference No"}</span><input name="reference_no" className="mt-1 w-full rounded-xl border border-[var(--school-border)] px-3 py-3 text-sm"/></label><label className="sm:col-span-2"><span className="text-xs font-bold">Notes</span><textarea name="notes" rows={3} className="mt-1 w-full rounded-xl border border-[var(--school-border)] px-3 py-3 text-sm"/></label><button disabled={saving} className="sm:col-span-2 rounded-xl px-5 py-3.5 text-sm font-black theme-primary-bg disabled:opacity-60">{saving?(showCharge?"Saving charge...":"Recording payment..."):(showCharge?"Create Fee Charge":"Collect Payment")}</button></form></>}
    </div></div>}
  </section>;
}
