"use client";

import Link from "next/link";
import { useMemo, useState } from "react";
import SuperAdminParentWorkspace from "@/components/admin/SuperAdminParentWorkspace";
import SuperAdminHRWorkspace from "@/components/admin/SuperAdminHRWorkspace";

type Activity={id:string;module:string;action:string;reference?:string|null;detail?:string|null;status?:string|null;createdAt:string};
type Action={label:string;href:string;hint?:string};
type Module={id:string;title:string;code:string;group:string;description:string;actions:Action[]};

const modules:Module[]=[
{id:"dashboard",title:"Command Center",code:"01",group:"Overview",description:"Everything important at a glance. Open pending work, recent activity, shortcuts and module health from one place.",actions:[{label:"Command Center",href:"/admin"},{label:"Pending Actions",href:"/admin"},{label:"System Activity",href:"/admin"},{label:"Global Search",href:"/admin"}]},
{id:"people",title:"People & Registrations",code:"02",group:"People",description:"Parents, guardians, students, members, teachers and staff entry points.",actions:[{label:"Parents & Guardians",href:"/admin/parents"},{label:"Parent Accounts",href:"/admin/parents"},{label:"Child Binding",href:"/admin/parents"},{label:"Parent Approvals",href:"/admin/parents"},{label:"People Directory",href:"/admin/people"},{label:"Members",href:"/admin/members"},{label:"Student Registrations",href:"/admin/people"}]},
{id:"hr",title:"Human Resources",code:"03",group:"HR",description:"Staff and teacher records, attendance, payroll and monthly salary processing.",actions:[{label:"Staff & Teachers",href:"/admin/hr"},{label:"Attendance",href:"/admin/hr"},{label:"Payroll",href:"/admin/hr"},{label:"Monthly Salary Sheet",href:"/admin/hr"},{label:"Salary Submission",href:"/admin/hr"}]},
{id:"inventory",title:"Inventory & Procurement",code:"04",group:"Store",description:"Stock, products, suppliers, procurement, receiving, issuing, returns, handover and reports.",actions:[{label:"Inventory Dashboard",href:"/admin/inventory"},{label:"Items & Products",href:"/admin/inventory/products"},{label:"Add / Edit Items",href:"/admin/inventory"},{label:"Suppliers",href:"/admin/inventory/suppliers"},{label:"Inventory Persons",href:"/admin/inventory/persons"},{label:"Stock In",href:"/admin/inventory/stock-in"},{label:"Stock Out",href:"/admin/inventory/stock-out"},{label:"Issue Stock",href:"/admin/inventory/issue"},{label:"Return Stock",href:"/admin/inventory/return"},{label:"Handover",href:"/admin/inventory/handover"},{label:"Takeover",href:"/admin/inventory/takeover"},{label:"Procurement",href:"/admin/inventory/procurement"},{label:"Procurement Reports",href:"/admin/inventory/reports"}]},
{id:"sr",title:"Service Requests",code:"05",group:"Workflow",description:"Create, review, approve, issue and track Item Service Requests without hunting through pages.",actions:[{label:"Create Service Request",href:"/admin/item-sr"},{label:"My SR",href:"/admin/item-sr"},{label:"Awaiting Approval",href:"/admin/item-sr"},{label:"Approved SR",href:"/admin/item-sr"},{label:"Issued SR",href:"/admin/item-sr"},{label:"SR History",href:"/admin/item-sr"},{label:"Print / View SR",href:"/admin/item-sr"}]},
{id:"accounts",title:"Accounts & Finance",code:"06",group:"Finance",description:"Fees, income, expense, bills, purchase-order payments, cash, bank, journal, ledger and reports.",actions:[{label:"Accounts Dashboard",href:"/admin/accounts"},{label:"Fees",href:"/admin/accounts/fees"},{label:"Income",href:"/admin/accounts/income"},{label:"New Expense",href:"/admin/accounts/expense/new"},{label:"Expense",href:"/admin/accounts/expense"},{label:"Bill Payments",href:"/admin/accounts"},{label:"PO Payments",href:"/admin/accounts"},{label:"Cashbook",href:"/admin/accounts/cashbook"},{label:"Bank",href:"/admin/accounts/bank"},{label:"Journal",href:"/admin/accounts/journal"},{label:"Ledger",href:"/admin/accounts/ledger"},{label:"Member Account Lookup",href:"/admin/accounts"},{label:"Financial Reports",href:"/admin/accounts/reports"}]},
{id:"academic",title:"Academic & Communication",code:"07",group:"School",description:"Results, notices and administrative communication.",actions:[{label:"Results",href:"/admin/results"},{label:"Notice Board",href:"/admin/notices"},{label:"Publish Notice",href:"/admin/notices"}]},
{id:"access",title:"Access & System Control",code:"08",group:"Control",description:"Roles, permissions, portals, settings and administrative audit controls.",actions:[{label:"Role Management",href:"/admin/roles"},{label:"Permission Builder",href:"/admin/roles"},{label:"PR & PO Permissions",href:"/admin/roles"},{label:"Admin Portals",href:"/admin/portals"},{label:"System Settings",href:"/admin/settings"},{label:"Audit & Activity",href:"/admin"}]},
];

const pendingStatus=["pending","due","partially_issued","awaiting_approval","submitted","under_review","pending_approval"];

export default function OracleSuperAdminShell({fullName,email,roleName,activityItems=[]}:{fullName?:string|null;email?:string|null;roleName:string;activityItems?:Activity[]}){
 const [selected,setSelected]=useState("dashboard");
 const [query,setQuery]=useState("");
 const [expanded,setExpanded]=useState<string[]>(modules.map(m=>m.id));
 const [busy,setBusy]=useState(false);
 const current=modules.find(m=>m.id===selected)||modules[0];
 const name=fullName||email||"Super Admin";
 const role=roleName.replace(/_/g," ");
 const pending=activityItems.filter(x=>pendingStatus.includes((x.status||"").toLowerCase()));
 const allActions=useMemo(()=>modules.flatMap(m=>m.actions.map(a=>({...a,module:m.title}))),[]);
 const filteredModules=useMemo(()=>{const q=query.trim().toLowerCase();if(!q)return modules;return modules.map(m=>({...m,actions:m.actions.filter(a=>`${m.title} ${m.group} ${a.label}`.toLowerCase().includes(q))})).filter(m=>m.actions.length||`${m.title} ${m.group}`.toLowerCase().includes(q));},[query]);
 const toggle=(id:string)=>setExpanded(v=>v.includes(id)?v.filter(x=>x!==id):[...v,id]);
 const openModule=(m:Module)=>{setSelected(m.id);if(!expanded.includes(m.id))setExpanded(v=>[...v,m.id]);};
 const logout=async()=>{if(busy)return;setBusy(true);try{await fetch("/api/auth/logout",{method:"POST"})}finally{window.location.href="https://ct-model-school-management.vercel.app/loginportal"}};
 return <div className="mx-auto w-full max-w-[1720px]"><div className="overflow-hidden rounded-[22px] border border-[var(--school-border)] bg-[var(--school-surface)] shadow-sm lg:grid lg:grid-cols-[292px_minmax(0,1fr)]">
  <aside className="flex max-h-[calc(100vh-6rem)] min-h-[760px] flex-col border-b border-[var(--school-border)] bg-[var(--school-surface)] lg:border-b-0 lg:border-r">
   <div className="border-b border-[var(--school-border)] px-5 py-5"><div className="flex items-center gap-3"><div className="grid h-10 w-10 place-items-center rounded-xl theme-primary-bg text-xs font-black">CT</div><div className="min-w-0"><p className="truncate text-xs font-black">C.T. Model School</p><p className="truncate text-[9px] font-semibold text-[var(--school-muted)]">Digital Management System</p></div></div><div className="mt-4 flex items-center justify-between"><span className="rounded-full bg-[var(--school-primary-soft)] px-2.5 py-1 text-[9px] font-black uppercase theme-primary">Super Admin</span><span className="text-[9px] font-bold text-[var(--school-muted)]">● Active</span></div></div>
   <div className="border-b border-[var(--school-border)] p-3"><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search any module or action…" className="w-full rounded-xl border border-[var(--school-border)] bg-[var(--school-background)] px-3 py-2.5 text-[10px] font-semibold outline-none focus:border-[var(--school-primary-border)]"/></div>
   <div className="flex-1 overflow-y-auto p-3"><div className="mb-2 flex items-center justify-between px-2"><p className="text-[9px] font-black uppercase tracking-[.18em] text-[var(--school-muted)]">All administration</p><span className="text-[9px] font-black theme-primary">{allActions.length} actions</span></div><nav className="space-y-1">{filteredModules.map(m=>{const active=m.id===selected,open=expanded.includes(m.id);return <div key={m.id}><button type="button" onClick={()=>{openModule(m);toggle(m.id)}} className={`flex w-full items-center gap-2 rounded-xl border px-2.5 py-2.5 text-left ${active?"border-[var(--school-primary-border)] bg-[var(--school-primary-soft)]":"border-transparent hover:bg-[var(--school-background)]"}`}><span className={`grid h-7 w-7 shrink-0 place-items-center rounded-lg text-[8px] font-black ${active?"bg-[var(--school-surface)] theme-primary":"bg-[var(--school-background)] text-[var(--school-muted)]"}`}>{m.code}</span><span className="min-w-0 flex-1"><b className={`block truncate text-[10px] ${active?"theme-primary":""}`}>{m.title}</b><small className="block truncate text-[8px] text-[var(--school-muted)]">{m.group} · {m.actions.length} actions</small></span><span className={`text-[11px] transition-transform ${open?"rotate-180":""}`}>⌄</span></button>{open?<div className="ml-9 mt-1 space-y-0.5 border-l border-[var(--school-border)] pl-2">{m.actions.map((a,i)=><Link key={`${m.id}-${a.label}`} href={a.href} onClick={()=>setSelected(m.id)} className="flex items-center gap-2 rounded-lg px-2 py-2 text-[9px] font-semibold text-[var(--school-muted)] hover:bg-[var(--school-background)] hover:theme-primary"><span className="w-4 text-[8px] font-black text-[var(--school-muted)]">{String(i+1).padStart(2,"0")}</span><span className="truncate">{a.label}</span></Link>)}</div>:null}</div>})}</nav></div>
   <div className="border-t border-[var(--school-border)] p-3"><div className="rounded-xl bg-[var(--school-background)] p-3"><p className="truncate text-[10px] font-black">{name}</p><p className="mt-0.5 truncate text-[8px] font-bold capitalize theme-primary">{role}</p><button type="button" onClick={logout} disabled={busy} className="mt-3 w-full rounded-lg border border-[var(--school-border)] bg-[var(--school-surface)] px-3 py-2 text-[9px] font-black theme-primary">{busy?"Logging out…":"Logout"}</button></div></div>
  </aside>
  <main className="min-w-0 bg-[var(--school-background)]"><header className="sticky top-0 z-30 border-b border-[var(--school-border)] bg-[var(--school-surface)]/95 px-4 py-3 backdrop-blur sm:px-6 lg:px-8"><div className="flex items-center gap-3"><div><p className="text-[9px] font-black uppercase tracking-[.18em] theme-primary">{current.group}</p><p className="text-sm font-black">{current.title}</p></div><div className="ml-auto flex items-center gap-2"><span className="hidden rounded-full border border-[var(--school-border)] px-3 py-1.5 text-[9px] font-bold text-[var(--school-muted)] sm:inline-flex">Enterprise command access</span><span className="grid h-8 w-8 place-items-center rounded-full bg-[var(--school-primary-soft)] text-[10px] font-black theme-primary">{name.slice(0,1).toUpperCase()}</span></div></div></header><div className="p-4 sm:p-6 lg:p-8">{selected==="dashboard"?<CommandCenter name={name} pending={pending} activity={activityItems} modules={modules} onSelect={openModule}/>:<ModuleLanding module={current} activity={activityItems} pending={pending}/>}</div></main>
  </div></div>;
}

function CommandCenter({name,pending,activity,modules,onSelect}:{name:string;pending:Activity[];activity:Activity[];modules:Module[];onSelect:(m:Module)=>void}){const [mode,setMode]=useState<"actions"|"activity"|"pending">("actions");const actionCount=modules.reduce((n,m)=>n+m.actions.length,0);return <div className="space-y-6"><div className="flex flex-col gap-4 border-b border-[var(--school-border)] pb-5 xl:flex-row xl:items-end xl:justify-between"><div><p className="text-[9px] font-black uppercase tracking-[.2em] theme-primary">Super Admin / Command Center</p><h1 className="mt-2 text-3xl font-black tracking-tight sm:text-4xl">Welcome, {name}</h1><p className="mt-2 max-w-3xl text-sm leading-6 text-[var(--school-muted)]">A single control surface for every administrative action. Nothing is hidden behind a module hunt.</p></div><div className="grid grid-cols-3 gap-2 sm:w-[360px]"><Stat label="Modules" value={String(modules.length)}/><Stat label="Actions" value={String(actionCount)}/><Stat label="Pending" value={String(pending.length)} primary/></div></div><section className="grid gap-3 md:grid-cols-3"><Quick title="Review pending" value={`${pending.length} items`} onClick={()=>setMode("pending")} primary/><Quick title="Recent activity" value={`${activity.length} live records`} onClick={()=>setMode("activity")}/><Quick title="All actions" value="Browse by module" onClick={()=>setMode("actions")}/></section>{mode==="actions"?<div className="space-y-4"><div><p className="text-[9px] font-black uppercase tracking-[.18em] theme-primary">Action catalog</p><h2 className="mt-1 text-xl font-black">Everything you can do</h2></div><div className="grid gap-4 md:grid-cols-2 xl:grid-cols-3">{modules.filter(m=>m.id!=="dashboard").map(m=><button key={m.id} type="button" onClick={()=>onSelect(m)} className="group rounded-2xl border border-[var(--school-border)] bg-[var(--school-surface)] p-5 text-left transition hover:-translate-y-0.5 hover:border-[var(--school-primary-border)] hover:shadow-sm"><div className="flex items-start justify-between gap-3"><div><p className="text-[9px] font-black uppercase tracking-[.16em] theme-primary">{m.code} · {m.group}</p><h3 className="mt-1 text-base font-black">{m.title}</h3></div><span className="rounded-full bg-[var(--school-primary-soft)] px-2 py-1 text-[8px] font-black theme-primary">{m.actions.length}</span></div><p className="mt-2 text-[10px] leading-5 text-[var(--school-muted)]">{m.description}</p><div className="mt-4 grid gap-1.5">{m.actions.slice(0,5).map(a=><div key={a.label} className="rounded-lg bg-[var(--school-background)] px-2.5 py-2 text-[9px] font-semibold text-[var(--school-muted)]">{a.label}</div>)}{m.actions.length>5?<div className="px-2.5 pt-1 text-[8px] font-black theme-primary">+ {m.actions.length-5} more actions</div>:null}</div></button>)}</div></div>:mode==="pending"?<ActivityList title="Pending Actions" items={pending}/>:<ActivityList title="Recent System Activity" items={activity}/>}</div>}

function ModuleLanding({module,activity,pending}:{module:Module;activity:Activity[];pending:Activity[]}){if(module.id==="people")return <SuperAdminParentWorkspace section="Parent Accounts"/>;if(module.id==="hr")return <SuperAdminHRWorkspace section="Staff & Teachers"/>;return <div className="space-y-6"><div className="border-b border-[var(--school-border)] pb-5"><p className="text-[9px] font-black uppercase tracking-[.18em] theme-primary">Administration / {module.group}</p><h1 className="mt-2 text-3xl font-black tracking-tight">{module.title}</h1><p className="mt-2 max-w-3xl text-sm leading-6 text-[var(--school-muted)]">{module.description}</p></div><section className="rounded-2xl border border-[var(--school-border)] bg-[var(--school-surface)] p-5"><div className="flex items-center justify-between gap-3"><div><p className="text-[9px] font-black uppercase tracking-[.16em] theme-primary">Action Center</p><h2 className="mt-1 text-lg font-black">Choose an action</h2></div><span className="rounded-full bg-[var(--school-primary-soft)] px-2.5 py-1 text-[8px] font-black theme-primary">{module.actions.length} actions</span></div><div className="mt-4 grid gap-2 sm:grid-cols-2 xl:grid-cols-3">{module.actions.map((a,i)=><Link key={a.label} href={a.href} className="group rounded-xl border border-[var(--school-border)] bg-[var(--school-background)] p-3 transition hover:border-[var(--school-primary-border)] hover:bg-[var(--school-primary-soft)]"><div className="flex items-center gap-3"><span className="grid h-7 w-7 shrink-0 place-items-center rounded-lg bg-[var(--school-surface)] text-[8px] font-black theme-primary">{String(i+1).padStart(2,"0")}</span><span className="min-w-0 flex-1 text-[10px] font-black group-hover:theme-primary">{a.label}</span><span className="text-xs text-[var(--school-muted)]">→</span></div></Link>)}</div></section><div className="grid gap-4 lg:grid-cols-2"><ActivityList title="Related pending" items={pending.slice(0,8)}/><ActivityList title="Recent activity" items={activity.slice(0,8)}/></div></div>}

function ActivityList({title,items}:{title:string;items:Activity[]}){return <section className="rounded-2xl border border-[var(--school-border)] bg-[var(--school-surface)] p-4 sm:p-5"><div className="flex items-center justify-between"><div><p className="text-[9px] font-black uppercase tracking-[.16em] theme-primary">Live records</p><h2 className="mt-1 text-base font-black">{title}</h2></div><span className="text-[9px] font-bold text-[var(--school-muted)]">{items.length}</span></div><div className="mt-4">{items.length?<div className="divide-y divide-[var(--school-border)] overflow-hidden rounded-xl border border-[var(--school-border)]">{items.slice(0,10).map(x=><div key={x.id} className="grid gap-2 px-3 py-3 sm:grid-cols-[1.5fr_.7fr_.7fr]"><div><p className="text-[10px] font-black">{x.action}</p><p className="mt-0.5 truncate text-[8px] text-[var(--school-muted)]">{x.module}{x.detail?` · ${x.detail}`:""}</p></div><p className="text-[8px] font-bold text-[var(--school-muted)]">{x.reference||"—"}</p><div><span className="rounded-full border border-[var(--school-border)] px-2 py-1 text-[7px] font-black">{status(x.status)}</span><p className="mt-1 text-[7px] text-[var(--school-muted)]">{date(x.createdAt)}</p></div></div>)}</div>:<Empty text="Nothing waiting here."/>}</div></section>}
function Stat({label,value,primary=false}:{label:string;value:string;primary?:boolean}){return <div className="rounded-xl border border-[var(--school-border)] bg-[var(--school-surface)] p-3"><p className="text-[8px] font-black uppercase tracking-[.14em] text-[var(--school-muted)]">{label}</p><p className={`mt-1 text-xl font-black ${primary?"theme-primary":""}`}>{value}</p></div>}
function Quick({title,value,onClick,primary=false}:{title:string;value:string;onClick:()=>void;primary?:boolean}){return <button type="button" onClick={onClick} className={`rounded-2xl border p-4 text-left ${primary?"border-[var(--school-primary-border)] bg-[var(--school-primary-soft)]":"border-[var(--school-border)] bg-[var(--school-surface)]"}`}><p className="text-[9px] font-black uppercase tracking-[.15em] theme-primary">{title}</p><p className="mt-1 text-sm font-black">{value}</p></button>}
function Empty({text}:{text:string}){return <div className="rounded-xl border border-dashed border-[var(--school-border)] p-7 text-center text-[9px] font-semibold text-[var(--school-muted)]">{text}</div>}
function status(v?:string|null){return v?v.replace(/_/g," ").replace(/\b\w/g,c=>c.toUpperCase()):"Updated"}
function date(v:string){const d=new Date(v);return Number.isNaN(d.getTime())?v:new Intl.DateTimeFormat("en-GB",{day:"2-digit",month:"short",hour:"2-digit",minute:"2-digit",hour12:true,timeZone:"Asia/Dhaka"}).format(d)}
