"use client";

import Link from "next/link";
import { useMemo, useState } from "react";
import SuperAdminParentWorkspace from "@/components/admin/SuperAdminParentWorkspace";
import SuperAdminHRWorkspace from "@/components/admin/SuperAdminHRWorkspace";

type Section={title:string;href?:string};
type Module={id:string;title:string;code:string;group:string;description:string;sections:Section[]};
type Activity={id:string;module:string;action:string;reference?:string|null;detail?:string|null;status?:string|null;createdAt:string};

const M:Module[]=[
{id:"dashboard",title:"Dashboard",code:"01",group:"Overview",description:"Live administration overview, system activity and pending work.",sections:[{title:"Overview"},{title:"System Activity"},{title:"Pending Actions"}]},
{id:"parents",title:"Parents & Guardians",code:"02",group:"People",description:"Parent accounts, child binding, approvals and parent records.",sections:["Parent Accounts","Child Binding","Approvals","Parent Records"].map(title=>({title}))},
{id:"hr",title:"Human Resources",code:"03",group:"HR",description:"Staff, teachers, attendance, payroll and monthly salary operations.",sections:["Staff & Teachers","Attendance","Payroll","Monthly Salary Sheet"].map(title=>({title}))},
{id:"inventory",title:"Inventory",code:"04",group:"Store",description:"Items, stock, service requests and stock history.",sections:["Add Items","Items","Issue SR","SR","Stock History"].map(title=>({title,href:"/admin/inventory"}))},
{id:"item-sr",title:"Item Service Request",code:"05",group:"Workflow",description:"Request review, approval, issue and service-request history.",sections:["My SR","Awaiting Approval","Approved SR","Issued SR","SR History"].map(title=>({title,href:"/admin/item-sr"}))},
{id:"accounts",title:"Accounts",code:"06",group:"Finance",description:"Financial records, bills, payroll settlement, ledger and reports.",sections:["Dashboard","Ledger","Bill Payments","PO Payments","Payroll","Reports"].map(title=>({title,href:"/admin/accounts"}))},
{id:"settings",title:"Access & Settings",code:"07",group:"Control",description:"Roles, permissions, system settings and audit controls.",sections:[{title:"Role Management",href:"/admin/roles"},{title:"Permission Builder",href:"/admin/roles"},{title:"PR & PO Permissions",href:"/admin/roles"},{title:"System Settings",href:"/admin/settings"},{title:"Audit & Activity",href:"/admin"}]}
];
const pendingStatus=["pending","due","partially_issued","awaiting_approval","submitted","under_review","pending_approval"];

export default function OracleSuperAdminShell({fullName,email,roleName,activityItems=[]}:{fullName?:string|null;email?:string|null;roleName:string;activityItems?:Activity[]}){
 const [selected,setSelected]=useState("dashboard"),[section,setSection]=useState("Overview"),[open,setOpen]=useState<string|null>("dashboard"),[find,setFind]=useState(""),[busy,setBusy]=useState(false);
 const current=M.find(x=>x.id===selected)||M[0],name=fullName||email||"Super Admin",role=roleName.replace(/_/g," ");
 const modules=useMemo(()=>M.filter(x=>!find||`${x.title} ${x.group} ${x.sections.map(s=>s.title).join(" ")}`.toLowerCase().includes(find.toLowerCase())),[find]);
 const pending=activityItems.filter(x=>pendingStatus.includes((x.status||"").toLowerCase()));
 const select=(m:Module)=>{const same=m.id===selected;setSelected(m.id);setSection(m.sections[0].title);setOpen(same&&open===m.id?null:m.id)};
 const selectSection=(m:Module,s:Section)=>{setSelected(m.id);setSection(s.title);setOpen(m.id)};
 const logout=async()=>{if(busy)return;setBusy(true);try{await fetch("/api/auth/logout",{method:"POST"})}finally{window.location.href="https://ct-model-school-management.vercel.app/loginportal"}};
 return <div className="mx-auto w-full max-w-[1580px]"><div className="min-h-[calc(100vh-7rem)] overflow-hidden rounded-[26px] border border-[var(--school-border)] bg-[var(--school-surface)] shadow-sm lg:grid lg:grid-cols-[250px_minmax(0,1fr)]">
 <aside className="flex flex-col border-b border-[var(--school-border)] bg-[var(--school-surface)] lg:border-b-0 lg:border-r">
  <div className="border-b border-[var(--school-border)] p-5"><p className="text-[10px] font-black uppercase tracking-[.2em] theme-primary">C.T. Model School</p><p className="mt-1 text-sm font-black">Management System</p><div className="mt-4 flex gap-2"><span className="rounded-full bg-[var(--school-primary-soft)] px-2.5 py-1 text-[9px] font-black uppercase theme-primary">Super Admin</span><span className="rounded-full border border-[var(--school-border)] px-2.5 py-1 text-[9px] font-bold text-[var(--school-muted)]">● Active</span></div></div>
  <div className="border-b border-[var(--school-border)] p-3"><input value={find} onChange={e=>setFind(e.target.value)} placeholder="Find module or section" className="w-full rounded-xl border border-[var(--school-border)] bg-[var(--school-background)] px-3 py-2.5 text-[10px] font-semibold outline-none"/></div>
  <nav className="space-y-1 p-3">{modules.map(m=>{const active=m.id===selected,expanded=open===m.id;return <div key={m.id}><button type="button" onClick={()=>select(m)} aria-expanded={expanded} className={`flex w-full items-center gap-2.5 rounded-xl border px-2.5 py-2.5 text-left ${active?"border-[var(--school-primary-border)] bg-[var(--school-primary-soft)]":"border-transparent hover:bg-[var(--school-background)]"}`}><b className={`grid h-7 w-7 shrink-0 place-items-center rounded-lg text-[9px] ${active?"bg-[var(--school-surface)] theme-primary":"bg-[var(--school-background)] text-[var(--school-muted)]"}`}>{m.code}</b><span className="min-w-0 flex-1"><b className={`block truncate text-[10px] ${active?"theme-primary":""}`}>{m.title}</b><small className="block truncate text-[8px] text-[var(--school-muted)]">{m.group}</small></span><span className={expanded?"rotate-180":""}>⌄</span></button>{expanded?<div className="ml-9 mt-1 space-y-0.5 border-l border-[var(--school-border)] pl-2">{m.sections.map((s,i)=>s.href&&m.id!=="parents"&&m.id!=="hr"?<Link key={s.title} href={s.href} onClick={()=>selectSection(m,s)} className={`flex items-center gap-2 rounded-lg px-2 py-2 text-[9px] ${active&&section===s.title?"bg-[var(--school-primary-soft)] font-black theme-primary":"text-[var(--school-muted)]"}`}><span className="w-4 text-[8px]">{i+1}</span>{s.title}</Link>:<button key={s.title} type="button" onClick={()=>selectSection(m,s)} className={`flex w-full items-center gap-2 rounded-lg px-2 py-2 text-left text-[9px] ${active&&section===s.title?"bg-[var(--school-primary-soft)] font-black theme-primary":"text-[var(--school-muted)]"}`}><span className="w-4 text-[8px]">{i+1}</span>{s.title}</button>)}</div>:null}</div>})}</nav>
  <div className="mt-auto border-t border-[var(--school-border)] p-3"><div className="rounded-xl bg-[var(--school-background)] p-3"><p className="truncate text-[10px] font-black">{name}</p><p className="mt-0.5 truncate text-[8px] font-bold capitalize theme-primary">{role}</p><button onClick={logout} disabled={busy} className="mt-3 w-full rounded-lg border border-[var(--school-border)] bg-[var(--school-surface)] px-3 py-2 text-[9px] font-black theme-primary">{busy?"Logging out...":"Logout"}</button></div></div>
 </aside>
 <main className="min-w-0 bg-[var(--school-background)]"><header className="sticky top-0 z-30 border-b border-[var(--school-border)] bg-[var(--school-surface)]/95 px-4 py-3 backdrop-blur sm:px-6 lg:px-8"><div className="flex items-center gap-3"><div><p className="text-[9px] font-black uppercase tracking-[.18em] theme-primary">{current.group}</p><p className="text-sm font-black">{current.title}</p></div><div className="ml-auto flex items-center gap-2"><span className="hidden rounded-full border border-[var(--school-border)] px-3 py-1.5 text-[9px] text-[var(--school-muted)] sm:inline-flex">System access active</span><span className="grid h-8 w-8 place-items-center rounded-full bg-[var(--school-primary-soft)] text-[10px] font-black theme-primary">{name.slice(0,1).toUpperCase()}</span></div></div></header>
  <div className="p-4 sm:p-6 lg:p-8"><div className="mb-5 flex flex-col gap-4 border-b border-[var(--school-border)] pb-5 sm:flex-row sm:items-end sm:justify-between"><div><p className="text-[9px] font-black uppercase tracking-[.18em] text-[var(--school-muted)]">Administration / {current.title} / {section}</p><h1 className="mt-2 text-3xl font-black tracking-tight">{section}</h1><p className="mt-1 max-w-3xl text-sm text-[var(--school-muted)]">{current.description}</p></div><div className="grid grid-cols-2 gap-2 sm:w-[270px]"><Info label="Role" value={role}/><Info label="Live records" value={String(activityItems.length)}/></div></div>
   {selected==="dashboard"?<Dashboard section={section} items={activityItems} pending={pending} name={name}/>:selected==="parents"?<SuperAdminParentWorkspace section={section as "Parent Accounts"|"Child Binding"|"Approvals"|"Parent Records"}/>:selected==="hr"?<SuperAdminHRWorkspace section={section as "Staff & Teachers"|"Attendance"|"Payroll"|"Monthly Salary Sheet"}/>:<Workspace module={current} section={section}/>}</div></main></div></div>
}

function Dashboard({section,items,pending,name}:{section:string;items:Activity[];pending:Activity[];name:string}){if(section==="System Activity")return <Records title="System Activity" items={items}/>;if(section==="Pending Actions")return <Pending items={pending}/>;return <div className="space-y-5"><div className="grid gap-3 sm:grid-cols-2 xl:grid-cols-4"><Metric label="Access" value="Active" note="Super Admin"/><Metric label="Modules" value="07" note="Administration"/><Metric label="Activity" value={String(items.length)} note="Live records"/><Metric label="Pending" value={String(pending.length)} note="Needs attention" primary/></div><div className="grid gap-5 xl:grid-cols-[1.5fr_1fr]"><Records title="Recent System Activity" items={items.slice(0,8)}/><Pending items={pending.slice(0,6)}/></div><div className="rounded-2xl border border-[var(--school-border)] bg-[var(--school-surface)] p-5"><p className="text-[9px] font-black uppercase theme-primary">Workspace</p><h2 className="mt-1 text-lg font-black">Welcome, {name}</h2><p className="mt-1 text-xs text-[var(--school-muted)]">Use the Navigator on the left. Each module owns its own workflow.</p></div></div>}
function Records({title,items}:{title:string;items:Activity[]}){return <section className="rounded-2xl border border-[var(--school-border)] bg-[var(--school-surface)] p-4 sm:p-5"><p className="text-[9px] font-black uppercase theme-primary">Live records</p><h2 className="mt-1 text-lg font-black">{title}</h2><div className="mt-4">{items.length?<div className="divide-y divide-[var(--school-border)] overflow-hidden rounded-xl border border-[var(--school-border)]">{items.map(x=><div key={x.id} className="grid gap-2 px-4 py-3 sm:grid-cols-[1.5fr_.7fr_.7fr]"><div><p className="text-xs font-black">{x.action}</p><p className="text-[9px] text-[var(--school-muted)]">{x.module}{x.detail?` · ${x.detail}`:""}</p></div><p className="text-[9px] text-[var(--school-muted)]">{x.reference||"—"}</p><div><span className="rounded-full border border-[var(--school-border)] px-2 py-1 text-[8px]">{status(x.status)}</span><p className="mt-1 text-[8px] text-[var(--school-muted)]">{date(x.createdAt)}</p></div></div>)}</div>:<Empty text="No records found."/>}</div></section>}
function Pending({items}:{items:Activity[]}){return <section className="rounded-2xl border border-[var(--school-border)] bg-[var(--school-surface)] p-4 sm:p-5"><p className="text-[9px] font-black uppercase theme-primary">Live queue</p><h2 className="mt-1 text-lg font-black">Pending Actions</h2><div className="mt-4 space-y-2">{items.length?items.map(x=><div key={x.id} className="rounded-xl border border-[var(--school-border)] p-3"><p className="text-[8px] font-black uppercase theme-primary">{x.module}</p><p className="mt-1 text-xs font-black">{x.action}</p><p className="mt-1 text-[9px] text-[var(--school-muted)]">{x.reference||"No reference"}</p></div>):<Empty text="No pending actions in the existing records."/>}</div></section>}
function Workspace({module,section}:{module:Module;section:string}){const s=module.sections.find(x=>x.title===section)||module.sections[0];return <section className="rounded-2xl border border-[var(--school-border)] bg-[var(--school-surface)] p-6 sm:p-8"><p className="text-[9px] font-black uppercase theme-primary">{module.group} workspace</p><h2 className="mt-2 text-2xl font-black">{section}</h2><p className="mt-2 max-w-2xl text-sm text-[var(--school-muted)]">Live business logic and database remain unchanged. This is the new enterprise navigation layer.</p>{s.href?<Link href={s.href} className="mt-5 inline-flex rounded-xl px-4 py-3 text-xs font-black theme-primary-bg">Open live workspace →</Link>:null}<div className="mt-6 grid gap-2 sm:grid-cols-2 lg:grid-cols-3">{module.sections.map(x=><div key={x.title} className={`rounded-xl border p-3 text-xs font-bold ${x.title===section?"border-[var(--school-primary-border)] bg-[var(--school-primary-soft)] theme-primary":"border-[var(--school-border)] bg-[var(--school-background)]"}`}>{x.title}</div>)}</div></section>}
function Metric({label,value,note,primary=false}:{label:string;value:string;note:string;primary?:boolean}){return <div className="rounded-xl border border-[var(--school-border)] bg-[var(--school-surface)] p-4"><p className="text-[8px] font-black uppercase text-[var(--school-muted)]">{label}</p><p className={`mt-2 text-2xl font-black ${primary?"theme-primary":""}`}>{value}</p><p className="mt-1 text-[9px] text-[var(--school-muted)]">{note}</p></div>}
function Info({label,value}:{label:string;value:string}){return <div className="rounded-xl border border-[var(--school-border)] bg-[var(--school-surface)] p-3"><p className="text-[8px] font-black uppercase text-[var(--school-muted)]">{label}</p><p className="mt-1 truncate text-[10px] font-black theme-primary">{value}</p></div>}
function Empty({text}:{text:string}){return <div className="rounded-xl border border-dashed border-[var(--school-border)] p-8 text-center text-[10px] text-[var(--school-muted)]">{text}</div>}
function status(v?:string|null){return v?v.replace(/_/g," ").replace(/\b\w/g,c=>c.toUpperCase()):"Updated"}
function date(v:string){const d=new Date(v);return Number.isNaN(d.getTime())?v:new Intl.DateTimeFormat("en-GB",{day:"2-digit",month:"short",hour:"2-digit",minute:"2-digit",hour12:true,timeZone:"Asia/Dhaka"}).format(d)}
