"use client";

import Link from "next/link";
import { ownerModules, ownerLeafCount } from "./ownerAdminNavigation";

type ActivityItem = { id: string; module: string; action: string; reference?: string | null; detail?: string | null; status?: string | null; createdAt: string };

export default function OwnerCommandCenterV2({ fullName, email, roleName, activityItems }: { fullName: string | null; email: string | null; roleName: string; activityItems: ActivityItem[] }) {
  const pending = activityItems.filter(i => ["pending", "submitted", "awaiting", "requested"].some(s => (i.status || "").toLowerCase().includes(s)));
  return <div className="space-y-6">
    <section className="rounded-3xl border border-[var(--school-border)] bg-[var(--school-surface)] p-6 shadow-sm md:p-8">
      <div className="flex flex-col gap-6 lg:flex-row lg:items-end lg:justify-between"><div><p className="text-[9px] font-black uppercase tracking-[.2em] theme-primary">Super Admin / Owner Command Center</p><h1 className="mt-2 text-3xl font-black tracking-tight md:text-4xl">Welcome, {fullName || "C.T. Model School Administrator"}</h1><p className="mt-2 max-w-3xl text-sm leading-6 text-[var(--school-muted)]">One unified school administration workspace. Every branch uses the same owner shell while existing database workflows remain intact.</p></div><div className="rounded-2xl border border-[var(--school-border)] bg-[var(--school-background)] px-5 py-4"><p className="text-[9px] font-black uppercase tracking-[.16em] text-[var(--school-muted)]">Role</p><p className="mt-1 text-sm font-black capitalize">{roleName.replace(/_/g, " ")}</p><p className="mt-1 text-[10px] text-[var(--school-muted)]">{email || ""}</p></div></div>
    </section>
    <section className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4"><div className="rounded-2xl border border-[var(--school-border)] bg-[var(--school-surface)] p-5"><p className="text-[9px] uppercase tracking-wider text-[var(--school-muted)]">Modules</p><p className="mt-1 text-2xl font-black">{ownerModules.length}</p></div><div className="rounded-2xl border border-[var(--school-border)] bg-[var(--school-surface)] p-5"><p className="text-[9px] uppercase tracking-wider text-[var(--school-muted)]">Action Leaves</p><p className="mt-1 text-2xl font-black">{ownerLeafCount}</p></div><Link href="/admin?view=pending" className="rounded-2xl border border-[var(--school-border)] bg-[var(--school-surface)] p-5 hover:bg-[var(--school-primary-soft)]"><p className="text-[9px] uppercase tracking-wider text-[var(--school-muted)]">Pending</p><p className="mt-1 text-2xl font-black">{pending.length}</p></Link><Link href="/admin?view=activity" className="rounded-2xl border border-[var(--school-border)] bg-[var(--school-surface)] p-5 hover:bg-[var(--school-primary-soft)]"><p className="text-[9px] uppercase tracking-wider text-[var(--school-muted)]">Live Activity</p><p className="mt-1 text-2xl font-black">{activityItems.length}</p></Link></section>
    <section className="grid gap-5 lg:grid-cols-2 xl:grid-cols-3">{ownerModules.map(module => <article key={module.code} className="rounded-3xl border border-[var(--school-border)] bg-[var(--school-surface)] p-5 shadow-sm"><div className="flex items-start justify-between gap-3"><div><p className="text-[9px] font-black uppercase tracking-widest theme-primary">{module.code} · Module</p><h2 className="mt-1 text-xl font-black">{module.title}</h2></div><span className="rounded-full border border-[var(--school-border)] px-2 py-1 text-[9px] font-black">{module.groups.reduce((n,g)=>n+(g.actions?.length||1),0)} actions</span></div><p className="mt-2 text-xs leading-5 text-[var(--school-muted)]">{module.description}</p><div className="mt-4 space-y-2">{module.groups.map(group => group.actions?.length ? <div key={group.label} className="rounded-xl bg-[var(--school-background)] p-2.5"><p className="text-[10px] font-black">{group.label}</p><div className="mt-1 grid gap-1 sm:grid-cols-2">{group.actions.map(action => <Link key={action.label} href={action.href} className="rounded-lg px-2 py-1.5 text-[9px] text-[var(--school-muted)] hover:bg-[var(--school-surface)] hover:theme-primary">{action.label}</Link>)}</div></div> : <Link key={group.label} href={group.href || "/admin"} className="block rounded-xl bg-[var(--school-background)] px-3 py-2 text-[10px] font-semibold hover:bg-[var(--school-primary-soft)] hover:theme-primary">{group.label}</Link>)}</div></article>)}</section>
  </div>;
}
