"use client";

import Link from "next/link";
import { useRouter } from "next/navigation";
import { ownerModules } from "./ownerAdminNavigation";

type ActivityItem = { id: string; module: string; action: string; reference?: string | null; detail?: string | null; status?: string | null; createdAt: string };
type OwnerMetrics = { students: number; parents: number; teachers: number; staff: number; inventoryItems: number; lowStockItems: number; pendingSr: number; pendingPr: number; pendingPo: number; pendingBills: number; pendingStudentAdmission: number; pendingParentRegistration: number; pendingPayroll: number; totalOutstandingBills: number; totalFeeDue: number };
const money = (value: number) => `৳${value.toLocaleString("en-BD", { maximumFractionDigits: 2 })}`;
const actionCount = (module: (typeof ownerModules)[number]) => module.groups.reduce((n, group) => n + (group.actions?.length || 1), 0);

export default function OwnerCommandCenterV2({ fullName, email, roleName, activityItems, metrics }: { fullName: string | null; email: string | null; roleName: string; activityItems: ActivityItem[]; metrics: OwnerMetrics }) {
 const router=useRouter();
 const pending=metrics.pendingSr+metrics.pendingPr+metrics.pendingPo+metrics.pendingBills+metrics.pendingStudentAdmission+metrics.pendingParentRegistration+metrics.pendingPayroll;
 const people=metrics.students+metrics.parents+metrics.teachers+metrics.staff;
 const attention=[
  ["Service Requests",metrics.pendingSr,"/admin/item-sr"],["Purchase Requests",metrics.pendingPr,"/admin/inventory/procurement?tab=pr"],["Purchase Orders",metrics.pendingPo,"/admin/inventory/procurement?tab=po"],["Bill Payments",metrics.pendingBills,"/admin/accounts/bill-payments"],["Admissions",metrics.pendingStudentAdmission,"/admin/students"],["Parent Requests",metrics.pendingParentRegistration,"/admin/parents"],["Payroll",metrics.pendingPayroll,"/admin/hr"],
 ].filter(([,count])=>Number(count)>0);
 return <div className="space-y-6">
  <section className="overflow-hidden rounded-[2rem] border border-[var(--school-border)] bg-[var(--school-surface)] shadow-sm"><div className="bg-[var(--school-primary-soft)] p-6 md:p-8"><div className="flex flex-col gap-6 lg:flex-row lg:items-end lg:justify-between"><div><p className="text-[9px] font-black uppercase tracking-[.22em] theme-primary">Super Admin · Owner Dashboard</p><h1 className="mt-2 text-3xl font-black tracking-tight md:text-4xl">Good to see you, {fullName||"Administrator"}</h1><p className="mt-2 max-w-2xl text-sm leading-6 text-[var(--school-muted)]">A live command center for the school. Follow attention items, review activity, and open any management workspace without leaving the unified Admin shell.</p></div><div className="flex flex-wrap gap-2"><button onClick={()=>router.refresh()} className="rounded-xl border border-[var(--school-border)] bg-[var(--school-surface)] px-4 py-2.5 text-[10px] font-black shadow-sm">Refresh data</button><div className="rounded-xl border border-[var(--school-border)] bg-[var(--school-surface)] px-4 py-2.5"><p className="text-[8px] font-black uppercase tracking-widest text-[var(--school-muted)]">Access</p><p className="mt-0.5 text-xs font-black capitalize">{roleName.replace(/_/g," ")}</p></div></div></div></div></section>
  <section className="grid gap-3 sm:grid-cols-2 xl:grid-cols-4">{[["Students",metrics.students,"/admin/students"],["People",people,"/admin/members"],["Inventory",metrics.inventoryItems,"/admin/inventory"],["Needs Attention",pending,"/admin?view=pending"]].map(([label,value,href],i)=><Link href={href as string} key={label as string} className={`group rounded-2xl border p-5 transition ${i===3?"border-[var(--school-primary-border)] bg-[var(--school-primary-soft)]":"border-[var(--school-border)] bg-[var(--school-surface)] hover:bg-[var(--school-primary-soft)]"}`}><div className="flex items-center justify-between"><p className="text-[9px] font-black uppercase tracking-wider text-[var(--school-muted)]">{label as string}</p><span className="text-xs theme-primary">↗</span></div><p className="mt-2 text-3xl font-black">{value as number}</p>{label==="Inventory"&&<p className="mt-1 text-[10px] text-[var(--school-muted)]">{metrics.lowStockItems} low-stock</p>}{label==="People"&&<p className="mt-1 text-[10px] text-[var(--school-muted)]">{metrics.teachers} teachers · {metrics.staff} staff</p>}{label==="Needs Attention"&&<p className="mt-1 text-[10px] text-[var(--school-muted)]">Live workflow queue</p>}</Link>)}</section>
  <section className="grid gap-4 lg:grid-cols-[1.4fr_.8fr]">
   <div className="rounded-3xl border border-[var(--school-border)] bg-[var(--school-surface)] p-5 shadow-sm md:p-6"><div className="flex items-end justify-between gap-3"><div><p className="text-[9px] font-black uppercase tracking-widest theme-primary">Action Center</p><h2 className="mt-1 text-xl font-black">Needs your attention</h2></div><Link href="/admin?view=pending" className="text-[10px] font-black theme-primary">Open queue →</Link></div>{attention.length?<div className="mt-4 grid gap-2 sm:grid-cols-2">{attention.map(([label,count,href])=><Link href={href as string} key={label as string} className="flex items-center justify-between rounded-xl bg-[var(--school-background)] p-3 transition hover:bg-[var(--school-primary-soft)]"><div><p className="text-xs font-black">{label as string}</p><p className="mt-0.5 text-[9px] text-[var(--school-muted)]">Requires review or processing</p></div><span className="rounded-full bg-[var(--school-surface)] px-2.5 py-1 text-xs font-black theme-primary">{count as number}</span></Link>)}</div>:<div className="mt-4 rounded-xl border border-dashed border-[var(--school-border)] p-8 text-center"><p className="text-sm font-black">Everything is clear</p><p className="mt-1 text-[10px] text-[var(--school-muted)]">No live pending workflow requires attention.</p></div>}</div>
   <div className="rounded-3xl border border-[var(--school-border)] bg-[var(--school-surface)] p-5 shadow-sm md:p-6"><p className="text-[9px] font-black uppercase tracking-widest theme-primary">Finance snapshot</p><h2 className="mt-1 text-xl font-black">Money requiring visibility</h2><div className="mt-4 space-y-2"><Link href="/admin/accounts/bill-payments" className="block rounded-xl bg-[var(--school-background)] p-4 hover:bg-[var(--school-primary-soft)]"><p className="text-[9px] uppercase tracking-wider text-[var(--school-muted)]">Outstanding bills</p><p className="mt-1 text-xl font-black">{money(metrics.totalOutstandingBills)}</p></Link><Link href="/admin/accounts/fees" className="block rounded-xl bg-[var(--school-background)] p-4 hover:bg-[var(--school-primary-soft)]"><p className="text-[9px] uppercase tracking-wider text-[var(--school-muted)]">Student fee due</p><p className="mt-1 text-xl font-black">{money(metrics.totalFeeDue)}</p></Link></div></div>
  </section>
  <section className="rounded-3xl border border-[var(--school-border)] bg-[var(--school-surface)] p-5 shadow-sm md:p-6"><div className="flex items-end justify-between gap-3"><div><p className="text-[9px] font-black uppercase tracking-widest theme-primary">Live workflow</p><h2 className="mt-1 text-xl font-black">Recent activity</h2></div><Link href="/admin?view=activity" className="text-[10px] font-black theme-primary">View all →</Link></div>{activityItems.length?<div className="mt-3 divide-y divide-[var(--school-border)]">{activityItems.slice(0,8).map(item=><div key={item.id} className="flex flex-col gap-2 py-3 sm:flex-row sm:items-center sm:justify-between"><div className="min-w-0"><p className="text-xs font-bold">{item.action}</p><p className="truncate text-[10px] text-[var(--school-muted)]">{item.module}{item.reference?` · ${item.reference}`:""}{item.detail?` · ${item.detail}`:""}</p></div><span className="w-fit rounded-full border border-[var(--school-border)] px-2 py-1 text-[9px] font-bold capitalize">{item.status||"recorded"}</span></div>)}</div>:<p className="mt-4 rounded-xl bg-[var(--school-background)] p-4 text-xs text-[var(--school-muted)]">No recent activity records found.</p>}</section>
  <section><div className="mb-3 flex items-end justify-between"><div><p className="text-[9px] font-black uppercase tracking-widest theme-primary">Owner workspace map</p><h2 className="mt-1 text-xl font-black">All management areas</h2></div><p className="text-[10px] text-[var(--school-muted)]">{ownerModules.length} modules</p></div><div className="grid gap-4 lg:grid-cols-2 xl:grid-cols-3">{ownerModules.map(module=><article key={module.code} className="rounded-3xl border border-[var(--school-border)] bg-[var(--school-surface)] p-5 shadow-sm"><div className="flex items-start justify-between gap-3"><div><p className="text-[9px] font-black uppercase tracking-widest theme-primary">{module.code} · Module</p><h3 className="mt-1 text-lg font-black">{module.title}</h3></div><span className="rounded-full bg-[var(--school-background)] px-2 py-1 text-[9px] font-black">{actionCount(module)} actions</span></div><p className="mt-2 text-[10px] leading-5 text-[var(--school-muted)]">{module.description}</p><div className="mt-4 space-y-2">{module.groups.map(group=>group.actions?.length?<div key={group.label} className="rounded-xl bg-[var(--school-background)] p-2.5"><p className="text-[10px] font-black">{group.label}</p><div className="mt-1 grid grid-cols-2 gap-1">{group.actions.map(action=><Link href={action.href} key={action.label} className="rounded-lg px-2 py-1.5 text-[9px] text-[var(--school-muted)] hover:bg-[var(--school-surface)] hover:theme-primary">{action.label}</Link>)}</div></div>:<Link href={group.href||"/admin"} key={group.label} className="flex items-center justify-between rounded-xl bg-[var(--school-background)] px-3 py-2.5 text-[10px] font-semibold hover:bg-[var(--school-primary-soft)]"><span>{group.label}</span><span className="theme-primary">→</span></Link>)}</div></article>)}</div></section>
 </div>;
}
