"use client";

import { useEffect, useMemo, useState } from "react";
import { createClient } from "@/lib/supabase/client";

type Parent = { id:string; parent_id:string; full_name:string; relation_type:string; phone:string; email:string|null; nid:string|null; address:string; is_active:boolean; created_at:string };
type Link = { id:string; student_id:string; parent_id:string; relationship:string; is_primary:boolean; created_at:string };
type ParentRequest = { id:string; registration_no:string; full_name:string; relation_type:string; phone:string; email:string|null; nid:string|null; occupation:string|null; address:string; status:string; parent_id:string|null; created_at:string; admin_note:string|null };
type StudentRequest = { id:string; registration_no:string; parent_id:string; registration_source:string; requested_student_id:string|null; academic_year:string; admission_class:string; section:string|null; student_name:string; student_name_bn:string|null; status:string; student_id:string|null; created_at:string; admin_note:string|null };
type Student = { id:string; student_id:string; full_name:string; admission_class:string; section:string|null; status:string };
type Detail = { kind:"parent"|"link"|"parentRequest"|"studentRequest"; value: Parent|Link|ParentRequest|StudentRequest }|null;

const date = (v:string) => new Intl.DateTimeFormat("en-GB",{day:"2-digit",month:"short",year:"numeric",timeZone:"Asia/Dhaka"}).format(new Date(v));
const statusText = (v:string) => v.replace(/_/g," ").replace(/\b\w/g,c=>c.toUpperCase());

export default function SuperAdminParentWorkspace({section}:{section:"Parent Accounts"|"Child Binding"|"Approvals"|"Parent Records"}) {
 const supabase=useMemo(()=>createClient(),[]);
 const [parents,setParents]=useState<Parent[]>([]),[links,setLinks]=useState<Link[]>([]),[students,setStudents]=useState<Student[]>([]),[parentRequests,setParentRequests]=useState<ParentRequest[]>([]),[studentRequests,setStudentRequests]=useState<StudentRequest[]>([]);
 const [loading,setLoading]=useState(true),[busy,setBusy]=useState<string|null>(null),[error,setError]=useState(""),[message,setMessage]=useState(""),[searchId,setSearchId]=useState(""),[searchName,setSearchName]=useState(""),[searchContact,setSearchContact]=useState(""),[searchOther,setSearchOther]=useState(""),[filter,setFilter]=useState("all"),[detail,setDetail]=useState<Detail>(null);
 async function load(){setLoading(true);setError("");const [p,l,s,pr,sr]=await Promise.all([supabase.from("parents").select("id,parent_id,full_name,relation_type,phone,email,nid,address,is_active,created_at").order("created_at",{ascending:false}),supabase.from("student_parent_links").select("id,student_id,parent_id,relationship,is_primary,created_at").order("created_at",{ascending:false}),supabase.from("students").select("id,student_id,full_name,admission_class,section,status").order("created_at",{ascending:false}),supabase.rpc("admin_list_parent_registrations",{p_status:null}),supabase.rpc("admin_list_parent_student_registrations",{p_status:null})]);const es=[p.error,l.error,s.error,pr.error,sr.error].filter(Boolean);if(es.length)setError(es.map(e=>e!.message).join(" • "));setParents((p.data??[]) as Parent[]);setLinks((l.data??[]) as Link[]);setStudents((s.data??[]) as Student[]);setParentRequests((pr.data??[]) as ParentRequest[]);setStudentRequests((sr.data??[]) as StudentRequest[]);setLoading(false)}
 useEffect(()=>{void load()},[]);
 useEffect(()=>{setSearchId("");setSearchName("");setSearchContact("");setSearchOther("");setFilter("all");setDetail(null)},[section]);
 async function approveParent(id:string){setBusy(id);setError("");setMessage("");const {data,error:e}=await supabase.rpc("parent_approve_registration",{p_request_id:id,p_admin_note:null});if(e)setError(e.message);else setMessage(`Parent approved. Permanent Parent ID: ${(data as {parent_id:string}).parent_id}`);setBusy(null);await load()}
 async function rejectParent(id:string){const note=window.prompt("Reason / note (optional):","");if(note===null)return;setBusy(id);setError("");setMessage("");const {error:e}=await supabase.rpc("parent_reject_registration",{p_request_id:id,p_note:note||null});if(e)setError(e.message);else setMessage("Parent registration rejected.");setBusy(null);await load()}
 async function approveStudent(id:string){setBusy(id);setError("");setMessage("");const {data,error:e}=await supabase.rpc("admin_approve_parent_student_registration",{p_request_id:id,p_admin_note:null});if(e)setError(e.message);else{const r=data as {student_id:string;action?:string};setMessage(r.action==="bound"?`Student approved and bound to Student ID: ${r.student_id}`:`Student approved and Student ID created: ${r.student_id}`)}setBusy(null);await load()}
 async function rejectStudent(id:string){const note=window.prompt("Reason / note (optional):","");if(note===null)return;setBusy(id);setError("");setMessage("");const {error:e}=await supabase.rpc("admin_reject_parent_student_registration",{p_request_id:id,p_note:note||null});if(e)setError(e.message);else setMessage("Child registration rejected.");setBusy(null);await load()}
 const qId=searchId.trim().toLowerCase(),qName=searchName.trim().toLowerCase(),qContact=searchContact.trim().toLowerCase(),qOther=searchOther.trim().toLowerCase();
 const contains=(value:string,q:string)=>!q||(value||"").toLowerCase().includes(q);
 const multiMatch=(idValues:string[],nameValues:string[],contactValues:string[],otherValues:string[])=>contains(idValues.join(" "),qId)&&contains(nameValues.join(" "),qName)&&contains(contactValues.join(" "),qContact)&&contains(otherValues.join(" "),qOther);
 const hasSearch=!!(qId||qName||qContact||qOther);
 const activeParents=parents.filter(p=>p.is_active), pendingParents=parentRequests.filter(r=>!["approved","rejected"].includes(r.status)),pendingStudents=studentRequests.filter(r=>!["approved","rejected"].includes(r.status));
 const filteredParents=activeParents.filter(p=>multiMatch([p.parent_id],[p.full_name],[p.phone],[p.email||"",p.nid||"",p.relation_type,p.address])&&(filter==="all"||filter==="active"));
 const filteredLinks=links.filter(l=>{const p=parents.find(x=>x.id===l.parent_id),s=students.find(x=>x.id===l.student_id);return multiMatch([p?.parent_id||"",l.parent_id,s?.student_id||"",l.student_id],[p?.full_name||"",s?.full_name||""],[p?.phone||""],[p?.email||"",p?.nid||"",l.relationship,s?.admission_class||"",s?.section||""])&&(filter==="all"||(filter==="primary"&&l.is_primary)||(filter==="secondary"&&!l.is_primary))});
 const filteredParentRequests=parentRequests.filter(r=>multiMatch([r.registration_no,r.parent_id||""],[r.full_name],[r.phone],[r.email||"",r.nid||"",r.relation_type,r.status,r.address])&&(filter==="all"||r.status===filter));
 const filteredStudentRequests=studentRequests.filter(r=>multiMatch([r.registration_no,r.student_id||"",r.requested_student_id||"",r.parent_id],[r.student_name,r.student_name_bn||""],[r.parent_id],[r.academic_year,r.admission_class,r.section||"",r.registration_source,r.status])&&(filter==="all"||r.status===filter));
 const childrenFor=(pid:string)=>links.filter(l=>l.parent_id===pid).map(l=>({l,s:students.find(x=>x.id===l.student_id)}));
 const clearSearch=()=>{setSearchId("");setSearchName("");setSearchContact("");setSearchOther("");setFilter("all")};
 if(loading)return <div className="mt-6 rounded-2xl border border-dashed border-[var(--school-border)] bg-[var(--school-background)] p-10 text-center text-sm text-[var(--school-muted)]">Loading existing database records...</div>;
 const filterOptions=section==="Child Binding"?["all","primary","secondary"]:section==="Approvals"?["all","pending","reviewing","approved","rejected"]:["all","active"];
 const fieldLabels=section==="Child Binding"?{id:"Parent / Student ID",name:"Parent / Student Name",contact:"Parent Phone",other:"Relationship / Class"}:section==="Approvals"?{id:"Registration / ID",name:"Parent / Student Name",contact:"Phone / Parent ID",other:"Email / NID / Class / Status"}:{id:"ID",name:"Name",contact:"Phone",other:"Email / NID / Address"};
 return <div className="mt-6 space-y-4">
  {error&&<div className="rounded-2xl border border-red-200 bg-red-50 px-4 py-3 text-sm font-bold text-red-700">{error}</div>}{message&&<div className="rounded-2xl border border-[var(--school-primary-border)] bg-[var(--school-primary-soft)] px-4 py-3 text-sm font-bold theme-primary">{message}</div>}
  <div className="sticky top-2 z-20 rounded-2xl border border-[var(--school-border)] bg-[var(--school-surface)]/95 p-3 shadow-sm backdrop-blur sm:p-4">
   <div className="mb-2 flex items-center justify-between gap-3"><div><p className="text-[10px] font-black uppercase tracking-[0.14em] theme-primary">Multi Search & Filter</p><p className="mt-0.5 text-[9px] font-semibold text-[var(--school-muted)]">Fill one or multiple fields. Multiple fields work together.</p></div>{hasSearch&&<span className="rounded-full bg-[var(--school-primary-soft)] px-2.5 py-1 text-[8px] font-black theme-primary">SEARCH ACTIVE</span>}</div>
   <div className="grid grid-cols-1 gap-2 sm:grid-cols-2 xl:grid-cols-4">
    <SearchField label={fieldLabels.id} value={searchId} onChange={setSearchId} placeholder={`Search by ${fieldLabels.id.toLowerCase()}...`}/>
    <SearchField label={fieldLabels.name} value={searchName} onChange={setSearchName} placeholder={`Search by ${fieldLabels.name.toLowerCase()}...`}/>
    <SearchField label={fieldLabels.contact} value={searchContact} onChange={setSearchContact} placeholder={`Search by ${fieldLabels.contact.toLowerCase()}...`}/>
    <SearchField label={fieldLabels.other} value={searchOther} onChange={setSearchOther} placeholder={`Search ${fieldLabels.other.toLowerCase()}...`}/>
   </div>
   <div className="mt-2 flex flex-col gap-2 sm:flex-row"><select aria-label="Filter" value={filter} onChange={e=>setFilter(e.target.value)} className="min-w-0 flex-1 rounded-xl border border-[var(--school-border)] bg-[var(--school-background)] px-3 py-2.5 text-xs font-bold text-[var(--school-text)]">{filterOptions.map(x=><option key={x} value={x}>{x==="all"?"All Records":statusText(x)}</option>)}</select><button type="button" onClick={clearSearch} className="rounded-xl border border-[var(--school-border)] px-4 py-2.5 text-xs font-black text-[var(--school-muted)] hover:border-[var(--school-primary-border)] hover:text-[var(--school-text)]">Reset All</button></div>
   <p className="mt-2 text-[9px] font-black uppercase tracking-[0.14em] text-[var(--school-muted)]">Locked workspace search & filter · {section}</p>
  </div>
  {section==="Parent Accounts"&&<SectionHead title="Parent Accounts" note="Live active parent accounts · click a compact card for full details" count={filteredParents.length}/>} 
  {section==="Child Binding"&&<SectionHead title="Child Binding" note="Live Parent–Student relationship records · click a card for full details" count={filteredLinks.length}/>} 
  {section==="Approvals"&&<SectionHead title="Approvals" note="Existing registration requests requiring review or already processed" count={filteredParentRequests.length+filteredStudentRequests.length}/>} 
  {section==="Parent Records"&&<SectionHead title="Parent Records" note="Complete parent view with current child-binding count" count={filteredParents.length}/>} 
  {section==="Parent Accounts"&&<div className="grid grid-cols-2 gap-2 sm:grid-cols-3 lg:grid-cols-4 xl:grid-cols-5">{filteredParents.map(p=><CompactCard key={p.id} id={p.parent_id} title={p.full_name} meta={`${p.relation_type} · ${p.phone}`} badge="ACTIVE" onClick={()=>setDetail({kind:"parent",value:p})}/>)}</div>}
  {section==="Parent Records"&&<div className="grid grid-cols-2 gap-2 sm:grid-cols-3 lg:grid-cols-4 xl:grid-cols-5">{filteredParents.map(p=><CompactCard key={p.id} id={p.parent_id} title={p.full_name} meta={`${childrenFor(p.id).length} child${childrenFor(p.id).length===1?"":"ren"}`} badge={p.is_active?"ACTIVE":"INACTIVE"} onClick={()=>setDetail({kind:"parent",value:p})}/>)}</div>}
  {section==="Child Binding"&&<div className="grid grid-cols-2 gap-2 sm:grid-cols-3 lg:grid-cols-4 xl:grid-cols-5">{filteredLinks.map(l=>{const p=parents.find(x=>x.id===l.parent_id),s=students.find(x=>x.id===l.student_id);return <CompactCard key={l.id} id={p?.parent_id||l.parent_id} title={p?.full_name||"Unknown parent"} meta={`${s?.student_id||l.student_id} · ${s?.full_name||"Unknown student"}`} badge={l.is_primary?"PRIMARY":"LINKED"} onClick={()=>setDetail({kind:"link",value:l})}/>})}</div>}
  {section==="Approvals"&&<div className="space-y-4"><div><p className="mb-2 text-[10px] font-black uppercase tracking-wider theme-primary">Parent registrations</p><div className="grid grid-cols-2 gap-2 sm:grid-cols-3 lg:grid-cols-4 xl:grid-cols-5">{filteredParentRequests.map(r=><CompactCard key={r.id} id={r.registration_no} title={r.full_name} meta={`${r.relation_type} · ${r.phone}`} badge={statusText(r.status)} onClick={()=>setDetail({kind:"parentRequest",value:r})}/>)}</div></div><div><p className="mb-2 text-[10px] font-black uppercase tracking-wider theme-primary">Child registrations</p><div className="grid grid-cols-2 gap-2 sm:grid-cols-3 lg:grid-cols-4 xl:grid-cols-5">{filteredStudentRequests.map(r=><CompactCard key={r.id} id={r.registration_no} title={r.student_name} meta={`${r.requested_student_id||"New Student"} · Class ${r.admission_class}`} badge={statusText(r.status)} onClick={()=>setDetail({kind:"studentRequest",value:r})}/>)}</div></div></div>}
  {!filteredParents.length&&!filteredLinks.length&&!filteredParentRequests.length&&!filteredStudentRequests.length&&<Empty text={hasSearch?"No records match the current search fields and filter.":"No records found in the database."}/>} 
  {detail&&<DetailModal detail={detail} parents={parents} students={students} links={links} busy={busy} onClose={()=>setDetail(null)} onApproveParent={approveParent} onRejectParent={rejectParent} onApproveStudent={approveStudent} onRejectStudent={rejectStudent}/>} 
 </div>;
}

function SearchField({label,value,onChange,placeholder}:{label:string;value:string;onChange:(value:string)=>void;placeholder:string}){return <label className="block min-w-0"><span className="mb-1 block px-1 text-[8px] font-black uppercase tracking-[0.12em] text-[var(--school-muted)]">{label}</span><div className="relative"><input value={value} onChange={e=>onChange(e.target.value)} placeholder={placeholder} className="w-full rounded-xl border border-[var(--school-border)] bg-[var(--school-background)] px-3 py-2.5 pr-8 text-xs font-semibold text-[var(--school-text)] outline-none placeholder:text-[var(--school-muted)] focus:border-[var(--school-primary-border)]"/>{value&&<button type="button" aria-label={`Clear ${label}`} onClick={()=>onChange("")} className="absolute right-2 top-1/2 -translate-y-1/2 text-sm font-black text-[var(--school-muted)] hover:text-[var(--school-text)]">×</button>}</div></label>}
function SectionHead({title,note,count}:{title:string;note:string;count:number}){return <div className="rounded-2xl border border-[var(--school-border)] bg-[var(--school-primary-soft)] px-4 py-4"><div className="flex items-center justify-between gap-3"><div><p className="text-[10px] font-black uppercase tracking-[0.16em] theme-primary">Live database</p><h2 className="mt-1 text-xl font-black text-[var(--school-text)]">{title}</h2><p className="mt-1 text-xs text-[var(--school-muted)]">{note}</p></div><span className="rounded-full border border-[var(--school-primary-border)] bg-[var(--school-surface)] px-3 py-1.5 text-[10px] font-black theme-primary">{count}</span></div></div>}
function CompactCard({id,title,meta,badge,onClick}:{id:string;title:string;meta:string;badge:string;onClick:()=>void}){return <button type="button" onClick={onClick} className="min-w-0 rounded-xl border border-[var(--school-border)] bg-[var(--school-surface)] p-3 text-left transition hover:border-[var(--school-primary-border)] hover:bg-[var(--school-primary-soft)]"><div className="flex items-center justify-between gap-2"><p className="truncate text-[9px] font-black uppercase tracking-wider theme-primary">{id}</p><span className="shrink-0 rounded-full bg-[var(--school-primary-soft)] px-1.5 py-0.5 text-[7px] font-black theme-primary">{badge}</span></div><p className="mt-1 truncate text-xs font-black text-[var(--school-text)]">{title}</p><p className="mt-1 truncate text-[9px] font-semibold text-[var(--school-muted)]">{meta}</p><p className="mt-2 text-[8px] font-black theme-primary">VIEW DETAILS ›</p></button>}
function DetailModal({detail,parents,students,links,busy,onClose,onApproveParent,onRejectParent,onApproveStudent,onRejectStudent}:{detail:Detail;parents:Parent[];students:Student[];links:Link[];busy:string|null;onClose:()=>void;onApproveParent:(id:string)=>void;onRejectParent:(id:string)=>void;onApproveStudent:(id:string)=>void;onRejectStudent:(id:string)=>void}){
 useEffect(()=>{const f=(e:KeyboardEvent)=>{if(e.key==="Escape")onClose()};document.addEventListener("keydown",f);return()=>document.removeEventListener("keydown",f)},[onClose]);if(!detail)return null;
 const v=detail.value as any;let title="Details",rows:[string,string][]=[];let actions=null;
 if(detail.kind==="parent"){const p=v as Parent;const count=links.filter(l=>l.parent_id===p.id).length;title=p.full_name;rows=[["Parent ID",p.parent_id],["Relation",p.relation_type],["Phone",p.phone],["Email",p.email||"-"],["NID",p.nid||"-"],["Address",p.address||"-"],["Children",String(count)],["Created",date(p.created_at)],["Status",p.is_active?"Active":"Inactive"]]}
 if(detail.kind==="link"){const l=v as Link,p=parents.find(x=>x.id===l.parent_id),s=students.find(x=>x.id===l.student_id);title="Parent–Student Binding";rows=[["Parent ID",p?.parent_id||l.parent_id],["Parent",p?.full_name||"Unknown"],["Student ID",s?.student_id||l.student_id],["Student",s?.full_name||"Unknown"],["Class",s?.admission_class||"-"],["Section",s?.section||"-"],["Relationship",l.relationship||"-"],["Primary",l.is_primary?"Yes":"No"],["Created",date(l.created_at)]]}
 if(detail.kind==="parentRequest"){const r=v as ParentRequest;title=r.full_name;rows=[["Registration",r.registration_no],["Name",r.full_name],["Relation",r.relation_type],["Phone",r.phone],["Email",r.email||"-"],["NID",r.nid||"-"],["Occupation",r.occupation||"-"],["Address",r.address||"-"],["Status",statusText(r.status)],["Created",date(r.created_at)]];if(!["approved","rejected"].includes(r.status))actions=<div className="flex gap-2"><button disabled={busy===r.id} onClick={()=>{onClose();onApproveParent(r.id)}} className="rounded-xl px-4 py-2.5 text-xs font-black theme-primary-bg">Approve</button><button disabled={busy===r.id} onClick={()=>{onClose();onRejectParent(r.id)}} className="rounded-xl border border-red-200 px-4 py-2.5 text-xs font-black text-red-600">Reject</button></div>}
 if(detail.kind==="studentRequest"){const r=v as StudentRequest;title=r.student_name;const p=parents.find(x=>x.id===r.parent_id);rows=[["Registration",r.registration_no],["Student",r.student_name],["Student ID",r.student_id||r.requested_student_id||"Not assigned"],["Parent",p?.full_name||r.parent_id],["Class",r.admission_class],["Section",r.section||"-"],["Academic Year",r.academic_year],["Source",statusText(r.registration_source)],["Status",statusText(r.status)],["Created",date(r.created_at)]];if(!["approved","rejected"].includes(r.status))actions=<div className="flex gap-2"><button disabled={busy===r.id} onClick={()=>{onClose();onApproveStudent(r.id)}} className="rounded-xl px-4 py-2.5 text-xs font-black theme-primary-bg">Approve</button><button disabled={busy===r.id} onClick={()=>{onClose();onRejectStudent(r.id)}} className="rounded-xl border border-red-200 px-4 py-2.5 text-xs font-black text-red-600">Reject</button></div>}
 return <div className="fixed inset-0 z-[100] grid place-items-center bg-black/35 p-4" role="dialog" aria-modal="true" onMouseDown={e=>{if(e.target===e.currentTarget)onClose()}}><div className="flex max-h-[88vh] w-full max-w-xl flex-col overflow-hidden rounded-2xl border border-[var(--school-border)] bg-[var(--school-surface)] shadow-2xl"><div className="flex items-start justify-between border-b border-[var(--school-border)] px-5 py-4"><div><p className="text-[9px] font-black uppercase tracking-[0.16em] theme-primary">Full details</p><h2 className="mt-1 text-xl font-black text-[var(--school-text)]">{title}</h2></div><button type="button" onClick={onClose} className="grid h-8 w-8 place-items-center rounded-full border border-[var(--school-border)] text-sm font-black text-[var(--school-muted)]">×</button></div><div className="overflow-y-auto p-5"><div className="grid gap-2 sm:grid-cols-2">{rows.map(([k,val])=><div key={k} className="rounded-xl border border-[var(--school-border)] bg-[var(--school-background)] p-3"><p className="text-[8px] font-black uppercase tracking-wider text-[var(--school-muted)]">{k}</p><p className="mt-1 break-words text-xs font-bold text-[var(--school-text)]">{val}</p></div>)}</div>{actions&&<div className="mt-4">{actions}</div>}</div></div></div>
}
function Empty({text}:{text:string}){return <div className="rounded-2xl border border-dashed border-[var(--school-border)] p-10 text-center text-sm text-[var(--school-muted)]">{text}</div>}
