"use client";
import { useEffect, useMemo, useState } from "react";
import { createClient } from "@/lib/supabase/client";

type Member={member_id:string;member_type:string;full_name:string;designation:string|null;department:string|null;subject:string|null;phone:string|null;email:string|null;is_active:boolean;status:string};
type Entry={id:string;voucher_no:string;entry_date:string;entry_type:string;category:string|null;party_id:string|null;party_name:string|null;total_amount:number;paid_amount:number;due_amount:number;due_date:string|null;payment_status:string;payment_method:string;reference_no:string|null;description:string|null};
type Form={entry_type:string;entry_date:string;category:string;party_type:string;party_id:string;party_name:string;total:string;paid:string;due_date:string;method:string;account:string;reference:string;notes:string};
const fresh=():Form=>({entry_type:"student_fee",entry_date:new Date().toISOString().slice(0,10),category:"",party_type:"",party_id:"",party_name:"",total:"",paid:"",due_date:"",method:"cash",account:"",reference:"",notes:""});
const money=(n:number)=>new Intl.NumberFormat("en-BD",{minimumFractionDigits:2,maximumFractionDigits:2}).format(n||0);
const days=(d:string|null)=>{if(!d)return null;const x=new Date(`${d}T00:00:00`);const t=new Date();t.setHours(0,0,0,0);return Math.ceil((x.getTime()-t.getTime())/86400000)};

export default function MemberAccounts({compact=false}:{compact?:boolean}){
 const supabase=useMemo(()=>createClient(),[]);const [summary,setSummary]=useState<any>(null);const [entries,setEntries]=useState<Entry[]>([]);const [loading,setLoading]=useState(true);const [error,setError]=useState("");
 const token=typeof window!=="undefined"?window.localStorage.getItem("ctms_store_token"):null;
 useEffect(()=>{if(!token)return;let alive=true;(async()=>{const [s,h]=await Promise.all([supabase.rpc("store_accounts_member_summary",{p_token:token}),supabase.rpc("store_accounts_member_history",{p_token:token})]);if(!alive)return;if(s.error||h.error)setError(s.error?.message||h.error?.message||"");else{setSummary(s.data);setEntries((h.data||[]) as Entry[])}setLoading(false)})();return()=>{alive=false}},[supabase,token]);
 if(loading)return <div className="mt-5 rounded-2xl border border-[var(--school-border)] p-5 text-xs text-[var(--school-muted)]">Loading account history...</div>;
 if(error)return <div className="mt-5 rounded-2xl border border-red-200 bg-red-50 p-5 text-xs text-red-700">{error}</div>;
 const next=summary?.next_due_date?days(summary.next_due_date):null;
 return <section className={`mt-5 rounded-2xl border border-[var(--school-border)] ${compact?"p-4":"p-5"}`}>
  <div className="flex flex-col gap-2 sm:flex-row sm:items-center sm:justify-between"><div><p className="text-[10px] font-black uppercase tracking-[0.15em] theme-primary">My Accounts</p><h3 className="mt-1 text-lg font-black">Payment & Due Status</h3></div><span className={`w-fit rounded-full px-3 py-1.5 text-[10px] font-black uppercase ${Number(summary?.due_amount||0)>0?"bg-amber-50 text-amber-700":"bg-emerald-50 text-emerald-700"}`}>{Number(summary?.due_amount||0)>0?"Due":"Paid"}</span></div>
  <div className="mt-4 grid gap-3 sm:grid-cols-2 lg:grid-cols-4"><div className="rounded-xl border border-[var(--school-border)] bg-[var(--school-primary-soft)] p-4"><p className="text-[10px] text-[var(--school-muted)]">Total</p><p className="mt-1 text-lg font-black">৳ {money(Number(summary?.total_amount||0))}</p></div><div className="rounded-xl border border-[var(--school-border)] bg-[var(--school-primary-soft)] p-4"><p className="text-[10px] text-[var(--school-muted)]">Paid</p><p className="mt-1 text-lg font-black theme-primary">৳ {money(Number(summary?.paid_amount||0))}</p></div><div className="rounded-xl border border-[var(--school-border)] bg-[var(--school-primary-soft)] p-4"><p className="text-[10px] text-[var(--school-muted)]">Due</p><p className="mt-1 text-lg font-black text-amber-700">৳ {money(Number(summary?.due_amount||0))}</p></div><div className="rounded-xl border border-[var(--school-border)] bg-[var(--school-primary-soft)] p-4"><p className="text-[10px] text-[var(--school-muted)]">Next Due</p><p className="mt-1 text-sm font-black">{summary?.next_due_date||"No pending due"}</p>{next!==null&&<p className="mt-1 text-[10px] font-bold text-amber-700">{next<0?`${Math.abs(next)} days overdue`:next===0?"Due today":`${next} days left`}</p>}</div></div>
  {entries.length>0&&<div className="mt-4 overflow-x-auto"><table className="w-full min-w-[850px] text-left text-xs"><thead><tr className="border-b border-[var(--school-border)] text-[10px] uppercase tracking-wider text-[var(--school-muted)]"><th className="p-2">Date</th><th className="p-2">Voucher</th><th className="p-2">Purpose</th><th className="p-2">Total</th><th className="p-2">Paid</th><th className="p-2">Due</th><th className="p-2">Pay By</th><th className="p-2">Status</th></tr></thead><tbody>{entries.map(e=><tr key={e.id} className="border-b border-[var(--school-border)]"><td className="p-2">{e.entry_date}</td><td className="p-2 font-bold">{e.voucher_no}</td><td className="p-2">{e.category||e.entry_type}</td><td className="p-2">৳ {money(Number(e.total_amount||0))}</td><td className="p-2 theme-primary">৳ {money(Number(e.paid_amount||0))}</td><td className="p-2 font-bold text-amber-700">৳ {money(Number(e.due_amount||0))}</td><td className="p-2">{e.due_date||"-"}</td><td className="p-2 font-black uppercase">{e.payment_status}</td></tr>)}</tbody></table></div>}
  {entries.length===0&&<p className="mt-4 rounded-xl border border-dashed border-[var(--school-border)] p-5 text-center text-xs text-[var(--school-muted)]">No Accounts entry has been linked to your ID yet.</p>}
 </section>
}

export function AccountsEntryForm({permissions}:{permissions:Record<string,boolean>}){
 const supabase=useMemo(()=>createClient(),[]);const [members,setMembers]=useState<Member[]>([]);const [form,setForm]=useState<Form>(fresh());const [open,setOpen]=useState(false);const [saving,setSaving]=useState(false);const [message,setMessage]=useState("");const [error,setError]=useState("");const token=typeof window!=="undefined"?window.localStorage.getItem("ctms_store_token"):null;
 const can=Boolean(permissions.dashboard||permissions.__all);const due=Math.max(0,Number(form.total||0)-Number(form.paid||0));const status=Number(form.total||0)>0&&Number(form.paid||0)>=Number(form.total||0)?"paid":Number(form.paid||0)>0?"partial":"due";
 useEffect(()=>{if(token&&can)supabase.rpc("store_accounts_list_members",{p_token:token}).then(({data,error:e})=>{if(e)setError(e.message);else setMembers((data||[]) as Member[])})},[can,supabase,token]);
 const pick=(id:string)=>{const m=members.find(x=>x.member_id===id);if(m)setForm(f=>({...f,party_id:m.member_id,party_type:m.member_type,party_name:m.full_name}))};
 async function save(ev:React.FormEvent){ev.preventDefault();if(!token||saving)return;const total=Number(form.total||0),paid=Number(form.paid||0);setError("");if(total<=0)return setError("Total payable amount must be greater than zero.");if(paid<0||paid>total)return setError("Paid amount cannot be greater than total.");if(!form.party_id)return setError("Select a member and member ID.");if(due>0&&!form.due_date)return setError("Due date is required for an unpaid amount.");setSaving(true);const r=await supabase.rpc("store_accounts_save_entry_v2",{p_token:token,p_entry_type:form.entry_type,p_entry_date:form.entry_date,p_category:form.category,p_party_type:form.party_type,p_party_id:form.party_id,p_party_name:form.party_name,p_total_amount:total,p_paid_amount:paid,p_due_date:form.due_date||null,p_payment_method:form.method,p_account_name:form.account,p_reference_no:form.reference,p_description:form.notes});setSaving(false);if(r.error)setError(r.error.message);else{setMessage(`Saved ${String(r.data?.voucher_no||"")} for ${form.party_id}.`);setOpen(false);setForm(fresh())}}
 if(!can)return null;
 return <><button type="button" onClick={()=>{setError("");setMessage("");setOpen(true)}} className="rounded-xl theme-primary-bg px-3 py-2 text-xs font-bold">+ Member Accounts Entry</button>{message&&<div className="mt-3 rounded-xl border border-[var(--school-primary-border)] bg-[var(--school-primary-soft)] p-3 text-xs font-semibold theme-primary">{message}</div>}{open&&<div className="fixed inset-0 z-[100] flex items-center justify-center bg-slate-950/50 p-3 sm:p-5" onMouseDown={e=>{if(e.target===e.currentTarget&&!saving)setOpen(false)}}><div className="flex max-h-[92vh] w-full max-w-4xl flex-col overflow-hidden rounded-2xl border border-[var(--school-border)] bg-[var(--school-surface)] shadow-2xl"><div className="flex items-center justify-between border-b border-[var(--school-border)] px-5 py-4"><div><p className="text-[10px] font-black uppercase tracking-wider theme-primary">Accounts Entry</p><h3 className="text-base font-black">Member Payment / Due</h3></div><button type="button" onClick={()=>!saving&&setOpen(false)} className="rounded-lg border border-[var(--school-border)] px-3 py-1.5 text-[10px] font-bold">Close</button></div><form onSubmit={save} className="overflow-y-auto p-5"><div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-3"><label className="text-[10px] font-bold">Entry Type<select value={form.entry_type} onChange={e=>setForm({...form,entry_type:e.target.value})} className="mt-1 w-full rounded-xl border border-[var(--school-border)] px-3 py-2.5 text-xs"><option value="student_fee">Member Fee</option><option value="salary">Salary</option><option value="other_payment">Other Member Payment</option><option value="income">Income</option><option value="expense">Expense</option><option value="vendor_payment">Vendor Payment</option><option value="school_bill">School Bill</option></select></label><label className="text-[10px] font-bold">Date<input type="date" value={form.entry_date} onChange={e=>setForm({...form,entry_date:e.target.value})} className="mt-1 w-full rounded-xl border border-[var(--school-border)] px-3 py-2.5 text-xs"/></label><label className="text-[10px] font-bold">Purpose / Category<input value={form.category} onChange={e=>setForm({...form,category:e.target.value})} placeholder="Monthly Fee / Salary / Exam Fee" className="mt-1 w-full rounded-xl border border-[var(--school-border)] px-3 py-2.5 text-xs"/></label></div>
 <div className="mt-4 rounded-2xl border border-[var(--school-border)] bg-[var(--school-primary-soft)] p-4"><div className="grid gap-3 sm:grid-cols-2"><label className="text-[10px] font-bold">Member<select value={form.party_id} onChange={e=>pick(e.target.value)} className="mt-1 w-full rounded-xl border border-[var(--school-border)] px-3 py-2.5 text-xs"><option value="">Select member...</option>{members.map(m=><option key={m.member_id} value={m.member_id}>{m.full_name} · {m.member_id}</option>)}</select></label><label className="text-[10px] font-bold">Member ID<select value={form.party_id} onChange={e=>pick(e.target.value)} className="mt-1 w-full rounded-xl border border-[var(--school-border)] px-3 py-2.5 text-xs"><option value="">Select ID...</option>{members.map(m=><option key={m.member_id} value={m.member_id}>{m.member_id}</option>)}</select></label></div>{form.party_id&&<div className="mt-3 grid gap-2 sm:grid-cols-2 lg:grid-cols-5">{[["Name",form.party_name],["ID",form.party_id],["Type",form.party_type],["Status",members.find(m=>m.member_id===form.party_id)?.status||"-"],["Designation",members.find(m=>m.member_id===form.party_id)?.designation||"-"]].map(([a,b])=><div key={a} className="rounded-xl border border-[var(--school-border)] bg-[var(--school-surface)] p-3"><p className="text-[9px] font-black uppercase tracking-wider text-[var(--school-muted)]">{a}</p><p className="mt-1 text-xs font-bold">{b}</p></div>)}</div>}</div>
 <div className="mt-4 grid gap-3 sm:grid-cols-2 lg:grid-cols-4"><label className="text-[10px] font-bold">Total Payable<input type="number" min="0" step="0.01" value={form.total} onChange={e=>setForm({...form,total:e.target.value})} className="mt-1 w-full rounded-xl border border-[var(--school-border)] px-3 py-2.5 text-xs"/></label><label className="text-[10px] font-bold">Paid Now<input type="number" min="0" step="0.01" value={form.paid} onChange={e=>setForm({...form,paid:e.target.value})} className="mt-1 w-full rounded-xl border border-[var(--school-border)] px-3 py-2.5 text-xs"/></label><div className="rounded-xl border border-[var(--school-border)] p-3"><p className="text-[9px] font-black uppercase tracking-wider text-[var(--school-muted)]">Due</p><p className="mt-1 text-sm font-black text-amber-700">৳ {money(due)}</p><p className="mt-1 text-[9px] font-black uppercase">{status}</p></div><label className="text-[10px] font-bold">Pay By / Due Date<input type="date" value={form.due_date} onChange={e=>setForm({...form,due_date:e.target.value})} className="mt-1 w-full rounded-xl border border-[var(--school-border)] px-3 py-2.5 text-xs"/></label></div>
 <div className="mt-4 grid gap-3 sm:grid-cols-2"><label className="text-[10px] font-bold">Payment Method<select value={form.method} onChange={e=>setForm({...form,method:e.target.value})} className="mt-1 w-full rounded-xl border border-[var(--school-border)] px-3 py-2.5 text-xs"><option value="cash">Cash</option><option value="bank">Bank</option><option value="mobile_banking">Mobile Banking</option><option value="cheque">Cheque</option></select></label><label className="text-[10px] font-bold">Account / Bank<input value={form.account} onChange={e=>setForm({...form,account:e.target.value})} className="mt-1 w-full rounded-xl border border-[var(--school-border)] px-3 py-2.5 text-xs"/></label><label className="text-[10px] font-bold">Reference No.<input value={form.reference} onChange={e=>setForm({...form,reference:e.target.value})} className="mt-1 w-full rounded-xl border border-[var(--school-border)] px-3 py-2.5 text-xs"/></label><label className="text-[10px] font-bold">Notes<textarea value={form.notes} onChange={e=>setForm({...form,notes:e.target.value})} rows={2} className="mt-1 w-full rounded-xl border border-[var(--school-border)] px-3 py-2.5 text-xs"/></label></div>{error&&<div className="mt-4 rounded-xl border border-red-200 bg-red-50 p-3 text-xs text-red-700">{error}</div>}<div className="mt-5 flex justify-end gap-2 border-t border-[var(--school-border)] pt-4"><button type="button" onClick={()=>setOpen(false)} className="rounded-xl border border-[var(--school-border)] px-4 py-2.5 text-xs font-bold">Cancel</button><button disabled={saving} className="rounded-xl theme-primary-bg px-5 py-2.5 text-xs font-black">{saving?"Saving...":"Save & Create Voucher"}</button></div></form></div></div>}</>
}
