"use client";
import { useEffect, useMemo, useState } from "react";
import { createClient } from "@/lib/supabase/client";

type Member={member_id:string;member_type:string;full_name:string;designation:string|null;department:string|null;subject:string|null;phone:string|null;email:string|null;is_active:boolean;status:string};
type Form={entry_type:string;entry_date:string;category:string;party_type:string;party_id:string;party_name:string;total:string;paid:string;due_date:string;method:string;account:string;reference:string;notes:string};
const fresh=():Form=>({entry_type:"student_fee",entry_date:new Date().toISOString().slice(0,10),category:"",party_type:"",party_id:"",party_name:"",total:"",paid:"",due_date:"",method:"cash",account:"",reference:"",notes:""});
const money=(n:number)=>new Intl.NumberFormat("en-BD",{minimumFractionDigits:2,maximumFractionDigits:2}).format(n||0);
const memberEntryTypes=new Set(["student_fee","salary","other_payment"]);
const labels:Record<string,string>={student_fee:"Member Fee",salary:"Salary",other_payment:"Other Member Payment",income:"Income",expense:"Expense",vendor_payment:"Vendor Payment",school_bill:"School Bill"};

export function AccountsEntryForm({permissions}:{permissions:Record<string,boolean>}){
 const supabase=useMemo(()=>createClient(),[]);const [members,setMembers]=useState<Member[]>([]);const [role,setRole]=useState("");const [form,setForm]=useState<Form>(fresh());const [open,setOpen]=useState(false);const [saving,setSaving]=useState(false);const [message,setMessage]=useState("");const [error,setError]=useState("");const token=typeof window!=="undefined"?window.localStorage.getItem("ctms_store_token"):null;
 const can=Boolean(permissions.dashboard||permissions.__all);const isMemberEntry=memberEntryTypes.has(form.entry_type);const due=Math.max(0,Number(form.total||0)-Number(form.paid||0));const status=Number(form.total||0)>0&&Number(form.paid||0)>=Number(form.total||0)?"paid":Number(form.paid||0)>0?"partial":"due";
 const roles=useMemo(()=>Array.from(new Set(members.map(m=>m.member_type).filter(Boolean))).sort((a,b)=>a.localeCompare(b)),[members]);
 const roleMembers=useMemo(()=>role?members.filter(m=>m.member_type===role):[],[members,role]);
 const selected=useMemo(()=>members.find(m=>m.member_id===form.party_id)||null,[members,form.party_id]);
 useEffect(()=>{if(token&&can)supabase.rpc("store_accounts_list_members",{p_token:token}).then(({data,error:e})=>{if(e)setError(e.message);else setMembers((data||[]) as Member[])})},[can,supabase,token]);
 const selectType=(entry_type:string)=>{setForm(f=>({...f,entry_type,party_type:"",party_id:"",party_name:"",category:"",reference:"",total:"",paid:"",due_date:"",account:"",notes:""}));setRole("");setError("")};
 const pick=(id:string)=>{const m=roleMembers.find(x=>x.member_id===id);if(m)setForm(f=>({...f,party_id:m.member_id,party_type:m.member_type,party_name:m.full_name}))};
 const changeRole=(next:string)=>{setRole(next);setForm(f=>({...f,party_id:"",party_type:next,party_name:""}))};
 const categoryLabel=form.entry_type==="income"?"Income Source":form.entry_type==="expense"?"Expense Category":form.entry_type==="vendor_payment"?"Vendor / Supplier":form.entry_type==="school_bill"?"Bill / Utility":"Purpose / Category";
 const categoryPlaceholder=form.entry_type==="income"?"Tuition, admission, donation...":form.entry_type==="expense"?"Transport, maintenance, supplies...":form.entry_type==="vendor_payment"?"Supplier / vendor name":form.entry_type==="school_bill"?"Electricity, water, internet...":"Monthly Fee / Salary / Exam Fee";
 const amountLabel=isMemberEntry?"Total Payable":form.entry_type==="school_bill"?"Bill Amount":form.entry_type==="income"?"Income Amount":form.entry_type==="expense"?"Expense Amount":form.entry_type==="vendor_payment"?"Payable Amount":"Amount";
 const detailsTitle=form.entry_type==="school_bill"?"Bill Details":form.entry_type==="vendor_payment"?"Vendor Details":form.entry_type==="income"?"Income Details":"Expense Details";
 async function save(ev:React.FormEvent){ev.preventDefault();if(!token||saving)return;const total=Number(form.total||0),paid=Number(form.paid||0);setError("");if(total<=0)return setError("Amount must be greater than zero.");if(paid<0||paid>total)return setError("Paid amount cannot be greater than total.");if(isMemberEntry&&!form.party_id)return setError("Select a role and member ID.");if(due>0&&!form.due_date)return setError("Due date is required for an unpaid amount.");setSaving(true);const r=await supabase.rpc("store_accounts_save_entry_v2",{p_token:token,p_entry_type:form.entry_type,p_entry_date:form.entry_date,p_category:form.category,p_party_type:isMemberEntry?form.party_type:null,p_party_id:isMemberEntry?form.party_id:null,p_party_name:isMemberEntry?form.party_name:null,p_total_amount:total,p_paid_amount:paid,p_due_date:form.due_date||null,p_payment_method:form.method,p_account_name:form.account,p_reference_no:form.reference,p_description:form.notes});setSaving(false);if(r.error)setError(r.error.message);else{setMessage(`Saved ${String(r.data?.voucher_no||"")}${isMemberEntry&&form.party_id?` for ${form.party_id}`:""}.`);setOpen(false);setRole("");setForm(fresh())}}
 if(!can)return null;
 return <><button type="button" onClick={()=>{setError("");setMessage("");setRole("");setForm(fresh());setOpen(true)}} className="rounded-xl theme-primary-bg px-3 py-2 text-xs font-bold">+ Accounts Entry</button>{message&&<div className="mt-3 rounded-xl border border-[var(--school-primary-border)] bg-[var(--school-primary-soft)] p-3 text-xs font-semibold theme-primary">{message}</div>}{open&&<div className="fixed inset-0 z-[100] flex items-center justify-center bg-slate-950/50 p-3 sm:p-5" onMouseDown={e=>{if(e.target===e.currentTarget&&!saving)setOpen(false)}}><div className="flex max-h-[92vh] w-full max-w-4xl flex-col overflow-hidden rounded-2xl border border-[var(--school-border)] bg-[var(--school-surface)] shadow-2xl"><div className="flex items-center justify-between border-b border-[var(--school-border)] px-5 py-4"><div><p className="text-[10px] font-black uppercase tracking-wider theme-primary">Accounts Entry</p><h3 className="text-base font-black">{labels[form.entry_type]||"Accounts Entry"}</h3></div><button type="button" onClick={()=>!saving&&setOpen(false)} className="rounded-lg border border-[var(--school-border)] px-3 py-1.5 text-[10px] font-bold">Close</button></div><form onSubmit={save} className="overflow-y-auto p-5"><div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-3"><label className="text-[10px] font-bold">Entry Type<select value={form.entry_type} onChange={e=>selectType(e.target.value)} className="mt-1 w-full rounded-xl border border-[var(--school-border)] px-3 py-2.5 text-xs"><option value="student_fee">Member Fee</option><option value="salary">Salary</option><option value="other_payment">Other Member Payment</option><option value="income">Income</option><option value="expense">Expense</option><option value="vendor_payment">Vendor Payment</option><option value="school_bill">School Bill</option></select></label><label className="text-[10px] font-bold">Date<input type="date" value={form.entry_date} onChange={e=>setForm({...form,entry_date:e.target.value})} className="mt-1 w-full rounded-xl border border-[var(--school-border)] px-3 py-2.5 text-xs"/></label><label className="text-[10px] font-bold">{categoryLabel}<input value={form.category} onChange={e=>setForm({...form,category:e.target.value})} placeholder={categoryPlaceholder} className="mt-1 w-full rounded-xl border border-[var(--school-border)] px-3 py-2.5 text-xs"/></label></div>
 {isMemberEntry?<div className="mt-4 rounded-2xl border border-[var(--school-border)] bg-[var(--school-primary-soft)] p-4"><div className="grid gap-3 sm:grid-cols-2"><label className="text-[10px] font-bold">Role<select value={role} onChange={e=>changeRole(e.target.value)} className="mt-1 w-full rounded-xl border border-[var(--school-border)] px-3 py-2.5 text-xs"><option value="">Select role...</option>{roles.map(r=><option key={r} value={r}>{r.charAt(0).toUpperCase()+r.slice(1)}</option>)}</select></label><label className="text-[10px] font-bold">Member ID<select value={form.party_id} onChange={e=>pick(e.target.value)} disabled={!role} className="mt-1 w-full rounded-xl border border-[var(--school-border)] px-3 py-2.5 text-xs"><option value="">{role?"Select ID...":"Select role first..."}</option>{roleMembers.map(m=><option key={m.member_id} value={m.member_id}>{m.member_id} · {m.full_name}</option>)}</select></label></div>{selected&&<div className="mt-3 grid gap-2 sm:grid-cols-2 lg:grid-cols-5">{[["Name",selected.full_name],["ID",selected.member_id],["Role",selected.member_type],["Status",selected.status||"-"],["Designation",selected.designation||"-"]].map(([a,b])=><div key={a} className="rounded-xl border border-[var(--school-border)] bg-[var(--school-surface)] p-3"><p className="text-[9px] font-black uppercase tracking-wider text-[var(--school-muted)]">{a}</p><p className="mt-1 text-xs font-bold">{b}</p></div>)}</div>}</div>:<div className="mt-4 rounded-2xl border border-[var(--school-border)] bg-[var(--school-primary-soft)] p-4"><p className="text-[10px] font-black uppercase tracking-wider theme-primary">{detailsTitle}</p><div className="mt-3 grid gap-3 sm:grid-cols-2"><label className="text-[10px] font-bold">{form.entry_type==="school_bill"?"Bill / Invoice No.":form.entry_type==="income"?"Receipt / Reference No.":form.entry_type==="expense"?"Expense Reference No.":"Vendor Invoice / Reference"}<input value={form.reference} onChange={e=>setForm({...form,reference:e.target.value})} className="mt-1 w-full rounded-xl border border-[var(--school-border)] px-3 py-2.5 text-xs"/></label><label className="text-[10px] font-bold">{form.entry_type==="school_bill"?"Payee / Provider":form.entry_type==="income"?"Received From":form.entry_type==="expense"?"Paid To":"Vendor / Supplier"}<input value={form.party_name} onChange={e=>setForm({...form,party_name:e.target.value})} className="mt-1 w-full rounded-xl border border-[var(--school-border)] px-3 py-2.5 text-xs"/></label></div></div>}
 <div className="mt-4 grid gap-3 sm:grid-cols-2 lg:grid-cols-4"><label className="text-[10px] font-bold">{amountLabel}<input type="number" min="0" step="0.01" value={form.total} onChange={e=>setForm({...form,total:e.target.value})} className="mt-1 w-full rounded-xl border border-[var(--school-border)] px-3 py-2.5 text-xs"/></label><label className="text-[10px] font-bold">Paid Now<input type="number" min="0" step="0.01" value={form.paid} onChange={e=>setForm({...form,paid:e.target.value})} className="mt-1 w-full rounded-xl border border-[var(--school-border)] px-3 py-2.5 text-xs"/></label><div className="rounded-xl border border-[var(--school-border)] p-3"><p className="text-[9px] font-black uppercase tracking-wider text-[var(--school-muted)]">Due</p><p className="mt-1 text-sm font-black text-amber-700">৳ {money(due)}</p><p className="mt-1 text-[9px] font-black uppercase">{status}</p></div><label className="text-[10px] font-bold">Pay By / Due Date<input type="date" value={form.due_date} onChange={e=>setForm({...form,due_date:e.target.value})} className="mt-1 w-full rounded-xl border border-[var(--school-border)] px-3 py-2.5 text-xs"/></label></div>
 <div className="mt-4 grid gap-3 sm:grid-cols-2"><label className="text-[10px] font-bold">Payment Method<select value={form.method} onChange={e=>setForm({...form,method:e.target.value})} className="mt-1 w-full rounded-xl border border-[var(--school-border)] px-3 py-2.5 text-xs"><option value="cash">Cash</option><option value="bank">Bank</option><option value="mobile_banking">Mobile Banking</option><option value="cheque">Cheque</option></select></label><label className="text-[10px] font-bold">Account / Bank<input value={form.account} onChange={e=>setForm({...form,account:e.target.value})} className="mt-1 w-full rounded-xl border border-[var(--school-border)] px-3 py-2.5 text-xs"/></label><label className="text-[10px] font-bold">Reference No.<input value={form.reference} onChange={e=>setForm({...form,reference:e.target.value})} className="mt-1 w-full rounded-xl border border-[var(--school-border)] px-3 py-2.5 text-xs"/></label><label className="text-[10px] font-bold">Notes<textarea value={form.notes} onChange={e=>setForm({...form,notes:e.target.value})} rows={2} className="mt-1 w-full rounded-xl border border-[var(--school-border)] px-3 py-2.5 text-xs"/></label></div>{error&&<div className="mt-4 rounded-xl border border-red-200 bg-red-50 p-3 text-xs text-red-700">{error}</div>}<div className="mt-5 flex justify-end gap-2 border-t border-[var(--school-border)] pt-4"><button type="button" onClick={()=>setOpen(false)} className="rounded-xl border border-[var(--school-border)] px-4 py-2.5 text-xs font-bold">Cancel</button><button disabled={saving} className="rounded-xl theme-primary-bg px-5 py-2.5 text-xs font-black">{saving?"Saving...":"Save & Create Voucher"}</button></div></form></div></div>}</>
}
