"use client";
import { useEffect,useMemo,useState } from "react";
import { createClient } from "@/lib/supabase/client";

type Entry={id:string;voucher_no:string;entry_date:string;entry_type:string;category:string|null;party_id:string|null;party_name:string|null;total_amount:number;paid_amount:number;due_amount:number;due_date:string|null;payment_status:string;payment_method:string;reference_no:string|null;description:string|null;entry_source:string;display_group:string;created_at?:string|null};
type Summary={base_salary:number;salary_sheet_total:number;salary_sheet_paid:number;salary_sheet_due:number;old_due:number;total_amount:number;paid_amount:number;due_amount:number;next_due_date:string|null};
type CurrentUser={member_id:string;permissions:Record<string,unknown>;full_name:string};
const money=(n:number)=>new Intl.NumberFormat("en-BD",{minimumFractionDigits:2,maximumFractionDigits:2}).format(Number(n)||0);
const monthLabel=(d:string|null)=>d?new Date(`${d.slice(0,7)}-01T00:00:00`).toLocaleDateString("en-US",{month:"long",year:"numeric"}):"";
const dateTimeLabel=(d:string|null|undefined)=>{if(!d)return "-";const x=new Date(d);if(Number.isNaN(x.getTime()))return d;return new Intl.DateTimeFormat("en-GB",{day:"2-digit",month:"short",year:"numeric",hour:"2-digit",minute:"2-digit",hour12:true,timeZone:"Asia/Dhaka"}).format(x)};
const days=(d:string|null)=>{if(!d)return null;const x=new Date(`${d}T00:00:00`);const t=new Date();t.setHours(0,0,0,0);return Math.ceil((x.getTime()-t.getTime())/86400000)};
const label=(e:Entry)=>e.category||({salary:"Salary",salary_payment:"Salary Payment",other_payment:"Other Member Payment",student_fee:"Member Fee"}[e.entry_type]||e.entry_type);

export default function MemberAccountsV2({compact=false,personalOnly=false}:{compact?:boolean;personalOnly?:boolean}){
 const supabase=useMemo(()=>createClient(),[]);const [user,setUser]=useState<CurrentUser|null>(null);const [summary,setSummary]=useState<Summary|null>(null);const [entries,setEntries]=useState<Entry[]>([]);const [loading,setLoading]=useState(true);const [error,setError]=useState("");
 const token=typeof window!=="undefined"?window.localStorage.getItem("ctms_store_token"):null;
 useEffect(()=>{if(!token)return;let alive=true;(async()=>{try{const r=await supabase.rpc("store_get_current_user",{p_token:token});if(r.error)throw r.error;if(!alive)return;const u=r.data as CurrentUser;setUser(u);const acc=u.permissions?.accounts&&typeof u.permissions.accounts==="object"?u.permissions.accounts as Record<string,boolean>:{};const canStatus=Boolean(acc.salary_status||acc.__all);const canHistory=Boolean(acc.salary_history||acc.salary_status||acc.__all);if(!canStatus&&!canHistory){setLoading(false);return}const [s,h]=await Promise.all([canStatus?supabase.rpc("store_accounts_member_summary",{p_token:token}):Promise.resolve({data:null,error:null}),canHistory?supabase.rpc("store_accounts_member_history_v2",{p_token:token}):Promise.resolve({data:[],error:null})]);if(s?.error||h?.error)throw new Error(s?.error?.message||h?.error?.message||"Unable to load account status.");if(s?.data)setSummary(s.data as Summary);setEntries((h?.data||[]) as Entry[])}catch(e){if(alive)setError(e instanceof Error?e.message:"Unable to load Accounts.")}finally{if(alive)setLoading(false)}})();return()=>{alive=false}},[supabase,token]);
 if(loading)return <div className="mt-5 rounded-2xl border border-[var(--school-border)] p-5 text-xs text-[var(--school-muted)]">Loading Salary Status...</div>;
 if(error&&!user)return <div className="mt-5 rounded-2xl border border-red-200 bg-red-50 p-5 text-xs text-red-700">{error}</div>;
 if(!summary&&!entries.length)return <div className="mt-5 rounded-2xl border border-dashed border-[var(--school-border)] p-5 text-center text-xs text-[var(--school-muted)]">Salary status is not available for this member.</div>;
 const next=summary?.next_due_date?days(summary.next_due_date):null;const salaryEntries=entries.filter(e=>e.display_group==="salary_sheet");const paymentEntries=entries.filter(e=>e.display_group==="salary_payment");const salaryMonth=salaryEntries[0]?.entry_date?monthLabel(salaryEntries[0].entry_date):null;
 return <section className={`mt-5 rounded-2xl border border-[var(--school-border)] ${compact?"p-4":"p-5"}`}>
  <div className="flex flex-col gap-2 sm:flex-row sm:items-center sm:justify-between"><div><p className="text-[10px] font-black uppercase tracking-[0.15em] theme-primary">My Salary</p><h3 className="mt-1 text-lg font-black">Payment & Due Status</h3></div><span className={`w-fit rounded-full px-3 py-1.5 text-[10px] font-black uppercase ${Number(summary?.due_amount||0)>0?"bg-amber-50 text-amber-700":"bg-emerald-50 text-emerald-700"}`}>{Number(summary?.due_amount||0)>0?"DUE":"PAID"}</span></div>
  <div className="mt-4 grid gap-3 sm:grid-cols-2 lg:grid-cols-5"><div className="rounded-xl border border-[var(--school-primary-border)] bg-[var(--school-primary-soft)] p-4 ring-1 ring-[var(--school-primary-border)]"><div className="flex items-center justify-between gap-2"><p className="text-[10px] text-[var(--school-muted)]">Salary Sheet</p>{salaryMonth&&<span className="rounded-full border border-[var(--school-primary-border)] bg-[var(--school-surface)] px-2 py-1 text-[9px] font-black theme-primary">{salaryMonth}</span>}</div><p className="mt-1 text-lg font-black">৳ {money(Number(summary?.salary_sheet_total||0))}</p><p className="mt-1 text-[10px] text-[var(--school-muted)]">Paid ৳ {money(Number(summary?.salary_sheet_paid||0))}</p></div><div className="rounded-xl border border-amber-200 bg-amber-50 p-4"><p className="text-[10px] text-amber-700">Old Due</p><p className="mt-1 text-lg font-black text-amber-800">৳ {money(Number(summary?.old_due||0))}</p><p className="mt-1 text-[10px] text-amber-700">Previous outstanding</p></div><div className="rounded-xl border border-[var(--school-border)] bg-[var(--school-primary-soft)] p-4"><p className="text-[10px] text-[var(--school-muted)]">Total</p><p className="mt-1 text-lg font-black">৳ {money(Number(summary?.total_amount||0))}</p><p className="mt-1 text-[10px] text-[var(--school-muted)]">Salary + Old Due</p></div><div className="rounded-xl border border-[var(--school-border)] bg-[var(--school-primary-soft)] p-4"><p className="text-[10px] text-[var(--school-muted)]">Paid</p><p className="mt-1 text-lg font-black theme-primary">৳ {money(Number(summary?.paid_amount||0))}</p></div><div className="rounded-xl border border-[var(--school-border)] bg-[var(--school-primary-soft)] p-4"><p className="text-[10px] text-[var(--school-muted)]">Due</p><p className="mt-1 text-lg font-black text-amber-700">৳ {money(Number(summary?.due_amount||0))}</p>{next!==null&&<p className="mt-1 text-[10px] font-bold text-amber-700">{next<0?`${Math.abs(next)} days overdue`:next===0?"Due today":`${next} days left`}</p>}</div></div>
  {paymentEntries.length>0&&<div className="mt-5 rounded-2xl border border-[var(--school-border)] bg-[var(--school-surface)]"><div className="border-b border-[var(--school-border)] px-4 py-3"><p className="text-[10px] font-black uppercase tracking-[0.15em] theme-primary">Payment History</p><p className="mt-1 text-xs text-[var(--school-muted)]">Every salary payment is listed separately with the payment date and time.</p></div><div className="overflow-x-auto"><table className="w-full min-w-[1050px] text-left text-xs"><thead><tr className="border-b border-[var(--school-border)] text-[10px] uppercase tracking-wider text-[var(--school-muted)]"><th className="p-3">Payment Date & Time</th><th className="p-3">Purpose</th><th className="p-3">Voucher</th><th className="p-3">Amount</th><th className="p-3">Method</th><th className="p-3">Reference</th><th className="p-3">Status</th></tr></thead><tbody>{paymentEntries.map(e=><tr key={e.id} className="border-b border-[var(--school-border)] last:border-b-0"><td className="p-3 font-semibold whitespace-nowrap">{dateTimeLabel(e.created_at)}</td><td className="p-3 font-bold">{label(e)}</td><td className="p-3 font-bold">{e.voucher_no}</td><td className="p-3 font-black theme-primary">৳ {money(Number(e.paid_amount||e.total_amount||0))}</td><td className="p-3 capitalize">{(e.payment_method||"-").replaceAll("_"," ")}</td><td className="p-3">{e.reference_no||"-"}</td><td className="p-3"><span className="rounded-full bg-emerald-50 px-2.5 py-1 text-[9px] font-black uppercase text-emerald-700">Paid</span></td></tr>)}</tbody></table></div></div>}
  {!personalOnly&&entries.length>0&&<div className="mt-5 overflow-x-auto"><table className="w-full min-w-[1050px] text-left text-xs"><thead><tr className="border-b border-[var(--school-border)] text-[10px] uppercase tracking-wider text-[var(--school-muted)]"><th className="p-2">Type</th><th className="p-2">Date</th><th className="p-2">Voucher</th><th className="p-2">Purpose</th><th className="p-2">Total</th><th className="p-2">Paid</th><th className="p-2">Due</th><th className="p-2">Status</th></tr></thead><tbody>{entries.map(e=><tr key={e.id} className="border-b border-[var(--school-border)]"><td className="p-2 font-black">{e.display_group==="salary_sheet"?"Salary Sheet":e.display_group==="salary_payment"?"Salary Payment":"Old Due"}</td><td className="p-2">{e.display_group==="salary_sheet"?monthLabel(e.entry_date):e.display_group==="salary_payment"?dateTimeLabel(e.created_at):e.entry_date}</td><td className="p-2 font-bold">{e.voucher_no}</td><td className="p-2">{label(e)}</td><td className="p-2">৳ {money(Number(e.total_amount||0))}</td><td className="p-2 theme-primary">৳ {money(Number(e.paid_amount||0))}</td><td className="p-2 font-bold text-amber-700">৳ {money(Number(e.due_amount||0))}</td><td className="p-2 font-black uppercase">{e.payment_status}</td></tr>)}</tbody></table></div>}
 </section>;
}
