"use client";
import { useEffect,useMemo,useState } from "react";
import { createClient } from "@/lib/supabase/client";

type Entry={id:string;voucher_no:string;entry_date:string;entry_type:string;category:string|null;party_id:string|null;party_name:string|null;total_amount:number;paid_amount:number;due_amount:number;due_date:string|null;payment_status:string;payment_method:string;reference_no:string|null;description:string|null;entry_source:string;display_group:string};
type Summary={base_salary:number;salary_sheet_total:number;salary_sheet_paid:number;salary_sheet_due:number;old_due:number;total_amount:number;paid_amount:number;due_amount:number;next_due_date:string|null};
const money=(n:number)=>new Intl.NumberFormat("en-BD",{minimumFractionDigits:2,maximumFractionDigits:2}).format(n||0);
const days=(d:string|null)=>{if(!d)return null;const x=new Date(`${d}T00:00:00`);const t=new Date();t.setHours(0,0,0,0);return Math.ceil((x.getTime()-t.getTime())/86400000)};
const label=(e:Entry)=>e.category||({salary:"Salary",other_payment:"Other Member Payment",student_fee:"Member Fee"}[e.entry_type]||e.entry_type);

export default function MemberAccountsV2({compact=false}:{compact?:boolean}){
 const supabase=useMemo(()=>createClient(),[]);const [summary,setSummary]=useState<Summary|null>(null);const [entries,setEntries]=useState<Entry[]>([]);const [loading,setLoading]=useState(true);const [error,setError]=useState("");
 const token=typeof window!=="undefined"?window.localStorage.getItem("ctms_store_token"):null;
 useEffect(()=>{if(!token)return;let alive=true;(async()=>{const [s,h]=await Promise.all([supabase.rpc("store_accounts_member_summary",{p_token:token}),supabase.rpc("store_accounts_member_history_v2",{p_token:token})]);if(!alive)return;if(s.error||h.error)setError(s.error?.message||h.error?.message||"");else{setSummary(s.data as Summary);setEntries((h.data||[]) as Entry[])}setLoading(false)})();return()=>{alive=false}},[supabase,token]);
 if(loading)return <div className="mt-5 rounded-2xl border border-[var(--school-border)] p-5 text-xs text-[var(--school-muted)]">Loading account history...</div>;
 if(error)return <div className="mt-5 rounded-2xl border border-red-200 bg-red-50 p-5 text-xs text-red-700">{error}</div>;
 const next=summary?.next_due_date?days(summary.next_due_date):null;const salaryEntries=entries.filter(e=>e.display_group==="salary_sheet");const oldEntries=entries.filter(e=>e.display_group==="old_due");
 return <section className={`mt-5 rounded-2xl border border-[var(--school-border)] ${compact?"p-4":"p-5"}`}>
  <div className="flex flex-col gap-2 sm:flex-row sm:items-center sm:justify-between"><div><p className="text-[10px] font-black uppercase tracking-[0.15em] theme-primary">My Accounts</p><h3 className="mt-1 text-lg font-black">Payment & Due Status</h3></div><span className={`w-fit rounded-full px-3 py-1.5 text-[10px] font-black uppercase ${Number(summary?.due_amount||0)>0?"bg-amber-50 text-amber-700":"bg-emerald-50 text-emerald-700"}`}>{Number(summary?.due_amount||0)>0?"Due":"Paid"}</span></div>
  <div className="mt-4 grid gap-3 sm:grid-cols-2 lg:grid-cols-5">
   <div className="rounded-xl border border-[var(--school-border)] bg-[var(--school-primary-soft)] p-4"><p className="text-[10px] text-[var(--school-muted)]">Salary Sheet</p><p className="mt-1 text-lg font-black">৳ {money(Number(summary?.salary_sheet_total||0))}</p><p className="mt-1 text-[10px] text-[var(--school-muted)]">Paid ৳ {money(Number(summary?.salary_sheet_paid||0))}</p></div>
   <div className="rounded-xl border border-amber-200 bg-amber-50 p-4"><p className="text-[10px] text-amber-700">Old Due</p><p className="mt-1 text-lg font-black text-amber-800">৳ {money(Number(summary?.old_due||0))}</p><p className="mt-1 text-[10px] text-amber-700">Previous outstanding</p></div>
   <div className="rounded-xl border border-[var(--school-border)] bg-[var(--school-primary-soft)] p-4"><p className="text-[10px] text-[var(--school-muted)]">Total</p><p className="mt-1 text-lg font-black">৳ {money(Number(summary?.total_amount||0))}</p><p className="mt-1 text-[10px] text-[var(--school-muted)]">Salary + Old Due</p></div>
   <div className="rounded-xl border border-[var(--school-border)] bg-[var(--school-primary-soft)] p-4"><p className="text-[10px] text-[var(--school-muted)]">Paid</p><p className="mt-1 text-lg font-black theme-primary">৳ {money(Number(summary?.paid_amount||0))}</p></div>
   <div className="rounded-xl border border-[var(--school-border)] bg-[var(--school-primary-soft)] p-4"><p className="text-[10px] text-[var(--school-muted)]">Due</p><p className="mt-1 text-lg font-black text-amber-700">৳ {money(Number(summary?.due_amount||0))}</p>{next!==null&&<p className="mt-1 text-[10px] font-bold text-amber-700">{next<0?`${Math.abs(next)} days overdue`:next===0?"Due today":`${next} days left`}</p>}</div>
  </div>
  {(salaryEntries.length>0||oldEntries.length>0)&&<div className="mt-5 grid gap-4 lg:grid-cols-2">
   <div className="rounded-2xl border border-[var(--school-border)] p-4"><div className="flex items-center justify-between"><div><p className="text-[10px] font-black uppercase tracking-wider theme-primary">Current Salary Sheet</p><p className="mt-1 text-xs text-[var(--school-muted)]">Submitted by HR and linked to this member ID.</p></div><p className="text-base font-black theme-primary">৳ {money(Number(summary?.salary_sheet_total||0))}</p></div><div className="mt-3 space-y-2">{salaryEntries.map(e=><div key={e.id} className="rounded-xl border border-[var(--school-border)] bg-[var(--school-primary-soft)] p-3"><div className="flex items-start justify-between gap-3"><div><p className="text-xs font-black">{label(e)}</p><p className="mt-1 text-[10px] text-[var(--school-muted)]">{e.entry_date} · {e.voucher_no}</p></div><p className="text-sm font-black">৳ {money(Number(e.total_amount||0))}</p></div><div className="mt-2 grid grid-cols-3 gap-2 text-[10px]"><span>Paid <b className="theme-primary">৳ {money(Number(e.paid_amount||0))}</b></span><span>Due <b className="text-amber-700">৳ {money(Number(e.due_amount||0))}</b></span><span>Status <b className="uppercase">{e.payment_status}</b></span></div>{e.description&&<p className="mt-2 text-[10px] text-[var(--school-muted)]">{e.description}</p>}</div>)}</div></div>
   <div className="rounded-2xl border border-[var(--school-border)] p-4"><div className="flex items-center justify-between"><div><p className="text-[10px] font-black uppercase tracking-wider text-amber-700">Old Due Details</p><p className="mt-1 text-xs text-[var(--school-muted)]">Previous outstanding amounts, kept separate from the current salary sheet.</p></div><p className="text-base font-black text-amber-800">৳ {money(Number(summary?.old_due||0))}</p></div><div className="mt-3 space-y-2">{oldEntries.filter(e=>Number(e.due_amount||0)>0).map(e=><div key={e.id} className="rounded-xl border border-amber-100 bg-amber-50 p-3"><div className="flex items-start justify-between gap-3"><div><p className="text-xs font-black">{label(e)}</p><p className="mt-1 text-[10px] text-amber-700">{e.entry_date} · {e.voucher_no}</p></div><p className="text-sm font-black text-amber-800">৳ {money(Number(e.due_amount||0))}</p></div><div className="mt-2 text-[10px] text-amber-700">Original ৳ {money(Number(e.total_amount||0))} · Paid ৳ {money(Number(e.paid_amount||0))}</div></div>)}{oldEntries.filter(e=>Number(e.due_amount||0)>0).length===0&&<p className="rounded-xl border border-dashed border-[var(--school-border)] p-4 text-center text-[10px] text-[var(--school-muted)]">No old outstanding due.</p>}</div></div>
  </div>}
  {entries.length>0&&<div className="mt-5 overflow-x-auto"><table className="w-full min-w-[1050px] text-left text-xs"><thead><tr className="border-b border-[var(--school-border)] text-[10px] uppercase tracking-wider text-[var(--school-muted)]"><th className="p-2">Type</th><th className="p-2">Date</th><th className="p-2">Voucher</th><th className="p-2">Purpose</th><th className="p-2">Total</th><th className="p-2">Paid</th><th className="p-2">Due</th><th className="p-2">Pay By</th><th className="p-2">Status</th><th className="p-2">Details</th></tr></thead><tbody>{entries.map(e=><tr key={e.id} className="border-b border-[var(--school-border)]"><td className="p-2 font-black">{e.display_group==="salary_sheet"?"Salary Sheet":"Old Due"}</td><td className="p-2">{e.entry_date}</td><td className="p-2 font-bold">{e.voucher_no}</td><td className="p-2">{label(e)}</td><td className="p-2">৳ {money(Number(e.total_amount||0))}</td><td className="p-2 theme-primary">৳ {money(Number(e.paid_amount||0))}</td><td className="p-2 font-bold text-amber-700">৳ {money(Number(e.due_amount||0))}</td><td className="p-2">{e.due_date||"-"}</td><td className="p-2 font-black uppercase">{e.payment_status}</td><td className="p-2 max-w-[260px]">{e.description||e.reference_no||"-"}</td></tr>)}</tbody></table></div>}
  {entries.length===0&&<p className="mt-4 rounded-xl border border-dashed border-[var(--school-border)] p-5 text-center text-xs text-[var(--school-muted)]">No Accounts entry has been linked to your ID yet.</p>}
 </section>;
}
