"use client";
import { useEffect,useMemo,useState } from "react";
import { createClient } from "@/lib/supabase/client";
import MemberAccountsV2 from "./member-accounts-v2";

type SalarySheet={id:string;payroll_month:string;member_id:string;member_type:string;member_name:string;designation:string|null;department:string|null;base_salary:number;working_days:number;present_days:number;absent_days:number;per_day_salary:number;gross_earned:number;bonus_percent:number;bonus_amount:number;extra_payment:number;other_earnings:number;deductions:number;payable_salary:number;status:string;accounts_entry_id:string|null;submitted_at:string|null;approved_at:string|null;paid_at:string|null;paid_amount:number;due_amount:number;payment_status:string;due_date:string|null;voucher_no:string|null};
type Permissions=Record<string,boolean>;
type User={member_type:string;permissions:Record<string,unknown>};
const money=(n:number)=>new Intl.NumberFormat("en-BD",{minimumFractionDigits:2,maximumFractionDigits:2}).format(Number(n)||0);
const monthLabel=(d:string|null)=>d?new Date(`${d.slice(0,7)}-01T00:00:00`).toLocaleDateString("en-US",{month:"long",year:"numeric"}):"";

export default function SalaryManager({token,permissions}:{token:string|null;permissions:Permissions}){
 const supabase=useMemo(()=>createClient(),[]);
 const [user,setUser]=useState<User|null>(null);const [sheets,setSheets]=useState<SalarySheet[]>([]);const [loading,setLoading]=useState(true);const [error,setError]=useState("");const [busy,setBusy]=useState("");const [month,setMonth]=useState(()=>new Date().toISOString().slice(0,7)+"-01");const [search,setSearch]=useState("");const [paying,setPaying]=useState<SalarySheet|null>(null);const [amount,setAmount]=useState("");const [method,setMethod]=useState("cash");const [reference,setReference]=useState("");const [note,setNote]=useState("");
 const canView=Boolean(permissions.salary_view||permissions.salary_approval||permissions.salary_payment||permissions.__all);const canApprove=Boolean(permissions.salary_approval||permissions.__all);const canPay=Boolean(permissions.salary_payment||permissions.__all);
 const load=async()=>{if(!token||!canView)return;const r=await supabase.rpc("store_accounts_list_salary_sheets",{p_token:token,p_month:month,p_search:search||null});if(r.error)throw r.error;setSheets((r.data||[]) as SalarySheet[])};
 useEffect(()=>{if(!token)return;let alive=true;(async()=>{try{const u=await supabase.rpc("store_get_current_user",{p_token:token});if(u.error)throw u.error;if(!alive)return;setUser(u.data as User);if(canView)await load()}catch(e){if(alive)setError(e instanceof Error?e.message:"Unable to load salary sheets.")}finally{if(alive)setLoading(false)}})();return()=>{alive=false}},[token,month,search,canView]);
 const approve=async(s:SalarySheet)=>{if(!token||!canApprove)return;setBusy(s.id);setError("");try{const r=await supabase.rpc("store_accounts_approve_salary_sheet",{p_token:token,p_payroll_id:s.id});if(r.error)throw r.error;await load()}catch(e){setError(e instanceof Error?e.message:"Approval failed.")}finally{setBusy("")}};
 const openPay=(s:SalarySheet)=>{setPaying(s);setAmount(String(Number(s.due_amount||0)));setMethod("cash");setReference("");setNote("");setError("")};
 const pay=async()=>{if(!token||!paying||!canPay)return;const n=Number(amount);if(!Number.isFinite(n)||n<=0){setError("Payment amount must be greater than zero.");return}if(n>Number(paying.due_amount)){setError(`Payment cannot exceed due amount ৳ ${money(Number(paying.due_amount))}.`);return}setBusy(paying.id);setError("");try{const r=await supabase.rpc("store_accounts_pay_salary_sheet",{p_token:token,p_payroll_id:paying.id,p_payment_amount:n,p_payment_method:method,p_reference_no:reference||null,p_description:note||null});if(r.error)throw r.error;setPaying(null);await load()}catch(e){setError(e instanceof Error?e.message:"Payment failed.")}finally{setBusy("")}};
 if(loading)return <div className="mt-5 rounded-2xl border border-[var(--school-border)] p-5 text-xs text-[var(--school-muted)]">Loading Accounts...</div>;
 if(!user)return <div className="mt-5 rounded-2xl border border-red-200 bg-red-50 p-5 text-xs text-red-700">Unable to load your account.</div>;
 if(!canView)return <MemberAccountsV2 />;
 const total=sheets.reduce((n,s)=>n+Number(s.payable_salary||0),0),paid=sheets.reduce((n,s)=>n+Number(s.paid_amount||0),0),due=sheets.reduce((n,s)=>n+Number(s.due_amount||0),0),partial=sheets.filter(s=>Number(s.paid_amount||0)>0&&Number(s.due_amount||0)>0).length;
 const badge=(s:SalarySheet)=>{const p=Number(s.paid_amount||0),d=Number(s.due_amount||0);if(d<=0&&Number(s.payable_salary||0)>0)return ["PAID","bg-emerald-50 text-emerald-700"];if(p>0&&d>0)return ["PARTIAL","bg-orange-50 text-orange-700"];return ["DUE","bg-red-50 text-red-700"]};
 return <section className="mt-5 rounded-2xl border border-[var(--school-border)] p-5">
  <div className="flex flex-col gap-3 lg:flex-row lg:items-start lg:justify-between"><div><p className="text-[10px] font-black uppercase tracking-[0.15em] theme-primary">Accounts • Salary Management</p><h3 className="mt-1 text-lg font-black">Salary Sheets & Payments</h3><p className="mt-1 text-xs text-[var(--school-muted)]">Access is controlled by the individual salary permissions assigned to your role.</p></div><div className="flex flex-wrap gap-2"><select value={month} onChange={e=>setMonth(e.target.value)} className="rounded-xl border border-[var(--school-border)] bg-[var(--school-surface)] px-3 py-2 text-xs font-bold">{Array.from({length:19},(_,i)=>{const d=new Date();d.setMonth(d.getMonth()+i-12);const v=`${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,"0")}-01`;return <option key={v} value={v}>{monthLabel(v)}</option>})}</select><input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Search name, ID, department..." className="w-64 max-w-full rounded-xl border border-[var(--school-border)] bg-[var(--school-surface)] px-3 py-2 text-xs"/></div></div>
  {error&&<div className="mt-4 rounded-xl border border-red-200 bg-red-50 p-3 text-xs font-semibold text-red-700">{error}</div>}
  <div className="mt-4 grid gap-3 sm:grid-cols-2 lg:grid-cols-4"><div className="rounded-xl border border-[var(--school-border)] bg-[var(--school-primary-soft)] p-4"><p className="text-[10px] text-[var(--school-muted)]">Salary Sheets</p><p className="mt-1 text-xl font-black">{sheets.length}</p></div><div className="rounded-xl border border-[var(--school-border)] bg-[var(--school-primary-soft)] p-4"><p className="text-[10px] text-[var(--school-muted)]">Total Payable</p><p className="mt-1 text-xl font-black">৳ {money(total)}</p></div><div className="rounded-xl border border-[var(--school-border)] bg-[var(--school-primary-soft)] p-4"><p className="text-[10px] text-[var(--school-muted)]">Paid</p><p className="mt-1 text-xl font-black theme-primary">৳ {money(paid)}</p></div><div className="rounded-xl border border-red-200 bg-red-50 p-4"><p className="text-[10px] text-red-700">Due</p><p className="mt-1 text-xl font-black text-red-700">৳ {money(due)}</p><p className="mt-1 text-[10px] font-bold text-orange-700">{partial} partial payment{partial===1?"":"s"}</p></div></div>
  <div className="mt-5 overflow-x-auto"><table className="w-full min-w-[1220px] text-left text-xs"><thead><tr className="border-b border-[var(--school-border)] text-[10px] uppercase tracking-wider text-[var(--school-muted)]"><th className="p-2">Employee</th><th className="p-2">Department</th><th className="p-2">Attendance</th><th className="p-2">Base</th><th className="p-2">Earned</th><th className="p-2">Deduction</th><th className="p-2">Payable</th><th className="p-2">Paid</th><th className="p-2">Due</th><th className="p-2">Status</th><th className="p-2">Action</th></tr></thead><tbody>{sheets.map(s=>{const [text,cls]=badge(s);return <tr key={s.id} className="border-b border-[var(--school-border)]"><td className="p-2"><p className="font-black">{s.member_name}</p><p className="mt-0.5 text-[10px] text-[var(--school-muted)]">{s.member_id} · {s.designation||s.member_type}</p></td><td className="p-2">{s.department||"-"}</td><td className="p-2">{s.present_days}/{s.working_days}<span className="text-[10px] text-[var(--school-muted)]"> present</span></td><td className="p-2">৳ {money(Number(s.base_salary))}</td><td className="p-2">৳ {money(Number(s.gross_earned)+Number(s.bonus_amount||0)+Number(s.extra_payment||0)+Number(s.other_earnings||0))}</td><td className="p-2 text-amber-700">৳ {money(Number(s.deductions))}</td><td className="p-2 font-black">৳ {money(Number(s.payable_salary))}</td><td className="p-2 font-semibold">৳ {money(Number(s.paid_amount))}</td><td className="p-2 font-black text-red-600">৳ {money(Number(s.due_amount))}</td><td className="p-2"><span className={`rounded-full px-2.5 py-1 text-[9px] font-black ${cls}`}>{text}</span></td><td className="p-2"><div className="flex gap-2">{canApprove&&s.status!=="paid"&&<button disabled={busy===s.id} onClick={()=>void approve(s)} className="rounded-lg border border-[var(--school-border)] px-3 py-2 text-[10px] font-black disabled:opacity-50">Approve</button>}{canPay&&Number(s.due_amount)>0&&<button disabled={busy===s.id} onClick={()=>openPay(s)} className="rounded-lg theme-primary-bg px-3 py-2 text-[10px] font-black disabled:opacity-50">Pay</button>}</div></td></tr>})}</tbody></table></div>
  {sheets.length===0&&<p className="mt-5 rounded-xl border border-dashed border-[var(--school-border)] p-6 text-center text-xs text-[var(--school-muted)]">No salary sheets found for {monthLabel(month)}.</p>}
  {paying&&<div className="mt-5 rounded-2xl border border-[var(--school-primary-border)] bg-[var(--school-primary-soft)] p-5"><div className="flex items-start justify-between gap-3"><div><p className="text-[10px] font-black uppercase tracking-wider theme-primary">Salary Payment</p><h4 className="mt-1 text-base font-black">{paying.member_name} · {paying.member_id}</h4><p className="mt-1 text-xs text-[var(--school-muted)]">{monthLabel(paying.payroll_month)} · Total ৳ {money(Number(paying.payable_salary))} · Already Paid ৳ {money(Number(paying.paid_amount))} · Due ৳ {money(Number(paying.due_amount))}</p></div><button onClick={()=>setPaying(null)} className="rounded-lg border border-[var(--school-border)] px-3 py-1.5 text-xs font-bold">Cancel</button></div><div className="mt-4 grid gap-3 sm:grid-cols-2 lg:grid-cols-4"><label className="text-[10px] font-bold">Payment Amount<input type="number" min="0.01" max={Number(paying.due_amount)} step="0.01" value={amount} onChange={e=>setAmount(e.target.value)} className="mt-1 w-full rounded-xl border border-[var(--school-border)] bg-[var(--school-surface)] px-3 py-3 text-xs font-bold"/></label><label className="text-[10px] font-bold">Payment Method<select value={method} onChange={e=>setMethod(e.target.value)} className="mt-1 w-full rounded-xl border border-[var(--school-border)] bg-[var(--school-surface)] px-3 py-3 text-xs font-bold"><option value="cash">Cash</option><option value="bank">Bank</option><option value="mobile_banking">Mobile Banking</option><option value="cheque">Cheque</option></select></label><label className="text-[10px] font-bold">Reference No.<input value={reference} onChange={e=>setReference(e.target.value)} placeholder="Optional" className="mt-1 w-full rounded-xl border border-[var(--school-border)] bg-[var(--school-surface)] px-3 py-3 text-xs"/></label><label className="text-[10px] font-bold">Note<input value={note} onChange={e=>setNote(e.target.value)} placeholder="Optional" className="mt-1 w-full rounded-xl border border-[var(--school-border)] bg-[var(--school-surface)] px-3 py-3 text-xs"/></label></div><div className="mt-4 flex justify-end"><button disabled={busy===paying.id} onClick={()=>void pay()} className="rounded-xl theme-primary-bg px-5 py-3 text-xs font-black disabled:opacity-50">{busy===paying.id?"Processing...":"Confirm Payment"}</button></div></div>}
 </section>;
}
