"use client";
import { FormEvent, useCallback, useEffect, useMemo, useState } from "react";
import { createClient } from "@/lib/supabase/client";

type Perms=Record<string,any>;
type Item={id:string;item_code:string;item_name:string;specification:string|null;unit:string;current_stock:number};
type PRItem={id:string;item_id:string;item_code:string;item_name:string;specification:string|null;unit:string;requested_quantity:number;approved_quantity:number};
type PR={id:string;pr_number:string;requester_name:string;requester_member_id:string|null;status:string;items:PRItem[]};
type POItem={id:string;item_id:string;item_code:string;item_name:string;unit:string;ordered_quantity:number;received_quantity:number;unit_price:number;line_total:number};
type PO={id:string;po_number:string;pr_number:string;supplier_name:string;status:string;items:POItem[];accounts:{clearance_status:string;total_amount:number;paid_amount:number;due_amount:number}|null};
const money=(n:number)=>`৳ ${new Intl.NumberFormat("en-BD",{minimumFractionDigits:2,maximumFractionDigits:2}).format(Number(n)||0)}`;
const label=(s:string)=>s.replace(/_/g," ").toUpperCase();

export default function ProcurementWorkspaceV3({permissions={},adminMode=false}:{permissions?:Perms;adminMode?:boolean}){
 const db=useMemo(()=>createClient(),[]); const token=typeof window!=="undefined"?localStorage.getItem("ctms_store_token"):null;
 const can=useMemo(()=>((key:string)=>adminMode||Boolean(permissions.procurement?.[key])),[adminMode,permissions]);
 const [tab,setTab]=useState<"pr"|"po">("pr"),[prs,setPrs]=useState<PR[]>([]),[pos,setPos]=useState<PO[]>([]),[items,setItems]=useState<Item[]>([]),[search,setSearch]=useState(""),[status,setStatus]=useState(""),[busy,setBusy]=useState(false),[msg,setMsg]=useState(""),[err,setErr]=useState("");
 const [newPr,setNewPr]=useState(false),[selected,setSelected]=useState<Record<string,string>>({}),[details,setDetails]=useState(""),[prApproval,setPrApproval]=useState<PR|null>(null),[approvedQty,setApprovedQty]=useState<Record<string,string>>({}),[convert,setConvert]=useState<PR|null>(null),[supplier,setSupplier]=useState("");
 const [accountsPo,setAccountsPo]=useState<PO|null>(null),[adminPo,setAdminPo]=useState<PO|null>(null),[adminLines,setAdminLines]=useState<Record<string,{qty:string;price:string}>>({}),[paymentPo,setPaymentPo]=useState<PO|null>(null);
 const reset=()=>{setMsg("");setErr("")};
 const load=useCallback(async()=>{if(!token)return; reset(); if(can("pr_view")||can("pr_make")||can("pr_approve")){const r=await db.rpc("store_procurement_list_prs",{p_token:token,p_search:tab==="pr"?search||null:null,p_status:tab==="pr"?status||null:null});if(r.error)setErr(r.error.message);else setPrs((r.data||[]) as PR[]);} if(can("pr_make")){const r=await db.rpc("store_list_items",{p_token:token,p_search:""});if(!r.error)setItems((r.data||[]) as Item[]);} if(can("po_view")||can("po_history")||can("po_accounts_submit")||can("po_payment_approve")||can("po_payment_paid")||can("po_restock")||can("po_approve")){const r=await db.rpc("store_procurement_list_pos",{p_token:token,p_search:tab==="po"?search||null:null,p_status:tab==="po"?status||null:null});if(r.error)setErr(r.error.message);else setPos((r.data||[]) as PO[]);}},[can,db,search,status,tab,token]);
 useEffect(()=>{void load()},[load]);
 async function createPr(e:FormEvent<HTMLFormElement>){e.preventDefault();if(!token)return;const list=Object.entries(selected).map(([item_id,quantity])=>({item_id,quantity:Number(quantity),note:""})).filter(x=>x.quantity>0);if(!list.length){setErr("Select item(s) and enter quantity.");return}setBusy(true);reset();const r=await db.rpc("store_procurement_create_pr",{p_token:token,p_request_details:details,p_items:list});if(r.error)setErr(r.error.message);else{setNewPr(false);setSelected({});setDetails("");setMsg(`${r.data.pr_number} submitted to Admin.`);await load()}setBusy(false)}
 async function approvePr(e:FormEvent<HTMLFormElement>){e.preventDefault();if(!token||!prApproval)return;setBusy(true);reset();const r=await db.rpc("store_procurement_approve_pr",{p_token:token,p_request_id:prApproval.id,p_approved_items:prApproval.items.map(i=>({id:i.id,approved_quantity:Number(approvedQty[i.id]||0)})),p_admin_note:""});if(r.error)setErr(r.error.message);else{setPrApproval(null);setMsg(`${prApproval.pr_number} ${r.data.status}.`);await load()}setBusy(false)}
 async function convertPr(e:FormEvent<HTMLFormElement>){e.preventDefault();if(!token||!convert)return;setBusy(true);reset();const r=await db.rpc("store_procurement_convert_pr_to_po",{p_token:token,p_request_id:convert.id,p_supplier_name:supplier});if(r.error)setErr(r.error.message);else{setConvert(null);setTab("po");setMsg(`${r.data.po_number} generated and sent to Accounts for pricing.`);await load()}setBusy(false)}
 async function submitAccounts(e:FormEvent<HTMLFormElement>){e.preventDefault();if(!token||!accountsPo)return;setBusy(true);reset();const fd=new FormData(e.currentTarget);const prices=accountsPo.items.map(i=>({id:i.id,unit_price:Number((fd.get(`price-${i.id}`)||0))}));const r=await db.rpc("store_procurement_accounts_submit",{p_token:token,p_po_id:accountsPo.id,p_expense_date:String(fd.get("date")),p_due_date:String(fd.get("due")||"")||null,p_expense_note:String(fd.get("note")||"")||null,p_item_prices:prices});if(r.error)setErr(r.error.message);else{setAccountsPo(null);setMsg(`${accountsPo.po_number} pricing submitted to Admin for quantity and price approval.`);await load()}setBusy(false)}
 async function approvePo(e:FormEvent<HTMLFormElement>){e.preventDefault();if(!token||!adminPo)return;setBusy(true);reset();const payload=adminPo.items.map(i=>({id:i.id,approved_quantity:Number(adminLines[i.id]?.qty||0),unit_price:Number(adminLines[i.id]?.price||0)}));const r=await db.rpc("store_procurement_approve_po",{p_token:token,p_po_id:adminPo.id,p_approved_items:payload});if(r.error)setErr(r.error.message);else{setAdminPo(null);setMsg(`${adminPo.po_number} approved by Admin. It is now back with Accounts for payment.`);await load()}setBusy(false)}
 async function approvePayment(po:PO){if(!token)return;setBusy(true);reset();const r=await db.rpc("store_procurement_accounts_approve",{p_token:token,p_po_id:po.id});if(r.error)setErr(r.error.message);else setMsg(`${po.po_number} payment clearance approved.`);await load();setBusy(false)}
 async function pay(e:FormEvent<HTMLFormElement>){e.preventDefault();if(!token||!paymentPo)return;setBusy(true);reset();const fd=new FormData(e.currentTarget);const r=await db.rpc("store_procurement_accounts_pay",{p_token:token,p_po_id:paymentPo.id,p_amount:Number(fd.get("amount")),p_payment_method:String(fd.get("method")),p_account_name:String(fd.get("account")||"")||null,p_reference_no:String(fd.get("ref")||"")||null,p_note:String(fd.get("note")||"")||null});if(r.error)setErr(r.error.message);else{setPaymentPo(null);setMsg(`${paymentPo.po_number} payment recorded.`);await load()}setBusy(false)}
 async function restock(po:PO){if(!token)return;setBusy(true);reset();const r=await db.rpc("store_procurement_restock",{p_token:token,p_po_id:po.id});if(r.error)setErr(r.error.message);else setMsg(`${po.po_number} stock-in completed and inventory updated.`);await load();setBusy(false)}
 if(!can("pr_view")&&!can("pr_make")&&!can("pr_approve")&&!can("po_view")&&!can("po_history")&&!can("po_accounts_submit")&&!can("po_payment_approve")&&!can("po_payment_paid")&&!can("po_restock")&&!can("po_approve"))return null;
 const total=(p:PO)=>p.items.reduce((n,i)=>n+Number(i.ordered_quantity)*Number(i.unit_price||0),0); const restockReady=(p:PO)=>can("po_restock")&&Boolean(p.accounts&&["approved","partial_paid","paid"].includes(p.accounts.clearance_status));
 return <section className="mt-5 rounded-3xl border border-[var(--school-border)] bg-[var(--school-surface)] shadow-sm">
  <header className="border-b border-[var(--school-border)] bg-[var(--school-primary-soft)] p-5 sm:p-6"><div className="flex flex-wrap items-end justify-between gap-3"><div><p className="text-[10px] font-black uppercase tracking-[.16em] theme-primary">Procurement • PR & PO</p><h2 className="mt-1 text-2xl font-black">PR → PO → Accounts → Admin → Payment</h2><p className="mt-1 text-xs text-[var(--school-muted)]">PR approval creates the PO. Accounts enters item prices first. Admin then checks price and quantity, approves the PO, and Accounts completes payment.</p></div>{can("pr_make")&&<button onClick={()=>{reset();setNewPr(true)}} className="rounded-xl px-4 py-2.5 text-xs font-black theme-primary-bg">+ New PR</button>}</div><div className="mt-4 flex gap-2"><button onClick={()=>{setTab("pr");setStatus("")}} className={`rounded-xl px-4 py-2.5 text-xs font-black ${tab==="pr"?"theme-primary-bg":"border border-[var(--school-border)]"}`}>PR Requests</button><button onClick={()=>{setTab("po");setStatus("")}} className={`rounded-xl px-4 py-2.5 text-xs font-black ${tab==="po"?"theme-primary-bg":"border border-[var(--school-border)]"}`}>PO & Accounts</button></div></header>
  {msg&&<p className="mx-5 mt-5 rounded-xl border border-[var(--school-primary-border)] bg-[var(--school-primary-soft)] p-3 text-xs font-semibold theme-primary">{msg}</p>}{err&&<p className="mx-5 mt-5 rounded-xl border border-red-200 bg-red-50 p-3 text-xs text-red-700">{err}</p>}
  <div className="p-5 sm:p-6"><div className="mb-4 flex gap-2"><input className="field min-w-0 flex-1" value={search} onChange={e=>setSearch(e.target.value)} placeholder={tab==="pr"?"Search PR / requester ID":"Search PO / PR / supplier"}/><select className="field w-52" value={status} onChange={e=>setStatus(e.target.value)}><option value="">All Status</option>{(tab==="pr"?["submitted","approved","rejected","converted"]:["submitted","accounts_submitted","approved","accounts_approved","partial_paid","paid","partially_received","received"]).map(s=><option key={s} value={s}>{label(s)}</option>)}</select><button onClick={()=>void load()} className="rounded-xl px-4 py-2.5 text-xs font-black theme-primary-bg">Refresh</button></div>
   {tab==="pr"?<div className="overflow-x-auto rounded-2xl border border-[var(--school-border)]"><table className="w-full min-w-[950px] text-xs"><thead className="bg-[var(--school-primary-soft)]"><tr>{["PR","Requester ID","Items","Requested","Approved","Status","Action"].map(h=><th key={h} className="p-3 text-left text-[9px] uppercase text-[var(--school-muted)]">{h}</th>)}</tr></thead><tbody>{prs.map(p=><tr key={p.id} className="border-t border-[var(--school-border)]"><td className="p-3 font-black theme-primary">{p.pr_number}</td><td className="p-3"><b>{p.requester_name}</b><div className="text-[10px] text-[var(--school-muted)]">{p.requester_member_id||"-"}</div></td><td className="p-3">{p.items.length}</td><td className="p-3">{p.items.reduce((n,i)=>n+Number(i.requested_quantity),0)}</td><td className="p-3">{p.items.reduce((n,i)=>n+Number(i.approved_quantity),0)}</td><td className="p-3">{label(p.status)}</td><td className="p-3 flex gap-2">{can("pr_approve")&&p.status==="submitted"&&<button onClick={()=>{setPrApproval(p);setApprovedQty(Object.fromEntries(p.items.map(i=>[i.id,String(i.requested_quantity)])))}} className="rounded-lg px-2.5 py-1.5 text-[10px] font-black theme-primary-bg">Approve Qty</button>}{can("pr_convert_po")&&p.status==="approved"&&<button onClick={()=>{setConvert(p);setSupplier("")}} className="rounded-lg border px-2.5 py-1.5 text-[10px] font-black">Generate PO</button>}</td></tr>)}</tbody></table></div>:
   <div className="overflow-x-auto rounded-2xl border border-[var(--school-border)]"><table className="w-full min-w-[1500px] text-xs"><thead className="bg-[var(--school-primary-soft)]"><tr>{["PO","PR","Supplier","Items","PO Total","Accounts","Paid","Due","Status","Action"].map(h=><th key={h} className="p-3 text-left text-[9px] uppercase text-[var(--school-muted)]">{h}</th>)}</tr></thead><tbody>{pos.map(p=><tr key={p.id} className="border-t border-[var(--school-border)]"><td className="p-3 font-black theme-primary">{p.po_number}</td><td className="p-3">{p.pr_number}</td><td className="p-3 font-bold">{p.supplier_name}</td><td className="p-3">{p.items.length}</td><td className="p-3">{total(p)>0?money(total(p)):"Price pending"}</td><td className="p-3">{p.accounts?money(p.accounts.total_amount):"Not submitted"}</td><td className="p-3">{p.accounts?money(p.accounts.paid_amount):"-"}</td><td className="p-3">{p.accounts?money(p.accounts.due_amount):"-"}</td><td className="p-3">{label(p.status)}{p.accounts?` / ${label(p.accounts.clearance_status)}`:""}</td><td className="p-3 flex flex-wrap gap-2">
   {can("po_accounts_submit")&&p.status==="submitted"&&!p.accounts&&<button onClick={()=>setAccountsPo(p)} className="rounded-lg border px-2.5 py-1.5 text-[10px] font-black">Accounts Pricing</button>}
   {can("po_approve")&&p.status==="accounts_submitted"&&<button onClick={()=>{setAdminPo(p);setAdminLines(Object.fromEntries(p.items.map(i=>[i.id,{qty:String(i.ordered_quantity),price:String(i.unit_price||"")}])) )}} className="rounded-lg px-2.5 py-1.5 text-[10px] font-black theme-primary-bg">Admin Check & Approval</button>}
   {can("po_payment_approve")&&p.accounts?.clearance_status==="submitted"&&p.status==="approved"&&<button onClick={()=>void approvePayment(p)} className="rounded-lg border px-2.5 py-1.5 text-[10px] font-black">Payment Approval</button>}
   {can("po_payment_paid")&&p.accounts&&["approved","partial_paid"].includes(p.accounts.clearance_status)&&p.accounts.due_amount>0&&<button onClick={()=>setPaymentPo(p)} className="rounded-lg border px-2.5 py-1.5 text-[10px] font-black">Paid</button>}
   {can("po_restock")&&p.accounts?.clearance_status==="submitted"&&<button disabled className="rounded-lg border border-amber-200 bg-amber-50 px-2.5 py-1.5 text-[10px] font-black text-amber-700">Stock In: Clearance</button>}
   {restockReady(p)&&<button disabled={busy} onClick={()=>void restock(p)} className="rounded-lg px-2.5 py-1.5 text-[10px] font-black theme-primary-bg">Stock In</button>}
   </td></tr>)}</tbody></table></div>}</div>
  {newPr&&<div className="fixed inset-0 z-50 flex items-center justify-center bg-black/50 p-4"><form onSubmit={createPr} className="max-h-[90vh] w-full max-w-5xl overflow-auto rounded-3xl bg-[var(--school-surface)] p-5 shadow-2xl"><div className="flex justify-between"><div><p className="text-[10px] font-black uppercase theme-primary">PR Request</p><h3 className="text-xl font-black">Send Purchase Request from your ID</h3></div><button type="button" onClick={()=>setNewPr(false)} className="rounded-xl border px-3 py-2 text-xs">Close</button></div><textarea className="field mt-4 min-h-20 w-full" value={details} onChange={e=>setDetails(e.target.value)} placeholder="Requirement details"/><div className="mt-4 overflow-x-auto rounded-2xl border"><table className="w-full min-w-[850px] text-xs"><thead className="bg-[var(--school-primary-soft)]"><tr><th className="p-3">Select</th><th className="p-3 text-left">Item</th><th className="p-3 text-left">Specification</th><th className="p-3">Stock</th><th className="p-3">Qty</th></tr></thead><tbody>{items.map(i=><tr key={i.id} className="border-t"><td className="p-3"><input type="checkbox" checked={selected[i.id]!==undefined} onChange={e=>setSelected(v=>{const n={...v};if(e.target.checked)n[i.id]=n[i.id]||"1";else delete n[i.id];return n})}/></td><td className="p-3"><b>{i.item_name}</b><div className="text-[10px] theme-primary">{i.item_code}</div></td><td className="p-3">{i.specification||"-"}</td><td className="p-3">{i.current_stock} {i.unit}</td><td className="p-3"><input className="field w-24" type="number" min="0.01" step="0.01" value={selected[i.id]||""} onChange={e=>setSelected(v=>({...v,[i.id]:e.target.value}))}/></td></tr>)}</tbody></table></div><button disabled={busy} className="mt-4 w-full rounded-xl py-3 text-sm font-black theme-primary-bg">Submit PR</button></form></div>}
  {prApproval&&<div className="fixed inset-0 z-50 flex items-center justify-center bg-black/50 p-4"><form onSubmit={approvePr} className="w-full max-w-3xl rounded-3xl bg-[var(--school-surface)] p-5 shadow-2xl"><div className="flex justify-between"><h3 className="text-xl font-black">Admin PR Approval • {prApproval.pr_number}</h3><button type="button" onClick={()=>setPrApproval(null)} className="rounded-xl border px-3 py-2 text-xs">Close</button></div><div className="mt-4 space-y-2">{prApproval.items.map(i=><div key={i.id} className="grid grid-cols-[1fr_130px] gap-3 rounded-2xl border p-3"><div><b>{i.item_name}</b><div className="text-[10px] theme-primary">Requested {i.requested_quantity} {i.unit}</div></div><input className="field" type="number" min="0" step="0.01" value={approvedQty[i.id]||"0"} onChange={e=>setApprovedQty(v=>({...v,[i.id]:e.target.value}))}/></div>)}</div><button disabled={busy} className="mt-4 w-full rounded-xl py-3 text-sm font-black theme-primary-bg">Approve PR Quantities</button></form></div>}
  {convert&&<div className="fixed inset-0 z-50 flex items-center justify-center bg-black/50 p-4"><form onSubmit={convertPr} className="w-full max-w-xl rounded-3xl bg-[var(--school-surface)] p-5 shadow-2xl"><div className="flex justify-between"><div><p className="text-[10px] font-black uppercase theme-primary">PR → PO</p><h3 className="text-xl font-black">{convert.pr_number}</h3></div><button type="button" onClick={()=>setConvert(null)} className="rounded-xl border px-3 py-2 text-xs">Close</button></div><label className="mt-5 block"><span className="label">Supplier / Vendor Name *</span><input className="field mt-1 w-full" required value={supplier} onChange={e=>setSupplier(e.target.value)}/></label><p className="mt-3 rounded-xl bg-[var(--school-primary-soft)] p-3 text-xs theme-primary">Only Admin-approved PR quantities are cloned into the new PO. The new PO goes to Accounts first for item-wise pricing.</p><button disabled={busy} className="mt-4 w-full rounded-xl py-3 text-sm font-black theme-primary-bg">Generate PO</button></form></div>}
  {accountsPo&&<div className="fixed inset-0 z-50 flex items-center justify-center bg-black/50 p-4"><form onSubmit={submitAccounts} className="max-h-[90vh] w-full max-w-4xl overflow-auto rounded-3xl bg-[var(--school-surface)] p-5 shadow-2xl"><div className="flex justify-between"><div><p className="text-[10px] font-black uppercase theme-primary">Accounts • PO Pricing</p><h3 className="text-xl font-black">{accountsPo.po_number}</h3><p className="text-xs text-[var(--school-muted)]">Enter the actual item-wise price. Then submit to Admin for final PO quantity and price approval.</p></div><button type="button" onClick={()=>setAccountsPo(null)} className="rounded-xl border px-3 py-2 text-xs">Close</button></div><div className="mt-4 space-y-2">{accountsPo.items.map(i=><div key={i.id} className="grid grid-cols-[1fr_110px_140px] items-center gap-3 rounded-xl border p-3"><div><b className="text-xs">{i.item_name}</b><div className="text-[10px] theme-primary">{i.item_code} • Qty {i.ordered_quantity} {i.unit}</div></div><span className="text-xs text-[var(--school-muted)]">Qty fixed from PR approval</span><input name={`price-${i.id}`} className="field" type="number" min="0.01" step="0.01" required placeholder="Unit Price" defaultValue={i.unit_price||""}/></div>)}</div><div className="mt-4 grid gap-3 sm:grid-cols-2"><input name="date" className="field" type="date" defaultValue={new Date().toISOString().slice(0,10)}/><input name="due" className="field" type="date"/><textarea name="note" className="field sm:col-span-2" placeholder="Accounts note"/></div><p className="mt-3 rounded-xl bg-[var(--school-primary-soft)] p-3 text-sm font-black theme-primary">Calculated total: {money(accountsPo.items.reduce((n,i)=>n+Number(i.ordered_quantity)*Number(i.unit_price||0),0))} before entered prices</p><button disabled={busy} className="mt-4 w-full rounded-xl py-3 text-sm font-black theme-primary-bg">Submit Pricing to Admin</button></form></div>}
  {adminPo&&<div className="fixed inset-0 z-50 flex items-center justify-center bg-black/50 p-4"><form onSubmit={approvePo} className="max-h-[90vh] w-full max-w-4xl overflow-auto rounded-3xl bg-[var(--school-surface)] p-5 shadow-2xl"><div className="flex justify-between"><div><p className="text-[10px] font-black uppercase theme-primary">Admin • Final PO Approval</p><h3 className="text-xl font-black">{adminPo.po_number}</h3><p className="text-xs text-[var(--school-muted)]">Check Accounts price and change approved quantity or price before final PO approval.</p></div><button type="button" onClick={()=>setAdminPo(null)} className="rounded-xl border px-3 py-2 text-xs">Close</button></div><div className="mt-4 space-y-2">{adminPo.items.map(i=><div key={i.id} className="grid grid-cols-[1fr_120px_140px_130px] items-center gap-3 rounded-xl border p-3"><div><b className="text-xs">{i.item_name}</b><div className="text-[10px] theme-primary">{i.item_code} • {i.unit}</div></div><span className="text-[10px] text-[var(--school-muted)]">Accounts Qty {i.ordered_quantity}</span><input className="field" type="number" min="0.01" step="0.01" value={adminLines[i.id]?.qty||""} onChange={e=>setAdminLines(v=>({...v,[i.id]:{...v[i.id],qty:e.target.value}}))} placeholder="Approved Qty"/><input className="field" type="number" min="0.01" step="0.01" value={adminLines[i.id]?.price||""} onChange={e=>setAdminLines(v=>({...v,[i.id]:{...v[i.id],price:e.target.value}}))} placeholder="Approved Price"/></div>)}</div><p className="mt-4 rounded-xl bg-[var(--school-primary-soft)] p-3 text-sm font-black theme-primary">Final Total: {money(adminPo.items.reduce((n,i)=>n+Number(adminLines[i.id]?.qty||0)*Number(adminLines[i.id]?.price||0),0))}</p><button disabled={busy} className="mt-4 w-full rounded-xl py-3 text-sm font-black theme-primary-bg">Approve PO & Send to Accounts Payment</button></form></div>}
  {paymentPo&&<div className="fixed inset-0 z-50 flex items-center justify-center bg-black/50 p-4"><form onSubmit={pay} className="w-full max-w-xl rounded-3xl bg-[var(--school-surface)] p-5 shadow-2xl"><div className="flex justify-between"><div><p className="text-[10px] font-black uppercase theme-primary">Accounts • Payment</p><h3 className="text-xl font-black">{paymentPo.po_number}</h3><p className="text-xs text-[var(--school-muted)]">Due {money(paymentPo.accounts?.due_amount||0)}</p></div><button type="button" onClick={()=>setPaymentPo(null)} className="rounded-xl border px-3 py-2 text-xs">Close</button></div><div className="mt-4 grid gap-3 sm:grid-cols-2"><input name="amount" className="field" type="number" min="0.01" max={paymentPo.accounts?.due_amount||0} step="0.01" required placeholder="Payment amount"/><select name="method" className="field"><option value="cash">Cash</option><option value="bank">Bank</option><option value="cheque">Cheque</option><option value="mobile_banking">Mobile Banking</option><option value="other">Other</option></select><input name="account" className="field" placeholder="Account / Bank"/><input name="ref" className="field" placeholder="Reference No."/><textarea name="note" className="field sm:col-span-2" placeholder="Payment note"/></div><button disabled={busy} className="mt-4 w-full rounded-xl py-3 text-sm font-black theme-primary-bg">Record Payment</button></form></div>}
 </section>;
}
